import {labAttribute,labP,labOp,labWire,labStep,labScenario} from './lab-common.js';

const branchOAuth='https://www.rfc-editor.org/rfc/rfc6749';
const branchOidc='https://openid.net/specs/openid-connect-core-1_0.html';
const branchBcp='https://www.rfc-editor.org/rfc/rfc9700';
const branchAdmin='https://www.keycloak.org/docs/latest/server_admin/index.html';
const branchWebauthn='https://www.w3.org/TR/webauthn-3/';
const branchA=(name,meaning,origin,purpose,example,standard='RFC 6749',source=branchOAuth)=>labAttribute(name,meaning,origin,purpose,example,standard,source);
export const BRANCHLAB_ATTRIBUTES={
  branchClientId:branchA('client_id','The public identifier of this registered application.','An administrator registers learning-client in the realm.','Selects the configured client and its permitted grant and redirect policy. It does not authenticate the client.','learning-client','RFC 6749 §2.2'),
  branchClientSecret:branchA('client_secret','A confidential backend credential.','Provisioned to the registered backend and retained on that backend.','Authenticates the confidential client at the token endpoint, separately from any person’s credential; it is absent from public browser clients.','protected-backend-secret','RFC 6749 §2.3.1'),
  branchAuthorization:branchA('Authorization','HTTP Basic client authentication.','The confidential backend encodes its form-encoded identifier and secret.','Authenticates the backend over TLS, separately from the user credentials.','Basic <encoded learning-client:secret>','RFC 6749 §2.3.1'),
  branchGrantType:branchA('grant_type','The token-endpoint operation selected by the client.','The application sets the registered grant identifier.','Distinguishes the deprecated password grant from code redemption.','password / authorization_code','RFC 6749 §4.1.3 / §4.3.2'),
  branchUsername:branchA('username','The account identifier supplied in the password grant.','The person enters an account name in the requesting application.','Identifies the account whose password the server must verify; identification is not authentication.','alex','RFC 6749 §4.3.2'),
  branchPassword:branchA('password','The person’s account password.','The person supplies it to this legacy application.','The application forwards it directly to the token endpoint in this deprecated grant, exposing the credential to another participant.','<person’s password>','RFC 6749 §4.3.2 / RFC 9700 §2.4',branchBcp),
  branchPasswordHash:branchA('Password verifier (local configuration)','The server’s protected password verifier.','Provisioned by account enrollment and stored by Realm A.','Verifies the password locally; the stored verifier never travels to the application.','protected server-side verifier','Keycloak credential policy',branchAdmin),
  branchScope:branchA('scope','The space-delimited requested or granted permissions.','The client requests configured scopes; the server applies client, user and consent policy.','Controls the permissions included in the resulting grant.','openid profile orders.read','RFC 6749 §3.3'),
  branchAccessToken:branchA('access_token','The authorization credential intended for an API.','Realm A issues it after the applicable grant checks.','Authorizes a resource request; it is distinct from an OIDC identity result.','<access-token>','RFC 6749 §5.1'),
  branchIdToken:branchA('id_token','A signed OIDC identity result for the client.','Realm A signs the identity result under its trusted issuer key.','The application verifies issuer, audience, lifetime and the request’s nonce and hash bindings when applicable.','<signed-ID-token>','OIDC Core §2',branchOidc),
  branchRefreshToken:branchA('refresh_token','A token for later redemption at the token endpoint.','Realm A issues it only when this grant and policy allow it.','Allows the client to request replacement tokens; the implicit token response omits it.','<refresh-token>','RFC 6749 §5.1'),
  branchTokenType:branchA('token_type','The usage scheme for the access token.','The authorization server sets the response member.','Tells the caller how to present the access token.','Bearer','RFC 6749 §5.1'),
  branchExpiresIn:branchA('expires_in','The access-token lifetime in seconds.','Realm A calculates the response lifetime under its policy.','Allows the client to track expiry without extending the token’s validity.','300','RFC 6749 §5.1'),
  branchResponseType:branchA('response_type','The requested authorization response.','The client selects the configured OIDC response type.','This lab compares implicit id_token token with hybrid code id_token token.','id_token token / code id_token token','OIDC Core §3.2 / §3.3',branchOidc),
  branchRedirectUri:branchA('redirect_uri','The registered application callback.','Configured during client registration and reused in the request.','The server checks the exact registered destination before returning a result.','https://learning.example.test/callback','RFC 6749 §3.1.2'),
  branchState:branchA('state','A request-specific callback correlation value.','The client creates and stores an unpredictable value before navigation.','The client compares it before accepting success or error callbacks.','fresh-request-state','RFC 6749 §4.1.1'),
  branchNonce:branchA('nonce','A request-specific binding for the OIDC ID token.','The client creates it before the authorization request.','The provider includes it in the ID token, and the client compares it locally.','fresh-request-nonce','OIDC Core §3.2.2.1',branchOidc),
  branchCode:branchA('code','A short-lived, client-bound authorization code.','Realm A creates it after interactive authentication and authorization.','The hybrid flow redeems it on a separate token-endpoint exchange; it is not an access token.','single-use-hybrid-code','RFC 6749 §4.1.2'),
  branchVerifier:branchA('code_verifier','The secret proof used to redeem the hybrid code.','The application generates a fresh high-entropy value locally.','Proves that the code redeemer holds the original commitment; it stays off browser authorization messages.','<fresh-verifier>','RFC 7636 §4.1','https://www.rfc-editor.org/rfc/rfc7636'),
  branchChallenge:branchA('code_challenge','The S256 commitment to the verifier.','The application computes BASE64URL(SHA256(ASCII(code_verifier))).','Realm A stores it with the code and checks it during redemption.','<S256-commitment>','RFC 7636 §4.2','https://www.rfc-editor.org/rfc/rfc7636'),
  branchChallengeMethod:branchA('code_challenge_method','The PKCE transform identifier.','The application selects S256.','Tells the server which verifier transform to recompute.','S256','RFC 7636 §4.3','https://www.rfc-editor.org/rfc/rfc7636'),
  branchCHash:branchA('c_hash','The OIDC ID-token hash binding for the front-channel code.','Realm A hashes the ASCII code with the JWS algorithm’s hash, takes its left half and Base64url encodes it.','The hybrid client recomputes it to bind the returned code to the verified ID token.','BASE64URL(left-half(HASH(code)))','OIDC Core §3.3.2.11',branchOidc),
  branchAtHash:branchA('at_hash','The OIDC ID-token hash binding for a front-channel access token.','Realm A hashes the ASCII access token with the JWS algorithm’s hash, takes its left half and Base64url encodes it.','The client recomputes it when it accepts a front-channel access token.','BASE64URL(left-half(HASH(access_token)))','OIDC Core §3.2.2.9',branchOidc),
  branchSigningKey:branchA('Private signing key (local)','The realm’s protected token-signing key.','Configured and retained by Realm A.','Signs ID-token and action-token JWS locally; it is never a message member.','protected realm key','RFC 7515 §5','https://www.rfc-editor.org/rfc/rfc7515'),
  branchVerificationKey:branchA('Public verification key (trusted local input)','The issuer key the client trusts for signature checks.','Obtained from configured issuer metadata and trusted JWKS.','Verifies the issuer signature before claims and hash bindings are accepted.','trusted public JWK','OIDC Core §3.1.3.7',branchOidc),
  branchIssuer:branchA('iss','The trusted identity-token issuer identifier.','Realm A inserts its configured HTTPS issuer URL.','The client compares it with the configured issuer after signature verification.','https://idp1.example.test/realms/realm-a','OIDC Core §2',branchOidc),
  branchIdentitySubject:branchA('sub','The authenticated person’s stable subject identifier within this OIDC issuer.','Realm A resolves the person after provider-side authentication and puts the subject in its signed ID token.','Together with iss, identifies the authenticated person. Hybrid ID tokens from the authorization and token endpoints must preserve this same subject and issuer.','person-in-realm-a-204','OIDC Core §2 / §3.3.3.6',branchOidc),
  branchFirstIdentityPair:branchA('Verified (iss, sub) pair (local state)','The issuer and subject retained from the verified front-channel ID token.','The client derives and stores this pair only after signature, claim and request-binding validation.','Compares the token-endpoint ID-token identity with the first verified identity. The identical issued-token relationship is specified in §3.3.3.6; this local consistency check illustrates that relationship.','{"iss":"https://idp1.example.test/realms/realm-a","sub":"person-in-realm-a-204"}','OIDC Core §3.3.3.6; local client consistency check',branchOidc),
  branchAudience:branchA('aud','The client audience of the identity token.','Realm A binds the identity result to learning-client.','The client checks that the ID token was intended for its own registration.','learning-client','OIDC Core §2',branchOidc),
  branchExp:branchA('exp','The expiration NumericDate of the signed result.','The issuer calculates it from the applicable lifetime.','The recipient rejects an expired ID or action token.','issued-at + permitted lifetime','RFC 7519 §4.1.4','https://www.rfc-editor.org/rfc/rfc7519'),
  branchPrompt:branchA('prompt','A requested interaction policy.','The OIDC client chooses consent for this example.','Asks the provider to obtain consent; it does not override registered client and user permissions.','consent','OIDC Core §3.1.2.1',branchOidc),
  branchConsent:branchA('Consent decision (local UI action)','The person’s deliberate approval or denial of the presented request.','The person acts on the provider’s authenticated consent page.','The provider issues the allowed grant only after approval, or returns access_denied after refusal.','approve / deny','Keycloak consent UI / RFC 6749 §4.1.2.1',branchAdmin),
  branchError:branchA('error','The protocol error identifier.','The rejecting participant constructs the applicable error response.','Ends this failed attempt; it must not be treated as a token or successful login.','access_denied / invalid_grant','RFC 6749 §4.1.2.1 / §5.2'),
  branchErrorDescription:branchA('error_description','An optional human-readable protocol error explanation.','The rejecting endpoint creates it without sensitive credential details.','Helps diagnose failure while the error identifier controls behavior.','This authorization request was denied.','RFC 6749 §4.1.2.1 / §5.2'),
  branchExternalSubject:branchA('sub','The stable subject asserted by the independent upstream issuer.','The upstream provider issues a verified identity result.','Realm A resolves the pair (upstream iss, sub), rather than treating an email address as proof of account ownership.','partner-account-405','OIDC Core §2',branchOidc),
  branchExternalIssuer:branchA('iss','The issuer of the brokered upstream identity result.','The independent provider inserts its registered issuer URL.','Realm A checks the trusted issuer and pairs it with sub before account linking.','https://login.partner.example.test','OIDC Core §2',branchOidc),
  branchEmail:branchA('email','An optional contact claim of the upstream identity.','The configured upstream provider supplies the claim.','May help suggest an existing account; matching email alone does not prove ownership of that local account.','alex@example.test','OIDC Core §5.1',branchOidc),
  branchEmailVerified:branchA('email_verified','Whether the upstream issuer states it verified the contact address.','The provider sets it under its own policy.','A verified contact claim still requires an explicitly trusted account-link policy; this lab requires local-account reauthentication.','true','OIDC Core §5.1',branchOidc),
  branchLocalAccount:branchA('Local account record (protected configuration)','The existing local identity to which the external account may be linked.','Realm A holds the account and its enrolled credentials.','The account-linking flow verifies control of this account before modifying its identity links.','local-account-204','Keycloak First Broker Login flow',branchAdmin),
  branchIdentityLink:branchA('Federated identity link (local record)','The mapping from a verified external issuer/subject pair to a local account.','Realm A creates the record after explicit linking and local-account verification.','Future brokered logins resolve the verified pair to the correct local subject.','(partner issuer, partner subject) → local-account-204','Keycloak First Broker Login flow',branchAdmin),
  branchChallengeLogin:branchA('challenge','Fresh WebAuthn relying-party challenge bytes.','Realm A creates an unpredictable challenge for this attempt.','Binds a possible assertion to this ceremony; cancellation produces no signed assertion.','fresh-WebAuthn-challenge','WebAuthn §5.1.2',branchWebauthn),
  branchRpId:branchA('rpId','The domain scope for the requested WebAuthn credential.','The relying party configures idp1.example.test.','The browser restricts credential use to the relying party’s allowed domain.','idp1.example.test','WebAuthn §5.1.2',branchWebauthn),
  branchNotAllowed:branchA('NotAllowedError','A local WebAuthn API failure result.','The browser rejects navigator.credentials.get() after cancellation, timeout or an unavailable credential.','The application treats it as an unfinished ceremony; no assertion is sent and no login is granted.','DOMException: NotAllowedError','WebAuthn §5.1.2',branchWebauthn),
  branchFallback:branchA('Fallback policy (local configuration)','The configured permitted alternative method.','An administrator configures the realm’s browser authentication flow.','Allows a separate password verification after cancellation; it never converts cancellation into successful WebAuthn.','Password alternative after explicit user selection','Keycloak authentication flows',branchAdmin),
  branchActionToken:branchA('Action token (Keycloak signed URL value)','A short-lived signed credential for a specific account action.','Realm A creates it after a reset request and sends it to the account’s verified delivery channel.','Possession, signature, action type, subject, expiry and one-use policy are checked before password reset; requesting by username alone authenticates nobody.','<signed-reset-credentials-token>','Keycloak Action Token SPI',branchAdmin),
  branchJti:branchA('jti','The unique identifier of the signed action token.','Realm A creates it for one reset action.','A server-side replay record enforces the illustrated one-use policy.','single-use-action-id','RFC 7519 §4.1.7 / Keycloak action-token policy',branchAdmin),
  branchSubject:branchA('sub','The account subject named by a verified action token.','Realm A binds the action token to the target account.','Prevents applying a valid reset credential to another account.','local-account-204','RFC 7519 §4.1.2 / Keycloak action-token policy',branchAdmin),
  branchActionType:branchA('typ (Keycloak action-token claim)','The configured Keycloak action discriminator.','Realm A writes the registered action-token type.','Selects the reset-credentials handler; this payload discriminator is distinct from a JWS header typ.','reset-credentials','Keycloak Action Token SPI',branchAdmin),
  branchNewPassword:branchA('New password (provider form field)','The replacement account secret entered on the verified reset page.','The person enters it after presenting the validated reset credential.','The provider validates password policy and stores a new verifier; it does not return this secret to the requesting application.','<replacement-secret>','Keycloak reset-credentials flow',branchAdmin),
  branchCookie:branchA('Cookie (provider session)','The browser’s opaque identity-provider session handle.','The provider establishes it after verified authentication.','Associates the browser with a server session; cookie presence alone does not override expiry or revocation.','KC-session=<opaque-handle>','Keycloak sessions',branchAdmin),
  branchSessionPolicy:branchA('Session policy (local configuration)','The server-side idle, maximum and concurrent-session policy.','Administrators configure user/client session lifetimes and the session-count limiter.','Controls whether a server still accepts session-bound operations; a copied signed JWT may remain locally verifiable until exp unless the API consults additional state.','idle/max limits; configured session-count action','Keycloak sessions / authentication flows',branchAdmin),
  branchSessionRecord:branchA('Session record (local state)','The provider’s active or revoked user/client-session record.','Realm A stores it and applies logout, expiry and concurrency policy.','Determines whether session-dependent token operations may continue.','active → revoked','Keycloak sessions',branchAdmin),
};
export const BRANCHLAB_SOURCES=[{name:'OIDC implicit and hybrid flows',url:branchOidc},{name:'OAuth 2.0 Security BCP',url:branchBcp},{name:'Keycloak authentication and broker flows',url:branchAdmin},{name:'WebAuthn cancellation',url:branchWebauthn}];
const branchSpecs={user:{name:'Person',role:'Account owner',plainRole:'Chooses a method and authorizes the requested action.'},app:{name:'Learning application',role:'OIDC / OAuth client',plainRole:'Tracks the request and validates its result.',art:'webapp'},browser:{name:'Browser',role:'User agent',plainRole:'Carries browser navigation and provider forms.'},realmA:{name:'Keycloak · Realm A',role:'Identity provider',plainRole:'Checks the configured policy before granting access.'},realmB:{name:'Independent upstream IdP',role:'Trusted upstream issuer',plainRole:'Returns a verified upstream identity.',art:'external'},hello:{name:'Windows Hello',role:'Platform authenticator',plainRole:'Returns a proof only after completed local verification.'}};
const branchD=(id,title,from,to,summary,payload,ops,checks=[],detail=summary)=>labStep(id,title,from,to,'study',from===to?'internal':from==='user'||to==='user'?'human':from==='browser'||to==='browser'?'browser':'backchannel',summary,detail,[...new Set(ops.map(op=>op.attributeId))],payload,checks,ops);
const branchLocal=(ids,kind,actor,detail)=>labOp(ids,kind,actor,detail);
const branchSend=(ids,from,to,detail,carriedAs)=>labWire(ids,from,to,detail,carriedAs);
const branchPayload=ids=>ids.map(id=>labP(BRANCHLAB_ATTRIBUTES[id].name,BRANCHLAB_ATTRIBUTES[id].example,undefined,id));
const branchMake=(id,title,summary,status,supportNote,steps,extra={})=>{
  const used=new Set(steps.flatMap(s=>s.fields));
  const definitions=Object.fromEntries([...used].map(id=>[id,BRANCHLAB_ATTRIBUTES[id]]));
  if(id!=='lab-direct-grant'&&definitions.branchPassword)definitions.branchPassword={...definitions.branchPassword,meaning:'The account password entered on Realm A’s provider page.',description:'The account password entered on Realm A’s provider page.',origin:'The person enters the enrolled local account secret on the provider’s protected form.',generator:'The account owner',purpose:'Realm A checks this proof directly against its local verifier. Neither the initiating OAuth application nor the upstream identity provider receives this password.',standard:'Keycloak provider authentication form',source:branchAdmin};
  if(id==='lab-account-recovery')definitions.branchUsername={...definitions.branchUsername,meaning:'The account identifier in a provider credential-reset request.',origin:'The requester enters an account identifier on Realm A’s reset page.',purpose:'Selects the account’s configured verified delivery channel. Requesting a reset by account name alone authenticates nobody.',standard:'Keycloak reset-credentials flow',source:branchAdmin};
  return labScenario({id,title,summary,category:'Interaction, errors & legacy',status,supportNote,source:branchAdmin,architecture:'web',protocol:'oidc',hasPerson:true,...extra},definitions,steps,{...branchSpecs,...extra.actorSpecs});
};
const branchDirect=branchMake('lab-direct-grant','Direct Access Grant · legacy password grant','The application handles the person’s password and submits it directly to the token endpoint.','Legacy / discouraged','RFC 9700 §2.4 says the password grant MUST NOT be used. Keycloak exposes it behind Direct Access Grants; this is an educational comparison, with no WebAuthn, broker or browser redirect.',[
  branchD('branch-direct-input','The person gives credentials to the legacy app','user','app','This legacy design exposes the account password to the requesting application.',branchPayload(['branchUsername','branchPassword']),branchSend(['branchUsername','branchPassword'],'user','app','Legacy application input; this is not the provider’s browser page.')),
  branchD('branch-direct-prepare','The backend prepares separate client authentication','app','app','The confidential application authenticates itself separately from the person.',branchPayload(['branchClientId','branchClientSecret','branchAuthorization']),[...branchLocal(['branchClientId','branchClientSecret'],'use','app','Reads protected backend configuration.'),...branchLocal(['branchAuthorization'],'derive','app','Builds HTTP Basic client authentication.')] ),
  branchD('branch-direct-request','Submit the password grant over HTTPS','app','realmA','A direct token request carries grant_type=password and the user credentials.',[labP('grant_type','password',undefined,'branchGrantType'),...branchPayload(['branchAuthorization','branchUsername','branchPassword','branchScope'])],[...branchSend(['branchAuthorization','branchUsername','branchPassword','branchGrantType','branchScope'],'app','realmA','HTTPS token request; Basic client credentials and password form fields are separate.'),...branchSend(['branchClientId','branchClientSecret'],'app','realmA','Encoded confidential client credentials within the Basic header.','Authorization: Basic')]),
  branchD('branch-direct-check','Check client, grant and account password','realmA','realmA','The server checks the configured client capability and password verifier.',branchPayload(['branchPasswordHash','branchClientId','branchPassword']),[...branchLocal(['branchClientId','branchClientSecret','branchAuthorization','branchGrantType'],'verify','realmA','Requires enabled Direct Access Grants and valid client authentication.'),...branchLocal(['branchPasswordHash'],'use','realmA','Uses the protected verifier locally.'),...branchLocal(['branchUsername','branchPassword'],'verify','realmA','Verifies the selected account under the configured direct-grant policy.')],['No browser/WebAuthn/brokering is added to this grant.']),
  branchD('branch-direct-issue','Issue configured token results','realmA','realmA','This openid-scoped example issues access, identity and refresh results only after policy checks.',branchPayload(['branchAccessToken','branchIdToken','branchRefreshToken']),[...branchLocal(['branchSigningKey'],'use','realmA','Signs locally.'),...branchLocal(['branchAccessToken','branchIdToken','branchRefreshToken','branchTokenType','branchExpiresIn'],'create','realmA','Creates results under this configured client’s policy.')]),
  branchD('branch-direct-response','Return the token response','realmA','app','The HTTPS token response returns tokens to the backend, not a browser callback.',branchPayload(['branchAccessToken','branchIdToken','branchRefreshToken','branchTokenType','branchExpiresIn']),branchSend(['branchAccessToken','branchIdToken','branchRefreshToken','branchTokenType','branchExpiresIn'],'realmA','app','OAuth/OIDC JSON response.')),
]);
function branchFrontFlow(hybrid){
  const prefix=hybrid?'branch-hybrid':'branch-implicit',front=hybrid?['branchCode','branchIdToken','branchAccessToken','branchState','branchTokenType','branchExpiresIn']:['branchIdToken','branchAccessToken','branchState','branchTokenType','branchExpiresIn'];
  const request=['branchClientId','branchResponseType','branchRedirectUri','branchScope','branchState','branchNonce',...(hybrid?['branchChallenge','branchChallengeMethod']:[])];
  const identityClaims=['branchIssuer','branchIdentitySubject','branchAudience','branchNonce','branchExp'];
  const frontClaims=[...identityClaims,'branchAtHash',...(hybrid?['branchCHash']:[])];
  const requestPayload=()=>request.map(id=>labP(BRANCHLAB_ATTRIBUTES[id].name,id==='branchResponseType'?(hybrid?'code id_token token':'id_token token'):BRANCHLAB_ATTRIBUTES[id].example,undefined,id));
  const identityPayload=(ids,token)=>ids.map(id=>labP(BRANCHLAB_ATTRIBUTES[id].name,id==='branchIdToken'?token:BRANCHLAB_ATTRIBUTES[id].example,undefined,id));
  const stages=[
    branchD(prefix+'-prepare','Prepare a correlated browser request','app','app','Create state and nonce; the hybrid example also retains a PKCE verifier locally.',branchPayload(['branchState','branchNonce',...(hybrid?['branchVerifier','branchChallenge','branchChallengeMethod']:[])]),[...branchLocal(['branchState','branchNonce',...(hybrid?['branchVerifier']:[])],'create','app','Creates unpredictable per-attempt request bindings.'),...(hybrid?[...branchLocal(['branchChallengeMethod'],'use','app','Selects S256 locally before deriving the PKCE commitment.'),...branchLocal(['branchChallenge'],'derive','app','Computes the S256 commitment without exposing the verifier.')]:[]),...branchLocal(['branchClientId','branchRedirectUri','branchScope'],'use','app','Uses configured registration and permissions.')]),
    branchD(prefix+'-navigate','Open the authorization request','app','browser','The application starts the browser request; its PKCE secret is absent.',requestPayload(),branchSend(request,'app','browser','Authorization URL parameters.')),
    branchD(prefix+'-request','The browser reaches Realm A','browser','realmA','Realm A validates client, redirect and requested response type.',requestPayload(),[...branchSend(request,'browser','realmA','Authorization request over HTTPS.'),...(hybrid?branchLocal(['branchChallenge','branchChallengeMethod','branchClientId','branchRedirectUri'],'store','realmA','Retains the original PKCE commitment, method and client/redirect binding for the later single-use code.'):[])]),
    branchD(prefix+'-verify','Complete the configured browser authentication','realmA','realmA','This example begins its response stage after a valid provider-side login.',[...branchPayload(['branchClientId','branchRedirectUri','branchScope']),labP('response_type',hybrid?'code id_token token':'id_token token',undefined,'branchResponseType')],branchLocal(['branchClientId','branchRedirectUri','branchResponseType','branchScope'],'verify','realmA','Requires a verified person and permitted configured response type; the factor ceremony is covered by the core journeys.'),['No token is issued from account identification alone.']),
    branchD(prefix+'-sign','Sign the identity result and token hash bindings','realmA','realmA','The signed identity token identifies the person and binds the nonce and front-channel token; hybrid also binds its code.',branchPayload(frontClaims),[...branchLocal(['branchAccessToken',...(hybrid?['branchCode']:[]),'branchIssuer','branchIdentitySubject','branchAudience','branchExp'],'create','realmA','Creates the issuer-bound authenticated subject and client-bound result values.'),...branchLocal(['branchAtHash',...(hybrid?['branchCHash']:[])],'derive','realmA','Calculates the left-half hash required by the ID-token signing algorithm.'),...branchLocal(['branchNonce'],'use','realmA','Includes the original nonce as a nested identity claim.'),...branchLocal(['branchSigningKey'],'use','realmA','Signs locally.'),...branchLocal(['branchIdToken'],'create','realmA','Serializes the signed front-channel identity token.')]),
    branchD(prefix+'-fragment','Return tokens in the browser URL fragment','realmA','browser','This configured fragment response exposes identity/access tokens to browser-side handling.',identityPayload([...front,...frontClaims],'<front-channel signed ID token>'),[...branchSend(front,'realmA','browser','HTTP redirect Location fragment; not separate token-endpoint requests.'),...branchSend(frontClaims,'realmA','browser','Nested signed ID-token claims.','id_token (JWS)')],['The URL fragment is not sent to the callback web server.']),
    branchD(prefix+'-callback','The browser client reads its callback fragment','browser','app','The JavaScript client reads and removes the fragment before continuing.',identityPayload([...front,...frontClaims],'<front-channel signed ID token>'),[...branchSend(front,'browser','app','Local browser-to-application callback processing; the server does not receive this fragment.'),...branchSend(frontClaims,'browser','app','Reads the identity claims from the same front-channel signed ID token.','id_token (JWS)')]),
    branchD(prefix+'-checks','Verify signature, state, nonce and token hashes','app','app',hybrid?'After trust and request checks, retain the verified issuer and subject for the later identity result.':'Accept the result only after trust and request binding checks.',identityPayload(['branchIdToken','branchVerificationKey','branchIssuer','branchIdentitySubject','branchState','branchNonce','branchAtHash',...(hybrid?['branchCHash','branchFirstIdentityPair']:[])],'<front-channel signed ID token>'),[...branchLocal(['branchVerificationKey'],'use','app','Uses trusted issuer keys, not an arbitrary token-supplied URL.'),...branchLocal(['branchIdToken',...identityClaims,'branchState','branchAtHash',...(hybrid?['branchCHash']:[])],'verify','app','Verifies signature, claims, saved callback state, nonce and recomputed hash bindings.'),...(hybrid?[...branchLocal(['branchFirstIdentityPair'],'derive','app','Extracts (iss, sub) only from the now verified front-channel ID token.'),...branchLocal(['branchFirstIdentityPair'],'store','app','Retains the verified identity pair for comparison with the token-endpoint ID token.')]:[])]),
  ];
  if(hybrid)stages.push(
    branchD(prefix+'-redeem','Redeem the hybrid code with its PKCE proof','app','realmA','A separate backchannel exchange sends the retained verifier with the code.',[labP('grant_type','authorization_code',undefined,'branchGrantType'),...branchPayload(['branchClientId','branchCode','branchVerifier','branchRedirectUri'])],branchSend(['branchGrantType','branchClientId','branchCode','branchVerifier','branchRedirectUri'],'app','realmA','Public-client token request; no client secret is embedded in JavaScript.')),
    branchD(prefix+'-pkce','Validate the code and saved commitment','realmA','realmA','The server checks code ownership, one-use status, callback and S256 proof.',branchPayload(['branchCode','branchChallenge','branchVerifier']),branchLocal(['branchCode','branchClientId','branchRedirectUri','branchChallenge','branchChallengeMethod','branchVerifier'],'verify','realmA','Recomputes S256, checks the saved commitment and method, and consumes the code.')),
    branchD(prefix+'-tokens','Return the token-endpoint result with the same identity','realmA','app','The newly signed ID token preserves the first ID token’s exact issuer and subject; refresh issuance depends on policy.',identityPayload(['branchAccessToken','branchIdToken','branchRefreshToken','branchTokenType','branchExpiresIn',...identityClaims],'<token-endpoint signed ID token>'),[...branchLocal(['branchIssuer','branchIdentitySubject','branchAudience','branchNonce'],'use','realmA','Uses the same authenticated identity and original request: §3.3.3.6 requires identical iss and sub in the two issued ID tokens.'),...branchLocal(['branchSigningKey'],'use','realmA','Signs the token-endpoint identity result with the trusted issuer key.'),...branchLocal(['branchIdToken'],'create','realmA','Creates the token-endpoint ID token with the preserved issuer and subject.'),...branchSend(['branchAccessToken','branchIdToken','branchRefreshToken','branchTokenType','branchExpiresIn'],'realmA','app','Token-endpoint JSON response after successful code checks.'),...branchSend(identityClaims,'realmA','app','Nested claims of the token-endpoint identity result.','id_token (JWS)')]),
    branchD(prefix+'-final-checks','Validate the redeemed result and its shared identity','app','app','Validate the second ID token and compare its issuer/subject with the retained first verified identity.',identityPayload(['branchIdToken',...identityClaims,'branchFirstIdentityPair'],'<token-endpoint signed ID token>'),[...branchLocal(['branchVerificationKey'],'use','app','Uses the trusted issuer key for the redeemed result.'),...branchLocal(['branchFirstIdentityPair'],'use','app','Loads the retained, verified front-channel issuer/subject pair.'),...branchLocal(['branchIdToken',...identityClaims],'verify','app','Applies OIDC §3.3.3.7 token-endpoint ID-token validation (the §3.1.3.7 rules), including issuer, client audience, lifetime and original nonce.'),...branchLocal(['branchIssuer','branchIdentitySubject','branchFirstIdentityPair'],'verify','app','Checks that the two verified ID tokens have the identical iss/sub relationship required of issued tokens by §3.3.3.6. This local consistency check is not presented as a separate compare-sub bullet in §3.3.3.7.')],['Second ID-token signature and normal claims valid','Second iss equals the first verified iss','Second sub equals the first verified sub']) );
  return branchMake(hybrid?'lab-hybrid':'lab-implicit',hybrid?'Hybrid · code and front-channel tokens':'Implicit · front-channel tokens',hybrid?'Compare signed front-channel code/token bindings with the later PKCE code exchange and its identical issuer/subject identity.':'See how implicit flow exposes tokens to browser callback handling.',hybrid?'Legacy / discouraged':'Legacy / discouraged','Educational legacy comparison. Modern browser clients use Authorization Code + PKCE. Token-bearing authorization responses expose additional front-channel attack surfaces.',stages,{architecture:'native',executionEnvironment:'browser',clientActor:'app',actorSpecs:{app:{...branchSpecs.app,name:'Browser JavaScript client',role:'Public OIDC client',art:'app'}}});
}
const branchConsent=branchMake('lab-consent-denial','Consent · approval and refusal','Compare two separate requests: deliberate approval and access_denied.','Keycloak supported','Consent must be configured for the client and requested scopes. This demonstration shows independent approved and denied attempts, rather than issuing tokens after the same denial.',[
  branchD('branch-consent-prepare','Attempt A · create its request binding','app','app','The client creates and retains a fresh state for the first consent request.',[labP('state','consent-state-A',undefined,'branchState')],branchLocal(['branchState'],'create','app','Creates the first attempt’s unpredictable callback correlation.')),
  branchD('branch-consent-request','Request explicit consent','app','browser','The client requests a code at its registered redirect with prompt=consent.',[...branchPayload(['branchClientId','branchRedirectUri','branchScope','branchPrompt']),labP('response_type','code',undefined,'branchResponseType'),labP('state','consent-state-A',undefined,'branchState')],branchSend(['branchClientId','branchRedirectUri','branchResponseType','branchScope','branchPrompt','branchState'],'app','browser','Configured authorization request for attempt A.')),
  branchD('branch-consent-deliver-A','Deliver the first authorization request','browser','realmA','Realm A receives the registered client, callback, response type, permissions and request state.',[...branchPayload(['branchClientId','branchRedirectUri','branchScope','branchPrompt']),labP('response_type','code',undefined,'branchResponseType'),labP('state','consent-state-A',undefined,'branchState')],[...branchSend(['branchClientId','branchRedirectUri','branchResponseType','branchScope','branchPrompt','branchState'],'browser','realmA','HTTPS authorization request for attempt A.'),...branchLocal(['branchClientId','branchRedirectUri','branchResponseType'],'verify','realmA','Checks the configured client, exact redirect and permitted code flow; account authentication precedes consent.'),...branchLocal(['branchState'],'store','realmA','Retains consent-state-A with its pending transaction.')]),
  branchD('branch-consent-page','Present the authenticated consent page','realmA','browser','The person sees the client and requested permissions after provider authentication.',branchPayload(['branchClientId','branchScope']),branchSend(['branchClientId','branchScope'],'realmA','browser','Provider page content; not an issued grant.')),
  branchD('branch-consent-approve','Attempt A · approve this request','user','browser','The person deliberately approves the shown request.',[labP('Consent decision (local UI action)','approve',undefined,'branchConsent')],branchSend(['branchConsent'],'user','browser','Local approval interaction.')),
  branchD('branch-consent-accept','Record approved permissions','browser','realmA','The provider applies the authenticated approval to its pending transaction.',[labP('Consent decision (local UI action)','approve',undefined,'branchConsent')],branchSend(['branchConsent'],'browser','realmA','Provider-specific approval form, not an OAuth parameter.')),
  branchD('branch-consent-success','Issue only the approved grant','realmA','browser','Attempt A returns a code bound to its request and state.',[...branchPayload(['branchCode']),labP('state','consent-state-A',undefined,'branchState')],[...branchLocal(['branchCode'],'create','realmA','Creates the approved client-bound authorization code.'),...branchSend(['branchCode','branchState'],'realmA','browser','Successful callback redirect for attempt A.')]),
  branchD('branch-consent-new','Attempt B · create a separate request','app','app','The second independent request has a new state and a new pending transaction.',[labP('state','consent-state-B',undefined,'branchState')],branchLocal(['branchState'],'create','app','Creates a fresh state for the independent denial example.')),
  branchD('branch-consent-request-B','Navigate with the second request','app','browser','Attempt B sends its own new state, code response type, exact callback and requested permissions.',[...branchPayload(['branchClientId','branchRedirectUri','branchScope','branchPrompt']),labP('response_type','code',undefined,'branchResponseType'),labP('state','consent-state-B',undefined,'branchState')],branchSend(['branchClientId','branchRedirectUri','branchResponseType','branchScope','branchPrompt','branchState'],'app','browser','Separate attempt B authorization URL.')),
  branchD('branch-consent-deliver-B','Deliver the second authorization request','browser','realmA','The provider receives the new request before asking for its decision.',[...branchPayload(['branchClientId','branchRedirectUri','branchScope','branchPrompt']),labP('response_type','code',undefined,'branchResponseType'),labP('state','consent-state-B',undefined,'branchState')],[...branchSend(['branchClientId','branchRedirectUri','branchResponseType','branchScope','branchPrompt','branchState'],'browser','realmA','Separate attempt B HTTPS authorization request.'),...branchLocal(['branchState'],'store','realmA','Binds consent-state-B to the second pending transaction.')]),
  branchD('branch-consent-page-B','Show the second consent request','realmA','browser','The already authenticated person reviews the second request’s permissions.',branchPayload(['branchClientId','branchScope']),branchSend(['branchClientId','branchScope'],'realmA','browser','Consent page for attempt B.')),
  branchD('branch-consent-deny','Attempt B · refuse the permissions','user','browser','The authenticated person refuses the second request through the provider’s UI.',[labP('Consent decision (local UI action)','deny',undefined,'branchConsent')],branchSend(['branchConsent'],'user','browser','Local denial action; no token is issued.')),
  branchD('branch-consent-submit-B','Submit the second request’s denial','browser','realmA','The provider receives the denial for its own pending second transaction.',[labP('Consent decision (local UI action)','deny',undefined,'branchConsent')],branchSend(['branchConsent'],'browser','realmA','Provider-specific consent form for attempt B.')),
  branchD('branch-consent-error','Return access_denied and the saved state','realmA','browser','The refusal returns an OAuth error, not a code or tokens.',[labP('error','access_denied',undefined,'branchError'),...branchPayload(['branchErrorDescription']),labP('state','consent-state-B',undefined,'branchState')],branchSend(['branchError','branchErrorDescription','branchState'],'realmA','browser','Error authorization redirect.')),
  branchD('branch-consent-callback','Deliver the denial callback','browser','app','The client receives the error callback from its registered redirect.',[labP('error','access_denied',undefined,'branchError'),labP('state','consent-state-B',undefined,'branchState')],branchSend(['branchError','branchState'],'browser','app','Callback parameters.')),
  branchD('branch-consent-check','Check state and stop the denied attempt','app','app','The client checks its saved correlation value and stops without redemption.',[labP('state','consent-state-B',undefined,'branchState'),labP('error','access_denied',undefined,'branchError')],branchLocal(['branchState','branchError'],'verify','app','Requires exact state match with consent-state-B; no code/token issuance follows attempt B.')),
]);
const branchLink=branchMake('lab-broker-account-link','First broker login · verify before linking','A matching email suggests an account; local verification authorizes the link.','Keycloak supported','Illustrates an explicit secure First Broker Login configuration requiring reauthentication of an existing local account. Automatic trusted-email linking is a different deliberate policy.',[
  branchD('branch-link-identity','The upstream returns its verified identity','realmB','realmA','The broker verifies the upstream signature and receives issuer, subject and contact claims.',branchPayload(['branchExternalIssuer','branchExternalSubject','branchEmail','branchEmailVerified']),branchSend(['branchExternalIssuer','branchExternalSubject','branchEmail','branchEmailVerified'],'realmB','realmA','Nested upstream identity result after the independent broker exchange.','upstream id_token')),
  branchD('branch-link-match','Find an existing local account candidate','realmA','realmA','The broker identifies a possible account but grants no login from email matching.',branchPayload(['branchLocalAccount','branchEmail']),[...branchLocal(['branchExternalIssuer','branchExternalSubject'],'verify','realmA','Checks trusted upstream identity.'),...branchLocal(['branchLocalAccount','branchEmail','branchEmailVerified'],'use','realmA','Looks up a candidate under explicit account-link policy.')],['Email matching alone does not prove local-account ownership.']),
  branchD('branch-link-prompt','Ask to verify the local account','realmA','browser','The provider asks the person to reauthenticate the intended existing account.',branchPayload(['branchLocalAccount']),branchSend(['branchLocalAccount'],'realmA','browser','Provider account-link verification page.')),
  branchD('branch-link-password','The person verifies the enrolled local account','user','browser','This configured example asks for the local account password.',branchPayload(['branchPassword']),branchSend(['branchPassword'],'user','browser','Provider-specific account-verification form.')),
  branchD('branch-link-form','Submit proof directly to Realm A','browser','realmA','The verification proof reaches the local provider, never the upstream issuer.',branchPayload(['branchPassword']),branchSend(['branchPassword'],'browser','realmA','Protected provider form.')),
  branchD('branch-link-verify','Verify local-account ownership','realmA','realmA','The local password verifier must succeed before the identity link changes.',branchPayload(['branchPasswordHash','branchLocalAccount']),[...branchLocal(['branchPasswordHash'],'use','realmA','Keeps the verifier local.'),...branchLocal(['branchPassword','branchLocalAccount'],'verify','realmA','Verifies the selected existing account and required account-link decision.')]),
  branchD('branch-link-store','Store the verified issuer/subject mapping','realmA','realmA','Only now does Realm A link the upstream identity to the local account.',branchPayload(['branchIdentityLink']),[...branchLocal(['branchExternalIssuer','branchExternalSubject','branchLocalAccount'],'use','realmA','Uses verified identity and authenticated local account.'),...branchLocal(['branchIdentityLink'],'create','realmA','Persists the explicit federated identity link.')]),
]);
const branchCancel=branchMake('lab-passkey-cancel','Passkey cancellation · configured fallback','A cancelled WebAuthn ceremony produces no assertion; a permitted alternative is a new verification.','Keycloak supported','The DOMException is a WebAuthn API outcome, not a Keycloak/OAuth token response. Password fallback must be explicitly permitted by the configured browser flow.',[
  branchD('branch-cancel-challenge','Create a fresh passkey ceremony','realmA','realmA','The relying party generates the challenge and selects its RP scope.',branchPayload(['branchChallengeLogin','branchRpId']),[...branchLocal(['branchChallengeLogin'],'create','realmA','Creates a fresh challenge.'),...branchLocal(['branchRpId'],'use','realmA','Uses the configured RP domain.')]),
  branchD('branch-cancel-get','Ask the browser for a credential','realmA','browser','The page calls navigator.credentials.get with this challenge and RP ID.',branchPayload(['branchChallengeLogin','branchRpId']),branchSend(['branchChallengeLogin','branchRpId'],'realmA','browser','WebAuthn request options.')),
  branchD('branch-cancel-local','The browser reports local cancellation','browser','browser','The ceremony ends with NotAllowedError and no signed assertion.',branchPayload(['branchNotAllowed']),branchLocal(['branchNotAllowed'],'create','browser','Rejects the local WebAuthn promise after cancellation; no assertion exists.'),['Nothing resembling a valid credential proof is sent to the server.']),
  branchD('branch-cancel-policy','Offer only a configured alternative','realmA','browser','This provider policy permits a separate password verification.',branchPayload(['branchFallback']),[...branchLocal(['branchFallback'],'use','realmA','Checks the configured alternative method.'),...branchSend(['branchFallback'],'realmA','browser','Provider UI choice, not WebAuthn success.')]),
  branchD('branch-cancel-input','The person chooses the alternative','user','browser','A new password proof is entered on the provider’s page.',branchPayload(['branchPassword']),branchSend(['branchPassword'],'user','browser','Explicit alternative-factor input.')),
  branchD('branch-cancel-password','Send the alternative proof to Realm A','browser','realmA','The provider receives the new factor; no passkey assertion was manufactured.',branchPayload(['branchPassword']),branchSend(['branchPassword'],'browser','realmA','Protected provider-specific password form.')),
  branchD('branch-cancel-verify','Verify the alternative independently','realmA','realmA','Only successful password verification can complete this configured login.',branchPayload(['branchPasswordHash','branchPassword']),[...branchLocal(['branchPasswordHash'],'use','realmA','Uses the protected local password verifier.'),...branchLocal(['branchPassword'],'verify','realmA','Verifies the alternative factor under configured policy.')]),
]);
const branchRecovery=branchMake('lab-account-recovery','Account recovery · one-use action credential','A reset request identifies an account; a protected reset credential authorizes the action.','Keycloak configured policy','This is Keycloak’s reset-credentials/action-token mechanism, not a new RFC OAuth grant. Account delivery verification, expiry, action type, subject and one-use checks are explicit.',[
  branchD('branch-recovery-request','Request a credential reset','user','realmA','Identifying an account does not authenticate the requester.',branchPayload(['branchUsername']),branchSend(['branchUsername'],'user','realmA','Provider reset-request UI abstraction.')),
  branchD('branch-recovery-create','Create a short-lived signed action','realmA','realmA','The provider binds the reset action to its account, type, expiry and unique ID.',branchPayload(['branchActionToken','branchSubject','branchActionType','branchExp','branchJti']),[...branchLocal(['branchSubject','branchActionType','branchExp','branchJti'],'create','realmA','Creates account-bound action claims.'),...branchLocal(['branchSigningKey'],'use','realmA','Signs the reset credential locally.'),...branchLocal(['branchActionToken'],'create','realmA','Serializes the protected action token.')]),
  branchD('branch-recovery-delivery','Deliver through the account’s verified channel','realmA','user','The intended account owner receives the protected reset link.',branchPayload(['branchActionToken']),branchSend(['branchActionToken'],'realmA','user','Verified account delivery abstraction; the OAuth application does not receive the reset secret.')),
  branchD('branch-recovery-open','Open the account action link','user','browser','The account owner presents the delivered action credential.',branchPayload(['branchActionToken']),branchSend(['branchActionToken'],'user','browser','Protected reset URL; avoid leaking the link.')),
  branchD('branch-recovery-return','Present the reset credential to Realm A','browser','realmA','The provider receives the signed account action credential.',branchPayload(['branchActionToken']),branchSend(['branchActionToken'],'browser','realmA','HTTPS action URL.')),
  branchD('branch-recovery-check','Validate trust, action, subject and one-use state','realmA','realmA','The reset handler checks signature, expiry, correct account/action and replay state.',branchPayload(['branchActionToken','branchSubject','branchActionType','branchExp','branchJti']),branchLocal(['branchActionToken','branchSubject','branchActionType','branchExp','branchJti'],'verify','realmA','Requires a valid configured action and rejects expired, altered or consumed credentials.'),['Account identification alone grants no reset authority.']),
  branchD('branch-recovery-password','Submit a replacement on the verified reset page','browser','realmA','The person chooses a new secret only after action verification.',branchPayload(['branchNewPassword']),branchSend(['branchNewPassword'],'browser','realmA','Provider password-reset form.')),
  branchD('branch-recovery-store','Update the verifier and consume the action','realmA','realmA','The provider enforces password policy, stores the new verifier and consumes the action ID.',branchPayload(['branchPasswordHash','branchJti']),[...branchLocal(['branchNewPassword'],'verify','realmA','Enforces configured password policy.'),...branchLocal(['branchPasswordHash'],'derive','realmA','Stores the replacement credential verifier locally.'),...branchLocal(['branchJti'],'store','realmA','Records the one-use action as consumed; a second presentation is rejected.')]),
]);
const branchSessions=branchMake('lab-concurrent-sessions','Concurrent sessions · server state and JWT lifetime','Session-count and expiry policy affect server state; local JWT checks have separate limits.','Keycloak configured policy','The configured User Session Count Limiter action can terminate an older session or deny a new one. This example terminates the older session; it does not promise immediate rejection by an offline JWT API.',[
  branchD('branch-sessions-existing','Read the existing browser session','browser','realmA','The provider receives a cookie that identifies an existing server-side session.',branchPayload(['branchCookie']),branchSend(['branchCookie'],'browser','realmA','HTTPS provider cookie; not an OAuth access token.')),
  branchD('branch-sessions-policy','Apply the configured session-count rule','realmA','realmA','A separately verified new login triggers the configured session-count action.',branchPayload(['branchSessionPolicy','branchSessionRecord']),[...branchLocal(['branchSessionPolicy','branchSessionRecord'],'use','realmA','Evaluates the configured policy after verifying the new authentication.')]),
  branchD('branch-sessions-revoke','Terminate the older server session','realmA','realmA','The illustrated policy revokes the older session record.',branchPayload(['branchSessionRecord']),branchLocal(['branchSessionRecord'],'store','realmA','Marks the old user/client session terminated under configured concurrency policy.')),
  branchD('branch-sessions-client','Prepare the registered client’s authentication','app','app','The backend reads its own registration and constructs valid client authentication.',branchPayload(['branchClientId','branchClientSecret','branchAuthorization']),[...branchLocal(['branchClientId','branchClientSecret'],'use','app','Reads the confidential client credentials from protected backend configuration.'),...branchLocal(['branchAuthorization'],'derive','app','Builds its authenticated Basic header independently from the old user-session credential.')]),
  branchD('branch-sessions-refresh','The old client attempts refresh','app','realmA','The registered backend authenticates and presents its session-bound refresh credential.',[labP('grant_type','refresh_token',undefined,'branchGrantType'),...branchPayload(['branchAuthorization','branchRefreshToken'])],[...branchSend(['branchAuthorization','branchGrantType','branchRefreshToken'],'app','realmA','Authenticated refresh attempt from the old session.'),...branchSend(['branchClientId','branchClientSecret'],'app','realmA','Encoded confidential client credentials within the Basic header.','Authorization: Basic'),...branchLocal(['branchAuthorization','branchClientId','branchClientSecret'],'verify','realmA','Authenticates the requesting client before evaluating the refresh token and revoked session.')]),
  branchD('branch-sessions-reject','Reject the session-dependent operation','realmA','app','The server returns invalid_grant for the revoked refresh session.',[labP('error','invalid_grant',undefined,'branchError')],[...branchLocal(['branchRefreshToken','branchSessionRecord'],'verify','realmA','Rejects the revoked session’s refresh operation.'),...branchSend(['branchError'],'realmA','app','OAuth token-endpoint error; no replacement tokens.')]),
  branchD('branch-sessions-jwt','A separate API checks an already issued JWT','realmB','realmB','Offline signature validation alone may still accept an unexpired JWT; a state-aware policy is separate.',branchPayload(['branchAccessToken','branchExp']),branchLocal(['branchAccessToken','branchExp'],'verify','realmB','Checks the token’s own signature/claims/lifetime. Immediate session revocation enforcement requires additional state/introspection policy.'),['Do not confuse server-session revocation with instant offline JWT invalidation.']),
],{hasPerson:false,protocol:'oauth',actorSpecs:{realmB:{name:'Protected API',role:'Resource server',plainRole:'Checks token trust, intended audience, permissions and configured session awareness.',art:'webapp'}}});
export const BRANCHLAB_SCENARIOS=[branchDirect,branchFrontFlow(false),branchFrontFlow(true),branchConsent,branchLink,branchCancel,branchRecovery,branchSessions];
