import { labAttribute, labP, labOp, labWire, labStep, labScenario } from './lab-common.js';

// Precise synthetic messages. Crypto is explained, never executed with real keys.
const protUrls = { oauth:'https://www.rfc-editor.org/rfc/rfc6749', pkce:'https://www.rfc-editor.org/rfc/rfc7636', jwt:'https://www.rfc-editor.org/rfc/rfc7523.html', mtls:'https://www.rfc-editor.org/rfc/rfc8705.html', par:'https://www.rfc-editor.org/rfc/rfc9126.html', jar:'https://www.rfc-editor.org/rfc/rfc9101.html', jarm:'https://openid.net/specs/oauth-v2-jarm.html', dpop:'https://www.rfc-editor.org/rfc/rfc9449.html', admin:'https://www.keycloak.org/docs/latest/server_admin/index.html', features:'https://www.keycloak.org/server/features', kcJwt:'https://www.keycloak.org/securing-apps/jwt-authorization-grant', kcDpop:'https://www.keycloak.org/securing-apps/dpop', upgrading:'https://www.keycloak.org/docs/latest/upgrading/index.html' };
const protIssuer='https://idp1.example.test/realms/realm-a';
const protTokenUrl=protIssuer+'/protocol/openid-connect/token';
const protAuthUrl=protIssuer+'/protocol/openid-connect/auth';
const protParUrl=protIssuer+'/protocol/openid-connect/ext/par/request';
const protApiUrl='https://orders.example.test/orders';
const protClient='protected-web-app';
const protCallback='https://app.example.test/oauth/callback';
const protPublicCert='X.509 client certificate (public, synthetic)';
const protState='st_protected_attempt_91';
const protCode='code_one_time_63';
const protHandle='urn:ietf:params:oauth:request_uri:random_handle_14';
const protSignedRequest='header.request_claims.signature (schematic signed Request Object)';
const protSignedResponse='header.authorization_response_claims.signature (schematic JARM)';

export const PROTLAB_ATTRIBUTES = {};
const protDefine=(id,name,meaning,origin,purpose,example,standard,source)=>{PROTLAB_ATTRIBUTES[id]=labAttribute(name,meaning,origin,purpose,example,standard,source);};
const protBaseDefs=[
 ['protClientId','client_id','The registered identifier of this protected backend client.','Configured during Realm A client registration.','Selects client policy; inside a client assertion it is the subject. An identifier alone does not authenticate a client.',protClient,'RFC 6749 §2.2',protUrls.oauth],
 ['protClientSecret','client_secret','A configured confidential backend credential.','Provisioned for the backend and the realm.','Used only in the examples choosing HTTP Basic. It is encoded within Basic over TLS and never sent to the browser.','Configured synthetic client secret','RFC 6749 §2.3.1',protUrls.oauth],
 ['protBasic','Authorization','HTTP Basic client authentication.','The backend encodes its client identifier and secret.','Authenticates the PAR/token caller over HTTPS. Basic encoding itself is not encryption.','Basic BASE64(encoded client_id:encoded client_secret)','RFC 6749 §2.3.1',protUrls.oauth],
 ['protScope','scope','The requested/effective authorization scope set.','Chosen by the client and resolved by realm policy.','Requests configured API authorization; it does not itself prove user authentication.','orders.read','RFC 6749 §3.3',protUrls.oauth],
 ['protTokenEndpoint','token_endpoint','The configured HTTPS token endpoint.','Published by Realm A discovery metadata.','Receives an authenticated grant request; the selected client-assertion audience is explicitly configured separately.',protTokenUrl,'OIDC Discovery §3', 'https://openid.net/specs/openid-connect-discovery-1_0.html'],
 ['protServiceGrant','grant_type','Requests a token for the client’s service account.','Set by the backend for a machine grant.','client_credentials is the grant; private_key_jwt, mTLS and DPoP are separate authentication/protection choices.','client_credentials','RFC 6749 §4.4',protUrls.oauth],
 ['protCodeGrant','grant_type','Requests authorization-code redemption.','Set by the backend after validating its browser callback.','Selects the code grant; PAR/JAR/JARM protect other messages in that grant.','authorization_code','RFC 6749 §4.1.3',protUrls.oauth],
 ['protAccessToken','access_token','The newly issued API authorization token.','Created and signed by Realm A after grant validation.','Retained by the backend for an API; sender constraints additionally require possession of the configured key/certificate.','Signed API access token (schematic)','RFC 6749 §5.1',protUrls.oauth],
 ['protTokenType','token_type','The token’s usage scheme.','Returned by the issuing token endpoint.','Bearer is used with the illustrated mTLS-bound token; DPoP is used with the DPoP-bound token. It is distinct from a grant type.','Bearer / DPoP according to scenario','RFC 6749 §5.1 / RFC 9449 §5',protUrls.dpop],
 ['protExpiresIn','expires_in','The returned token lifetime in seconds.','Set by Realm A at token issuance.','Helps the client manage the token lifetime; this is separate from PAR handle/JWT proof lifetimes.','300 (illustrative)','RFC 6749 §5.1',protUrls.oauth],
 ['protRealmSigningKey','issuer signing private key (local)','Realm A’s protected key for signing tokens or JARM.','Provisioned and retained by Realm A.','Signs the issuer’s statement locally. It is separate from client assertion keys, TLS keys and DPoP keys.','Realm A private signing key; never transmitted','Keycloak realm keys / JWS',protUrls.admin],
 ['protRealmPublicKey','issuer signing public key (trusted)','The trusted public key for Realm A JWT verification.','Provisioned from trusted Realm A metadata/JWKS.','Verifies issuer signatures; a parsed issuer or untrusted key hint does not establish trust.','Trusted Realm A signing public key','JWS / Keycloak realm keys',protUrls.admin],
 ['protApiAudience','aud','The intended API audience inside an access token.','Resolved by Realm A’s configured audience/role mappings.','The resource checks that the token is intended for orders-api before accepting it.','orders-api','RFC 7519 §4.1.3','https://www.rfc-editor.org/rfc/rfc7519'],
 ['protClientPrivateKey','client signing private key (local)','The backend’s asymmetric signing key.','Provisioned and retained by the backend.','Signs client assertions or Request Objects locally. Its public key is registered with Realm A; the private key never crosses a link.','Protected client signing private key','RFC 7523 / RFC 9101',protUrls.jwt],
 ['protClientPublicKey','client signing public key (registered)','The client’s trusted signature-verification key.','Registered through a certificate/public key or configured client JWKS URL.','Realm A verifies client assertions and signed Request Objects under an allowed algorithm.','Registered client public key; alg RS256 in this example','Keycloak Signed JWT credentials',protUrls.admin],
 ['protCaType','client_assertion_type','Identifies a JWT used for client authentication.','Set by the requesting backend.','Selects the client-authentication assertion format, independently of grant_type.','urn:ietf:params:oauth:client-assertion-type:jwt-bearer','RFC 7523 §2.2',protUrls.jwt],
 ['protCaJwt','client_assertion','The signed JWT authenticating the OAuth client.','The backend signs its fresh client assertion.','Proves control of the registered client signing key; this assertion does not assert a person’s identity.','header.client_auth_claims.signature (schematic)','RFC 7523 §2.2',protUrls.jwt],
 ['protCaIss','iss','The issuer of this client-authentication JWT.','The backend sets its registered client identifier.','Matches the configured assertion issuer/client identity in this private_key_jwt profile.',protClient,'OIDC Core §9 / RFC 7523 §3',protUrls.jwt],
 ['protCaSub','sub','The client being authenticated by the JWT.','Set by the backend to its client_id.','The realm checks this identifies the registered requesting client; it is not a user subject.',protClient,'RFC 7523 §3',protUrls.jwt],
 ['protCaAud','aud','The single configured recipient of the client assertion.','Set to Realm A’s issuer URL in this example.','Current Keycloak accepts its issuer or the appropriate endpoint URL and defaults to one audience. The exact accepted string is agreed in configuration.',protIssuer,'RFC 7523 §3 / Keycloak current audience policy',protUrls.upgrading],
 ['protCaExp','exp','The client assertion expiry.','The backend sets a short NumericDate lifetime.','The realm rejects expired assertions and enforces its maximum lifetime.','Current time + 60 seconds (illustrative)','RFC 7523 §3',protUrls.jwt],
 ['protCaIat','iat','The client assertion creation time.','The backend sets the current NumericDate.','Supports freshness policy; included by this profile rather than claimed universally mandatory by RFC 7523.','Current Unix-epoch seconds','RFC 7523 §3',protUrls.jwt],
 ['protCaJti','jti','The unique identifier of this client assertion.','Freshly generated by the backend for one request.','The realm’s replay policy rejects reuse and retains the identifier through the assertion validity window. RFC 7523 permits this claim; the lab explicitly uses it.','client_jwt_unique_12','RFC 7523 §3',protUrls.jwt],
 ['protCaReplay','assertion replay cache (local)','The realm’s record of used client-assertion identifiers.','Maintained locally by the configured client-authentication replay policy.','Rejects reuse of a previously accepted jti while the assertion could be valid. It is not an HTTP field.','Used jti retained until expiry','RFC 7523 §3 / Keycloak Signed JWT',protUrls.jwt],
 ['protTlsCertificate','TLS client certificate','The public X.509 certificate presented by the backend.','Issued by a trusted CA and configured in the backend.','Presented during TLS; client authentication checks CA chain and registered certificate identity. The private key is not contained in the transmitted certificate.',protPublicCert,'RFC 8705 §2',protUrls.mtls],
 ['protTlsPrivateKey','TLS client private key (local)','The protected key corresponding to the client certificate.','Provisioned and retained by the backend.','Signs TLS handshake proof locally and never goes to the realm or API.','Client TLS private key; never transmitted','RFC 8705 §2 / TLS',protUrls.mtls],
 ['protTlsProof','CertificateVerify','The TLS handshake signature proving client-key possession.','Created by the backend’s TLS implementation with its local private key.','The realm/API TLS verifier checks this proof; this is TLS evidence, not an OAuth JSON/form parameter.','TLS client CertificateVerify signature (schematic)','TLS 1.3 §4.4.3 / RFC 8705','https://www.rfc-editor.org/rfc/rfc8446'],
 ['protTlsAuthMethod','token_endpoint_auth_method','The client’s registered mutual-TLS authentication method.','Configured as PKI mutual-TLS client authentication.','tls_client_auth authenticates the registered confidential client. It is distinct from enabling certificate-bound tokens.','tls_client_auth','RFC 8705 §2.1',protUrls.mtls],
 ['protTlsBoundSetting','tls_client_certificate_bound_access_tokens','The metadata/configuration requiring certificate-bound access tokens.','Enabled for this client separately from client authentication.','Requests tokens bound to the certificate used at issuance. API enforcement of the binding must also be implemented.','true','RFC 8705 §3.3 / Keycloak certificate-bound access tokens',protUrls.mtls],
 ['protCertThumbprint','cnf.x5t#S256','The certificate thumbprint in the access token’s confirmation claim.','Realm A computes BASE64URL(SHA256(DER(whole X.509 client certificate))), without padding.','The API compares it with the current TLS client certificate. This is a certificate hash, not a public-key hash or JWK thumbprint.','BASE64URL(SHA256(DER(client certificate)))','RFC 8705 §3.1',protUrls.mtls],
 ['protBearerHeader','Authorization','The HTTP access-token presentation header.','The backend supplies its issued token during an API request.','Bearer is still the scheme for this mTLS-bound token; TLS certificate possession must be checked in addition.','Bearer <certificate-bound access_token>','RFC 6750 / RFC 8705 §3',protUrls.mtls],
 ['protRedirect','redirect_uri','The registered HTTPS callback for the backend.','Configured identically in the client and realm registration.','Receives the code or JARM authorization response through the browser. It is repeated consistently at code redemption.',protCallback,'RFC 6749 §4.1',protUrls.oauth],
 ['protResponseType','response_type','Selects an authorization code.','Set by the backend before directing the browser.','PAR/JAR protect this request; JARM protects the response. All still use the code grant.','code','RFC 6749 §4.1.1',protUrls.oauth],
 ['protState','state','The random correlation value for this browser authorization attempt.','Generated and retained by the backend.','Returned unchanged and compared before accepting the callback; signed JARM does not remove this correlation check.',protState,'RFC 6749 §4.1.1 / §10.12',protUrls.oauth],
 ['protVerifier','code_verifier','The one-time secret for PKCE code redemption.','Generated and retained by the backend before authorization.','Only its S256 commitment reaches the browser; the verifier is sent directly to the token endpoint later.','Random verifier retained only in the backend until redemption','RFC 7636 §4.1',protUrls.pkce],
 ['protChallenge','code_challenge','The public commitment derived from code_verifier.','The backend computes BASE64URL(SHA256(ASCII(code_verifier))), without padding.','Bound to the request/code so the realm can verify the eventual secret.','S256 commitment of the locally retained verifier','RFC 7636 §4.2',protUrls.pkce],
 ['protChallengeMethod','code_challenge_method','The selected PKCE derivation method.','Configured by the backend as S256.','The realm uses this method to check the redeemed code_verifier.','S256','RFC 7636 §4.2',protUrls.pkce],
 ['protCode','code','The short-lived, single-use authorization code.','Created by Realm A after its configured user authentication/approval succeeds.','Bound to this client, redirect and PKCE commitment; the backend redeems it directly. It is not an access token.',protCode,'RFC 6749 §4.1.2',protUrls.oauth],
 ['protApproval','User authentication / approval (local operation)','The person’s interaction with the configured realm login page.','The browser presents Realm A’s configured authentication/consent process.','This compact protection lab assumes that process succeeds; the main sign-in scenarios separately animate password, TOTP and passkey factors.','Successful configured realm login/approval','Keycloak browser authentication flow',protUrls.admin],
 ['protParEndpoint','pushed_authorization_request_endpoint','The HTTPS endpoint accepting pushed authorization parameters.','Published in the authorization server metadata.','Receives an authenticated POST before the browser is redirected. A returned request_uri is a reference, not an authorization code.',protParUrl,'RFC 9126 §2 / §5',protUrls.par],
 ['protRequestUri','request_uri','The short-lived reference to the stored pushed authorization request.','Generated unpredictably by Realm A after authenticating and validating the PAR request.','Bound to the authenticated client and expiry. The client uses it once; the server normally enforces one-time use, with RFC allowances for browser refresh.',protHandle,'RFC 9126 §2.2 / §4',protUrls.par],
 ['protParExpiresIn','expires_in','The lifetime of this PAR reference in seconds.','Set by Realm A when returning the pushed-request handle.','An expired handle is rejected; this lifetime is different from the eventual token lifetime.','60 (illustrative)','RFC 9126 §2.2',protUrls.par],
 ['protParStoredRequest','pushed request / client binding (local)','The realm’s stored authorization parameters and authenticated client association.','Stored after validating PAR authentication, redirect, scopes, state and PKCE.','Later resolves the browser’s handle to the exact validated request. The browser carries the handle instead of resending all parameters.','Stored request bound to protected-web-app; expiry and used marker','RFC 9126 §2 / §4',protUrls.par],
 ['protRequestObject','request','The signed JWT Request Object carried in an authorization request.','The backend signs the complete authorization request using its registered signing key.','Protects request integrity. The realm uses inner parameters only and requires outer/inner client_id consistency. This is not client_assertion. Signature alone does not encrypt its contents.',protSignedRequest,'RFC 9101 §4-§6',protUrls.jar],
 ['protRoIss','iss','The issuer of this signed Request Object.','Set by the client to its registered client_id.','Identifies the client signing the request under the selected request-object profile.',protClient,'RFC 9101 §4 / OIDC Request Object',protUrls.jar],
 ['protRoAud','aud','The Request Object’s intended authorization server.','Set by the backend to Realm A’s issuer identifier.','The selected profile checks the signed request is intended for this server.',protIssuer,'RFC 9101 §4 / §10',protUrls.jar],
 ['protRoExp','exp','The expiry of this signed Request Object.','Set by the backend to a short NumericDate lifetime.','Limits the acceptable request-object freshness window under the configured profile.','Current time + 60 seconds (illustrative)','RFC 9101 §4 / §10',protUrls.jar],
 ['protRoJti','jti','The optional unique identifier of this Request Object.','Generated by the backend for this authorization request.','Provides request correlation. RFC 9101 does not make it mandatory in every deployment, and this lab does not claim stock Keycloak caches jti for one-use enforcement. State, PKCE and freshness checks retain their own purpose.','request_object_unique_22','RFC 9101 §4 / JWT §4.1.7',protUrls.jar],
 ['protRoReplay','Request Object freshness policy (local)','The selected realm signature/audience/time policy for this signed request.','Configured on the authorization server and evaluated locally.','Checks the Request Object’s allowed signature, intended audience and short expiry. Optional jti is used for correlation; a custom one-use replay cache would be a separate extension, not a stock Keycloak capability claimed here.','Selected signature/audience/short-expiry policy; optional nbf check disabled in this example','RFC 9101 security considerations / Keycloak secure-request-object client policy',protUrls.jar],
 ['protResponseMode','response_mode','Requests a JWT-secured authorization response transport.','Set by the client to query.jwt in this lab.','The callback query carries response=<signed JWT>; code and state are claims inside it. Other standard modes are form_post.jwt, fragment.jwt and jwt.','query.jwt','JARM §2.3',protUrls.jarm],
 ['protJarmResponse','response','The signed JWT containing the authorization response.','Created and signed by Realm A after successful authorization.','The client validates it completely before processing code. This is an authorization response JWT, not an OIDC ID token.',protSignedResponse,'JARM §2.1-§2.4',protUrls.jarm],
 ['protJarmIss','iss','The issuer of the JWT authorization response.','Written by Realm A in JARM.','Must match the expected issuer retained with the original browser attempt.',protIssuer,'JARM §2.1 / §2.4',protUrls.jarm],
 ['protJarmAud','aud','The intended client of the JWT authorization response.','Set by Realm A to the requesting client_id.','The backend checks that the response is addressed to this client.',protClient,'JARM §2.1 / §2.4',protUrls.jarm],
 ['protJarmExp','exp','The validity limit of the JWT authorization response.','Set by Realm A to a short NumericDate lifetime.','The backend rejects expired responses before processing the contained code.','Current time + 60 seconds (illustrative)','JARM §2.1 / §2.4',protUrls.jarm],
 ['protJarmAlg','alg','The signature algorithm for JARM.','Configured for this client and used by Realm A.','The backend checks the configured allowlist and verifies the expected issuer’s signature; alg=none is forbidden.','RS256 (illustrative configured policy)','JARM §2.2 / §2.4',protUrls.jarm],
 ['protJarmPending','pending authorization attempt (local)','The original client-side request context and consumed marker.','Retained locally with expected issuer, client, state and PKCE verifier.','Validates response binding and prevents accepting the same pending attempt repeatedly; JARM integrity does not replace this state check.','Expected issuer/client/state; pending or consumed','JARM §2.4 / RFC 6749 §10.12',protUrls.jarm],
];
for(const row of protBaseDefs)protDefine(...row);

const protDpopDefs=[
 ['protDpopPrivate','DPoP signing private key (local)','The key protecting this sender-constrained token.','Generated and retained by the backend.','Signs fresh DPoP proofs. It never leaves the client and is different from client-authentication and realm signing keys.','Client-local protected asymmetric key','RFC 9449 §4',protUrls.dpop],
 ['protDpopJwk','jwk','The public key in the DPoP proof’s protected JWT header.','Derived from the client’s DPoP key pair.','The server verifies the proof signature and compares its RFC 7638 thumbprint with the token’s cnf.jkt. The header must not contain private key material.','Public EC P-256 JWK {kty,crv,x,y}; no d','RFC 9449 §4.2',protUrls.dpop],
 ['protDpopTyp','typ','The DPoP proof JWT type.','Set by the proof creator in the protected header.','Distinguishes this request proof from other JWT types.','dpop+jwt','RFC 9449 §4.2',protUrls.dpop],
 ['protDpopAlg','alg','The asymmetric DPoP signature algorithm.','Selected from an allowed supported algorithm list.','The server verifies the signature under that public key; none and symmetric MAC algorithms are forbidden.','ES256 (illustrative)','RFC 9449 §4.2-§4.3',protUrls.dpop],
 ['protDpopJti','jti','The unique identifier of each individual HTTP-request proof.','Freshly generated by the client for each token/API attempt, including retries.','The server rejects recent replay in its validation window; reusing a JWT from another request is not permitted.','Fresh distinct jti per request','RFC 9449 §4.2-§4.3',protUrls.dpop],
 ['protDpopHtm','htm','The HTTP method bound into the signed proof.','Taken from the actual request by the client.','The receiver checks the proof matches POST for token requests or GET for this API request.','POST token request / GET API request','RFC 9449 §4.2',protUrls.dpop],
 ['protDpopHtu','htu','The target URI bound into the signed proof.','Taken from the actual request URI without query or fragment.','The receiver checks the actual target after permitted URI normalization. A proof for the token endpoint cannot authorize this API URI.',protTokenUrl+' or '+protApiUrl+'; query/fragment excluded','RFC 9449 §4.2-§4.3',protUrls.dpop],
 ['protDpopIat','iat','The proof creation time.','Set by the client as the current NumericDate.','The receiver checks its permitted freshness window, separately from access-token expiry.','Current Unix-epoch seconds','RFC 9449 §4.2-§4.3',protUrls.dpop],
 ['protDpopTokenProof','DPoP','The HTTP header carrying a signed proof for a token request.','The client signs typ/alg/jwk plus fresh jti, htm=POST, token htu and iat.','Proves possession of the key to which the result token is bound. This token request proof has no ath because it is not presenting an access token to a resource.','header.token_request_proof.signature (schematic)','RFC 9449 §4-§5',protUrls.dpop],
 ['protDpopApiProof','DPoP','The header carrying a fresh proof for this protected-resource request.','The client signs a new proof for API method/URI and the presented token hash.','Includes ath and any server-required nonce, in addition to the common proof members. It is different from the token-request proof.','header.api_request_proof.signature (schematic)','RFC 9449 §7',protUrls.dpop],
 ['protDpopJkt','cnf.jkt','The access token’s DPoP public-key thumbprint.','The issuer computes the RFC 7638 JWK thumbprint: canonical required public JWK members, SHA-256, base64url without padding.','The resource compares it with the current proof key. This is not an X.509 certificate thumbprint.','BASE64URL(SHA256(canonical public JWK required members))','RFC 9449 §6 / RFC 7638',protUrls.dpop],
 ['protDpopAth','ath','The hash of the access token presented at the API.','The client computes BASE64URL(SHA256(ASCII(access_token))), without padding.','The API recomputes the hash of the received token and compares it to this signed claim. It is absent from the illustrated token-endpoint proof.','BASE64URL(SHA256(ASCII(access_token)))','RFC 9449 §4.2 / §7',protUrls.dpop],
 ['protDpopAuthorization','Authorization','The HTTP header presenting the DPoP-bound access token.','Constructed by the backend after receiving token_type=DPoP.','Uses the DPoP scheme together with a separate DPoP proof header; a plain Bearer presentation is not sufficient.','DPoP <bound access_token>','RFC 9449 §7.1',protUrls.dpop],
 ['protDpopNonceHeader','DPoP-Nonce','The resource server’s nonce challenge header.','Generated unpredictably by the API when its chosen proof policy requires a nonce.','The client retains this server-specific nonce and signs it in a fresh retry proof. Authorization-server nonce challenges are a separate context.','api_nonce_random_32','RFC 9449 §8-§9',protUrls.dpop],
 ['protDpopNonce','nonce','The server-provided value inside the retry proof.','Copied by the client from the API’s DPoP-Nonce header.','The API checks it against its valid nonce policy. This is a DPoP freshness challenge, not an OIDC ID-token nonce.','api_nonce_random_32','RFC 9449 §9',protUrls.dpop],
 ['protDpopChallenge','WWW-Authenticate','The resource’s authentication challenge.','Returned by the API with HTTP 401 under its nonce policy.','Signals use_dpop_nonce for the DPoP scheme. At a token endpoint the standard challenge would instead be HTTP 400 JSON error plus DPoP-Nonce.','DPoP error="use_dpop_nonce"','RFC 9449 §9',protUrls.dpop],
 ['protDpopReplay','DPoP freshness / replay record (local)','The receiver’s window of recent request proofs and valid nonce state.','Maintained independently by Realm A and the resource server.','Rejects replay or stale proofs; token validity and proof validity are checked separately.','Recent key/jti + time window + resource nonce policy','RFC 9449 §4.3 / §8-§9',protUrls.dpop],
];
for(const row of protDpopDefs)protDefine(...row);
const protGrantDefs=[
 ['protJwtGrant','grant_type','Selects the JWT bearer authorization grant.','Set by the confidential backend.','Uses assertion as the authorization grant; it is different from client_assertion used to authenticate the calling client.','urn:ietf:params:oauth:grant-type:jwt-bearer','RFC 7523 §2.1',protUrls.jwt],
 ['protGrantAssertion','assertion','A signed JWT representing a subject under an external trust relationship.','Issued by the trusted external IdP for Realm A; the source identity was verified earlier.','Realm A validates external issuer/subject/audience/time/signature and maps a previously linked subject. Client authentication is separately required by Keycloak.','header.external_subject_assertion.signature (schematic)','RFC 7523 §2.1 / Keycloak JWT grant',protUrls.kcJwt],
 ['protGrantIss','iss','The issuer of the authorization-grant assertion.','Set by the trusted external IdP.','Selects Realm A’s configured trusted IdP, which must be allowed for this client.','https://login.partner.example.test','RFC 7523 §3',protUrls.jwt],
 ['protGrantSub','sub','The external subject identifier represented by the assertion.','Assigned by the external IdP to the previously verified user.','Keycloak resolves this through the user’s existing IdP link; it is not the requesting client identifier.','external-user-913','RFC 7523 §3 / Keycloak JWT grant',protUrls.kcJwt],
 ['protGrantAud','aud','The single configured Realm A recipient of the subject assertion.','Set by the external IdP to Realm A’s issuer in this example.','Current Keycloak accepts issuer or token URL and requires a single audience for this ordinary profile. Custom provider-specific audiences are separate configuration variants.',protIssuer,'RFC 7523 §3 / Keycloak audience policy',protUrls.kcJwt],
 ['protGrantExp','exp','The authorization-grant assertion expiry.','Set by the trusted IdP under the agreed short-lived profile.','Keycloak rejects expired assertions and enforces the configured maximum assertion expiration.','Current time + 60 seconds (illustrative)','RFC 7523 §3',protUrls.jwt],
 ['protGrantIat','iat','The subject assertion creation time.','Set by the trusted IdP.','Included for this profile’s freshness policy and validated according to allowed clock skew.','Current Unix-epoch seconds','RFC 7523 §3',protUrls.jwt],
 ['protGrantJti','jti','The unique identifier of this subject assertion.','Freshly generated by the external IdP.','Current Keycloak requires one-time assertion identifiers by default when assertion reuse is disabled. RFC 7523 itself makes jti optional.','external_assertion_unique_41','RFC 7523 §3 / Keycloak one-time assertions',protUrls.kcJwt],
 ['protGrantPrivate','external issuer private key (local)','The trusted IdP’s assertion signing key.','Retained and protected by the external issuer.','Signs the subject assertion locally; it never crosses a link or becomes the backend’s client-authentication key.','External IdP private signing key; never transmitted','RFC 7523 §3',protUrls.jwt],
 ['protGrantPublic','trusted external issuer public key','The verification key configured for Realm A’s IdP trust.','Provisioned manually or fetched through the specifically trusted IdP JWKS configuration.','Realm A verifies the grant assertion with this key and the permitted signature algorithm. Arbitrary incoming key URLs are not trusted.','Configured external issuer public key','Keycloak JWT Authorization Grant',protUrls.kcJwt],
 ['protGrantPolicy','JWT Authorization Grant / allowed IdP settings (local)','The realm/client settings enabling this particular trust relationship.','Configured on the confidential client and the trusted IdP.','The client capability, allowed provider and IdP grant switch must all permit the request.','Confidential client + enabled grant + permitted IdP','Keycloak JWT Authorization Grant',protUrls.kcJwt],
 ['protGrantLink','previously linked external subject (local)','The existing binding between the external subject and a local Realm A user.','Created by prior account-linking administration or a completed broker flow.','Required by this current Keycloak grant; the grant does not invent a new user or automatically link an arbitrary assertion subject.','external-user-913 → user-in-A-204','Keycloak JWT Authorization Grant',protUrls.kcJwt],
 ['protGrantReplay','subject assertion replay record (local)','The realm’s one-time subject-assertion record.','Maintained locally while the assertion can be valid.','Rejects reused jti with default assertion reuse disabled. This is independent of any client-assertion replay record.','Used external assertion jti until expiration','Keycloak JWT Authorization Grant',protUrls.kcJwt],
 ['protTransientSession','transient user session (local)','Keycloak’s temporary context for the validated JWT grant.','Created after the linked subject and assertion are accepted.','Supports the resulting token; current Keycloak JWT authorization grant creates a transient session and does not issue a refresh token.','Transient session; no refresh token','Keycloak JWT Authorization Grant',protUrls.kcJwt],
];
for(const row of protGrantDefs)protDefine(...row);

export const PROTLAB_SOURCES=[
 {name:'JWT client authentication and authorization grants',standard:'RFC 7523',url:protUrls.jwt,note:'client_assertion authenticates a client; assertion can carry an independent authorization grant.'},
 {name:'Mutual TLS and certificate-bound tokens',standard:'RFC 8705',url:protUrls.mtls,note:'TLS client authentication and token certificate binding are distinct protections.'},
 {name:'Pushed Authorization Requests',standard:'RFC 9126',url:protUrls.par,note:'Authenticated server-stored authorization request and expiring client-bound request_uri.'},
 {name:'JWT-Secured Authorization Requests',standard:'RFC 9101',url:protUrls.jar,note:'Signed Request Objects, registered client keys and inner/outer client identity consistency.'},
 {name:'JWT Secured Authorization Response Mode',standard:'JARM final specification',url:protUrls.jarm,note:'Signed response JWT validation must finish before code is processed; response is not an ID token.'},
 {name:'DPoP',standard:'RFC 9449',url:protUrls.dpop,note:'Per-request proof, public JWK thumbprint, resource token hash and independent nonce challenges.'},
 {name:'Keycloak protection configuration',standard:'Keycloak official administration guide',url:protUrls.admin,note:'Signed JWT credentials, Request Object/JARM algorithms and certificate-bound tokens.'},
 {name:'Current supported features',standard:'Keycloak official feature catalog',url:protUrls.features,note:'DPoP, PAR and JWT authorization grant are supported and enabled by default in the current catalog.'},
 {name:'Keycloak DPoP guide',standard:'Keycloak official guide',url:protUrls.kcDpop,note:'Client token binding and resource-server proof enforcement.'},
 {name:'Keycloak JWT Authorization Grant guide',standard:'Keycloak official guide',url:protUrls.kcJwt,note:'Confidential client, permitted IdP, linked subject, single audience, default one-time assertion and transient session.'},
 {name:'Current client assertion audience policy',standard:'Keycloak official upgrading guide',url:protUrls.upgrading,note:'Current audience defaults require a single configured issuer/appropriate endpoint recipient.'},
];

const protOps=(ids,kind,actor,detail,carriedAs)=>labOp(ids,kind,actor,detail,carriedAs);
const protPayload=(id,value,description)=>labP(PROTLAB_ATTRIBUTES[id].name,value??PROTLAB_ATTRIBUTES[id].example,description,id);
const protStep=(id,title,from,to,summary,detail,ops,payload=[],checks=[],channel)=>labStep(id,title,from,to,from===to?'prepare':'tokens',channel||(from===to?'internal':from==='browser'||to==='browser'?'https':'backchannel'),summary,detail,[...new Set(ops.map(operation=>operation.attributeId))],payload,checks,ops);
const protLocal=(id,title,actor,summary,detail,ops,payload=[],checks=[])=>protStep(id,title,actor,actor,summary,detail,ops,payload,checks,'internal');
const protWire=(id,title,from,to,summary,detail,ids,payload=[],nested=[],checks=[],channel)=>protStep(id,title,from,to,summary,detail,[...labWire(ids,from,to,'Actual message member carried in this exchange.'),...nested],payload,checks,channel);
const protPick=steps=>Object.fromEntries([...new Set(steps.flatMap(step=>step.fields))].map(id=>[id,PROTLAB_ATTRIBUTES[id]]));
const protBackend={name:'Protected web backend',role:'Confidential OAuth client',plainRole:'Prepares protected requests and retains its credentials and API tokens.',notes:['Synthetic teaching values; no live OAuth server or real secrets.','Private keys stay local. Protocol protections do not replace configured authorization policy.']};
const protRealm={name:'IdP 1 · Realm A',role:'OAuth authorization server',plainRole:'Checks the client, request and grant before issuing a token.',notes:['Uses independently configured trust for client signing keys, issuer keys and certificate identity.']};
const protApi={name:'Orders API',role:'OAuth resource server',plainRole:'Checks the token and required possession proof before returning data.',art:'app',notes:['API authorization and sender-constraint enforcement are application responsibilities.']};
const protBrowser={name:'Web browser',role:'User-agent',plainRole:'Visits the realm and delivers the browser authorization response.',notes:['Never receives the PKCE verifier, client secret or client private signing key in these flows.']};
const protPerson={name:'Person',role:'Existing user',plainRole:'Completes the realm’s configured login and approval.',notes:['Factors are summarized here; password, TOTP and passkey ceremonies are shown separately in the main scenarios.']};
const protMeta=(id,title,summary,source,hasPerson=false,supportNote='Supported in current Keycloak when the corresponding client/server settings are configured.')=>({id,title,summary,category:'Request, client and token protection',status:'Keycloak supported',supportNote,source,architecture:'web',protocol:'oauth',hasPerson});
const protMakeScenario=(meta,steps,actors)=>labScenario(meta,protPick(steps),steps,actors);
const protBasicIds=['protBasic','protClientId','protClientSecret'];
const protBasicWire=(from,to)=>labWire(protBasicIds,from,to,'Client identifier and secret are encoded within the HTTP Basic header over TLS, not repeated as separate form fields.','Authorization: Basic');
const protApiIssue=(id,binding=[])=>protLocal(id,'Issue an API token','realmA','Realm A signs the authorized token and prepares its response metadata.','The successful grant resolves subject/scopes and the configured orders-api audience. Realm A uses its local private signing key; token claims and any sender-constraint confirmation are inside the JWT. This API token is not used to establish a new browser identity.',[...protOps(['protScope','protRealmSigningKey',...binding],'use','realmA','Uses permitted authorization and the protected local signing key.'),...protOps(['protAccessToken','protApiAudience','protTokenType','protExpiresIn'],'create','realmA','Creates the signed access token and response metadata.')],[protPayload('protAccessToken'),protPayload('protApiAudience')]);
const protTokenResponse=(id,type='Bearer',binding=[])=>protWire(id,'Return the API access token','realmA','app','The backend receives the token and its usage scheme over HTTPS.','The JSON token response carries access_token, token_type, expires_in and scope. Any aud/cnf members are claims inside access_token, not extra top-level response fields. This compact lab does not request a refresh token.',['protAccessToken','protTokenType','protExpiresIn','protScope'],[protPayload('protAccessToken'),protPayload('protTokenType',type),protPayload('protExpiresIn'),protPayload('protScope')],labWire(['protApiAudience',...binding],'realmA','app','Nested access-token claim, not a top-level token response parameter.','access_token → signed JWT'));

const protCaClaims=['protCaIss','protCaSub','protCaAud','protCaExp','protCaIat','protCaJti'];
const protClientJwtSteps=[
 protLocal('prot-client-jwt-sign','Sign a fresh client authentication JWT','app','The backend authenticates with its signing key instead of a shared secret.','The registered private_key_jwt profile sets iss=sub=client_id, a single configured aud equal to Realm A’s issuer, short exp, current iat and fresh jti. RFC 7523 permits the token endpoint as audience; current Keycloak accepts an agreed issuer/appropriate endpoint string. The private signing key stays in the backend. The separate client_credentials grant authorizes its service account.',[...protOps(['protClientId','protClientPrivateKey','protServiceGrant','protScope'],'use','app','Uses configured client identity/key and service-account grant.'),...protOps(protCaClaims,'create','app','Creates a fresh short-lived client assertion with one configured audience.'),...protOps(['protCaType'],'use','app','Selects the registered JWT client-authentication assertion type.'),...protOps(['protCaJwt'],'derive','app','Signs the assertion using the local client private key.')],protCaClaims.map(id=>protPayload(id))),
 protWire('prot-client-jwt-request','Authenticate the token request with client_assertion','app','realmA','The token endpoint receives client authentication and a separate grant.','Form fields are client_id, grant_type=client_credentials, scope, client_assertion_type and client_assertion. JWT claims are nested inside client_assertion. There is no client_secret, user password, browser, PKCE or new human login.',['protClientId','protServiceGrant','protScope','protCaType','protCaJwt'],['protClientId','protServiceGrant','protScope','protCaType','protCaJwt'].map(id=>protPayload(id)),labWire(protCaClaims,'app','realmA','Claim inside the signed client authentication JWT.','client_assertion → signed JWT')),
 protLocal('prot-client-jwt-verify','Verify the client assertion and reject replay','realmA','Realm A checks the registered client key, claims, lifetime and unique request identifier.','Verify the client-associated public key and allowed asymmetric signature algorithm, iss/sub identity, exact configured single audience and short exp. Check iat under freshness policy and jti against the configured replay cache, then retain the accepted identifier until expiry. jti/iat are included by this lab profile, not declared universally mandatory in RFC 7523. Only after client authentication may the service-account grant and scope be authorized.',[...protOps(['protClientPublicKey'],'use','realmA','Uses only the registered trusted client public verification key.'),...protOps(['protClientId','protCaType','protCaJwt',...protCaClaims,'protCaReplay'],'verify','realmA','Checks client assertion signature, configured identity/audience/time and replay policy.'),...protOps(['protCaReplay'],'store','realmA','Remembers the accepted jti during its validity window.'),...protOps(['protServiceGrant','protScope'],'verify','realmA','Applies service-account capability and allowed scope policy.')],[],['Registered client key and allowed alg','iss/sub identify this client','Single configured aud, short expiry','Fresh jti; no replay','Service account and scopes allowed']),
 protApiIssue('prot-client-jwt-issue'),protTokenResponse('prot-client-jwt-response'),
];

const protMtlsSteps=[
 protLocal('prot-mtls-prepare','Use the configured client certificate','app','The backend holds a public certificate and its protected private key.','This example explicitly enables both tls_client_auth client authentication and certificate-bound access tokens. They are separate capabilities. The certificate is public, while its corresponding private key stays in the client. The TLS server presents its own server certificate as usual; the lab focuses on the client evidence.',[...protOps(['protTlsCertificate','protTlsPrivateKey','protTlsAuthMethod','protTlsBoundSetting','protClientId'],'use','app','Uses the configured client certificate/private key and registered mTLS policy.'),...protOps(['protTlsProof'],'derive','app','Signs the TLS handshake transcript locally using the client private key.')],[protPayload('protTlsAuthMethod'),protPayload('protTlsBoundSetting')]),
 protWire('prot-mtls-handshake','Prove possession during TLS client authentication','app','realmA','The realm receives the public certificate and TLS handshake proof.','Certificate and CertificateVerify are TLS handshake objects, not OAuth form fields. The realm validates the trusted CA chain/registered certificate identity and the TLS possession proof. The private key itself is never transmitted.',['protTlsCertificate','protTlsProof'],[protPayload('protTlsCertificate'),protPayload('protTlsProof')],[],[],'backchannel'),
 protWire('prot-mtls-request','Send a grant over the authenticated TLS connection','app','realmA','The backend identifies its client and requests service-account API authorization.','POST the token form with client_id, grant_type=client_credentials and scope over the TLS connection authenticated with the registered certificate. No client_secret or JWT client assertion is needed in this selected method.',['protClientId','protServiceGrant','protScope'],['protClientId','protServiceGrant','protScope'].map(id=>protPayload(id))),
 protLocal('prot-mtls-bind','Authenticate the client and bind the token to its certificate','realmA','The realm computes the certificate thumbprint that the token will require.','Verify the trusted certificate chain, registered client identity and TLS CertificateVerify, then authorize the grant. Certificate binding is explicitly enabled separately. Compute BASE64URL(SHA256(DER(whole X.509 certificate))) and place it inside cnf as x5t#S256. This is a hash of the certificate, not just its public key and not a JWK thumbprint.',[...protOps(['protTlsCertificate','protTlsProof','protTlsAuthMethod','protClientId','protServiceGrant','protScope','protTlsBoundSetting'],'verify','realmA','Checks registered mTLS authentication and separately configured token binding.'),...protOps(['protCertThumbprint'],'derive','realmA','Hashes the full DER certificate with SHA-256 and base64url-encodes without padding.')],[protPayload('protCertThumbprint')],['Certificate trust/registered identity valid','TLS proof verifies key possession','Grant allowed','Certificate-bound token policy enabled']),
 protApiIssue('prot-mtls-issue',['protCertThumbprint']),protTokenResponse('prot-mtls-response','Bearer',['protCertThumbprint']),
 protLocal('prot-mtls-api-proof','Prove possession again to the API','app','The backend connects to the API using the same certificate and local private key.','The API independently requests/validates TLS client certificate evidence. The backend signs this new handshake transcript with the same protected key and presents the certificate corresponding to the token’s thumbprint. A copied access token without this key is insufficient.',[...protOps(['protTlsCertificate','protTlsPrivateKey','protAccessToken'],'use','app','Uses the issued token and same certificate/private key for the resource connection.'),...protOps(['protTlsProof','protBearerHeader'],'derive','app','Creates a fresh TLS handshake proof and the Bearer access-token header.')]),
 protWire('prot-mtls-api-request','Present the token over certificate-authenticated TLS','app','realmB','The API receives the bearer-scheme token together with TLS certificate possession evidence.','The access token is presented as Authorization: Bearer. CertificateVerify and the client certificate are TLS evidence. The API must still enforce the confirmation binding; normal bearer-token signature checks alone are insufficient.',['protAccessToken','protBearerHeader','protTlsCertificate','protTlsProof'],[protPayload('protBearerHeader'),protPayload('protTlsCertificate'),protPayload('protTlsProof')],labWire(['protCertThumbprint','protApiAudience'],'app','realmB','Nested claim in the presented access token.','Authorization → access_token → signed JWT')),
 protLocal('prot-mtls-api-check','Require the exact bound certificate at the API','realmB','The API checks ordinary authorization plus equality of the certificate thumbprints.','Validate the access-token issuer/signature/lifetime/audience/scopes and the TLS possession proof. Compute the current connection’s full DER certificate hash and compare it to cnf.x5t#S256; reject a missing or different certificate even if the token signature is valid. Keycloak’s generic adapters do not automatically provide this certificate-binding enforcement for an arbitrary external API; its implementation must do so.',[...protOps(['protRealmPublicKey'],'use','realmB','Uses trusted issuer public signing keys for token verification.'),...protOps(['protAccessToken','protApiAudience','protScope','protTlsCertificate','protTlsProof','protCertThumbprint'],'verify','realmB','Checks token authorization, TLS possession and exact confirmation thumbprint equality.')],[],['Issuer signature/lifetime/API authorization valid','TLS certificate/key possession valid','BASE64URL(SHA256(DER(current certificate))) equals cnf.x5t#S256']),
];

const protAuthIds=['protClientId','protRedirect','protResponseType','protScope','protState','protChallenge','protChallengeMethod'];
const protFrontStart=id=>protLocal(id,'Create the browser attempt and PKCE commitment','app','The backend creates state and a secret verifier before opening the realm page.','The verifier stays in the backend. Its public S256 commitment, client identifier, exact registered HTTPS callback, response_type=code and requested scopes belong to the authorization request. This lab demonstrates OAuth authorization; no OIDC ID token or nonce is needed.',[...protOps(['protClientId','protRedirect','protResponseType','protScope','protChallengeMethod','protTokenEndpoint'],'use','app','Uses configured client request parameters and token endpoint.'),...protOps(['protState','protVerifier'],'create','app','Creates and retains fresh request state and PKCE verifier locally.'),...protOps(['protChallenge'],'derive','app','Computes BASE64URL(SHA256(ASCII(code_verifier))), without padding.'),...protOps(['protState','protVerifier'],'store','app','Retains pending state and verifier until validated code redemption.')],[protPayload('protState'),protPayload('protChallenge')]);
const protApprove=id=>protStep(id,'Complete the configured realm login','user','browser','The person completes the realm page’s configured authentication and approval.','This local UI interaction summarizes successful configured authentication/consent. Main scenarios animate the actual password, TOTP and passkey factors. The authorization server resumes only after those checks succeed; this summary does not assert any particular factor or assurance level.',protOps(['protApproval'],'use','user','Completes the local browser interaction with the configured realm login/approval process.'),[protPayload('protApproval')],[],'local');
const protCodeCreate=id=>protLocal(id,'Bind a one-time code to the validated attempt','realmA','Successful realm authorization produces a code for this client and PKCE commitment.','The realm has completed its configured authentication/approval. It creates a short-lived single-use code bound to this client, redirect and S256 commitment. The returned state is the original request value, not a newly generated state. The compact lab summarizes the realm’s own authentication checks as a prerequisite at this point.',[...protOps(['protApproval','protClientId','protRedirect','protChallenge','protChallengeMethod'],'verify','realmA','Requires successful configured realm authorization and validated client/redirect/PKCE request.'),...protOps(['protCode'],'create','realmA','Creates a single-use client/redirect/PKCE-bound authorization code.'),...protOps(['protState'],'use','realmA','Returns the original correlation value unchanged.')],[protPayload('protCode'),protPayload('protState')]);
const protPlainCallback=(prefix)=>[
 protWire(prefix+'-redirect','Redirect the browser to the registered callback','realmA','browser','The browser receives code and the original state on the callback URL.','HTTP 302 Location uses the registered HTTPS redirect_uri with code and state. The realm tells the browser where to go; it does not call the backend callback itself.',['protCode','protState','protRedirect'],[labP('Location',protCallback+'?code='+protCode+'&state='+protState)],[],[],'redirect'),
 protWire(prefix+'-callback','Deliver the browser callback','browser','app','The browser delivers the code and state to the backend.','The callback contains no client secret or PKCE verifier. The backend must compare state with its original pending attempt before accepting the authorization response.',['protCode','protState'],[protPayload('protCode'),protPayload('protState')]),
 protLocal(prefix+'-state-check','Match the callback to the pending attempt','app','The backend validates state before redeeming the code.','Reject an unexpected state or missing pending attempt. Valid callback correlation does not itself validate the code; the token endpoint still verifies code bindings and PKCE.',protOps(['protState'],'verify','app','Compares the received state to the locally retained request state.'),[],['Original pending state matches']),
];
const protCodeFinish=prefix=>[
 protWire(prefix+'-redeem','Redeem the code directly with PKCE','app','realmA','The backend sends the retained verifier and client authentication to the token endpoint.','The HTTPS form body contains grant_type=authorization_code, code, redirect_uri and code_verifier. Registered client_id/client_secret are encoded within HTTP Basic client authentication. The verifier bypasses the browser and is not sent to an upstream IdP.',['protCodeGrant','protCode','protRedirect','protVerifier'],['protCodeGrant','protCode','protRedirect','protVerifier','protBasic'].map(id=>protPayload(id)),protBasicWire('app','realmA')),
 protLocal(prefix+'-pkce-check','Check code bindings and the PKCE proof','realmA','The realm authenticates the backend and verifies its secret against the stored commitment.','Validate client authentication, code expiry/single use, client and redirect binding, then compare BASE64URL(SHA256(ASCII(code_verifier))) to the code’s retained S256 challenge. Successful redemption consumes the code. PAR, JAR or JARM did not remove these checks.',protOps(['protBasic','protClientId','protClientSecret','protCode','protCodeGrant','protRedirect','protVerifier','protChallenge','protChallengeMethod'],'verify','realmA','Checks authenticated client, single-use code bindings and S256 verifier/commitment equality.'),[],['Client authenticated','Code current, single-use and client/redirect bound','S256 verifier matches original commitment']),
 protApiIssue(prefix+'-issue'),protTokenResponse(prefix+'-tokens'),
];

const protParSteps=[
 protFrontStart('prot-par-start'),
 protLocal('prot-par-endpoint','Select the discovered PAR endpoint','app','The backend chooses the realm’s configured pushed-authorization endpoint.','The discovered pushed_authorization_request_endpoint directs the authenticated POST. It is a destination URL, not a form-body member, and must belong to the intended authorization server.',protOps(['protParEndpoint'],'use','app','Uses the configured/discovered trusted PAR endpoint.'),[protPayload('protParEndpoint')]),
 protWire('prot-par-push','Push the complete authorization request over HTTPS','app','realmA','The backend authenticates and posts all authorization parameters before opening the browser.','POST the authorization request to pushed_authorization_request_endpoint using the registered confidential client authentication. Realm A sees the request directly: client_id, redirect_uri, response_type, scope, state and PKCE commitment/method. The secret verifier is not part of the pushed request. This example does not combine PAR with a signed Request Object; PAR and JAR can also be combined.',protAuthIds,[labP('HTTP','POST '+protParUrl),...protAuthIds.map(id=>protPayload(id)),protPayload('protBasic')],protBasicWire('app','realmA')),
 protLocal('prot-par-store','Validate and store the client-bound request','realmA','Realm A authenticates the client and stores the validated request behind an expiring handle.','Check client authentication, exact permitted redirect, code response type, allowed scope and S256 parameters. Store request fields with the authenticated client and an expiration/one-use policy. Generate an unpredictable request_uri only after these checks. PAR accepts no incoming request_uri reference in this posted request.',[...protOps([...protBasicIds,...protAuthIds],'verify','realmA','Authenticates the PAR caller and validates the complete authorization request.'),...protOps(['protParStoredRequest'],'store','realmA','Stores the exact validated authorization request bound to this authenticated client.'),...protOps(['protRequestUri','protParExpiresIn'],'create','realmA','Creates an unpredictable short-lived handle and its lifetime.')],[protPayload('protRequestUri'),protPayload('protParExpiresIn')]),
 protWire('prot-par-reference','Return the pushed-request reference','realmA','app','A 201 JSON response contains request_uri and its lifetime.','request_uri is a short-lived reference to the server-stored authorization request, not a code or token. expires_in is the reference lifetime; it does not describe an access token.',['protRequestUri','protParExpiresIn'],[labP('HTTP','201 Created'),protPayload('protRequestUri'),protPayload('protParExpiresIn')]),
 protWire('prot-par-browser','Open authorization with only client_id and request_uri','app','browser','The browser receives a small URL that points to the stored request.','The authorization URL uses client_id plus the PAR request_uri. state, scope, redirect and the PKCE commitment remain in the stored request instead of appearing as duplicate query parameters. code_verifier stays in the backend.',['protClientId','protRequestUri'],[labP('URL',protAuthUrl+'?client_id='+protClient+'&request_uri='+protHandle)],[],[],'local'),
 protWire('prot-par-authorize','Resolve the reference at the authorization endpoint','browser','realmA','The realm receives the same client identifier and pushed-request handle.','The realm checks the reference was issued to this client, has not expired and is valid under its one-use/reload policy, then resumes the stored authorization request.',['protClientId','protRequestUri'],[protPayload('protClientId'),protPayload('protRequestUri')]),
 protLocal('prot-par-resolve','Check handle expiry and original client binding','realmA','The stored state and PKCE commitment belong to this exact pending request.','An expired reference is rejected. The client must use a request_uri only once; the server should enforce one-time use but RFC 9126 permits deliberate duplicate handling for a browser refresh. This model uses one-time acceptance. The browser-supplied client_id must match the authenticated client bound to the stored request.',[...protOps(['protRequestUri','protClientId','protParExpiresIn','protParStoredRequest'],'verify','realmA','Checks reference/client binding, expiration and chosen one-use policy.'),...protOps(['protState','protChallenge','protChallengeMethod','protRedirect','protScope'],'use','realmA','Restores the originally authenticated and validated request fields locally.')],[],['Handle bound to same authenticated client','Reference unexpired','Selected one-use policy passes']),
 protApprove('prot-par-approve'),protCodeCreate('prot-par-code'),...protPlainCallback('prot-par'),...protCodeFinish('prot-par'),
];

const protRoClaims=['protRoIss','protRoAud','protRoExp','protRoJti'];
const protJarSteps=[
 protFrontStart('prot-jar-start'),
 protLocal('prot-jar-sign','Sign the complete authorization Request Object','app','The backend signs the request fields and its intended-server/freshness claims.','The Request Object includes all authorization parameters, iss=client_id, aud=Realm A issuer and this profile’s short exp and fresh jti. Sign it with the registered client private key. It is transmitted as request, not client_assertion; it protects authorization-request integrity and does not replace token-endpoint client authentication. This scenario uses signing without JWE encryption, so the browser can read the signed contents.',[...protOps([...protAuthIds,'protClientPrivateKey'],'use','app','Uses complete OAuth request fields and its local client signing key.'),...protOps(protRoClaims,'create','app','Adds the selected issuer/audience/expiry/replay profile claims.'),...protOps(['protRequestObject'],'derive','app','Signs the authorization Request Object with the registered client key.')],[protPayload('protRequestObject')]),
 protWire('prot-jar-browser','Give the browser the signed authorization request','app','browser','The URL identifies the client and carries its signed request JWT.','The outer query has client_id, response_type=code and request=<signed JWT>. Outer client_id and the Request Object’s client_id are identical. The duplicated response_type is also consistent. All substantive parameters are signed inside the object; omitted inner parameters cannot be recovered from unsigned query extras.',['protClientId','protResponseType','protRequestObject'],[labP('URL',protAuthUrl+'?client_id='+protClient+'&response_type=code&request=<signed-request-jwt>')],labWire([...protAuthIds,...protRoClaims],'app','browser','Signed member inside the Request Object; not an independently authoritative query value.','request → signed Request Object'),[],'local'),
 protWire('prot-jar-authorize','Deliver the signed Request Object to Realm A','browser','realmA','The realm receives the request JWT together with the same outer client identifier.','Use the registered client key and allowed request-object algorithm. The outer client_id must match the signed client_id. RFC 9101 processing uses Request Object parameters only; unsigned query parameters cannot override signed fields.',['protClientId','protResponseType','protRequestObject'],[protPayload('protClientId'),protPayload('protResponseType'),protPayload('protRequestObject')],labWire([...protAuthIds,...protRoClaims],'browser','realmA','Member carried inside the signed authorization Request Object.','request → signed Request Object')),
 protLocal('prot-jar-verify','Verify request signature, identity and profile policy','realmA','Realm A verifies the trusted client signature and uses the signed parameters only.','Validate the configured client public key/signature/algorithm, signed issuer and intended authorization-server audience and short expiry under the selected request-object policy. This example disables that policy’s optional nbf check because nbf is absent. The optional jti supports correlation; this lab does not claim a stock Keycloak one-use jti cache. Outer and inner client_id must be identical; this selected profile also uses a consistent duplicated response_type. Validate the resulting client/redirect/scope/PKCE request. Signing does not authenticate an arbitrary user or replace Realm A’s login flow.',[...protOps(['protClientPublicKey'],'use','realmA','Uses the client-associated public verification key and allowed algorithm.'),...protOps(['protRequestObject',...protRoClaims.filter(id=>id!=='protRoJti'),...protAuthIds,'protRoReplay'],'verify','realmA','Checks JWS, client_id equality, selected request freshness profile and authorization parameters.'),...protOps(['protRoJti'],'use','realmA','Uses the optional signed identifier for correlation without claiming a stock one-use replay cache.')],[],['Registered client signature valid','Outer client_id equals signed client_id','Intended server and selected freshness profile valid','Only signed inner parameters used','Redirect/scopes/PKCE allowed']),
 protApprove('prot-jar-approve'),protCodeCreate('prot-jar-code'),...protPlainCallback('prot-jar'),...protCodeFinish('prot-jar'),
];

const protJarmClaims=['protJarmIss','protJarmAud','protJarmExp','protCode','protState'];
const protJarmSteps=[
 protFrontStart('prot-jarm-start'),
 protLocal('prot-jarm-pending','Retain the expected issuer and response policy','app','The backend requests query.jwt and retains its pending callback context.','Remember the expected authorization server, client identifier, original state and PKCE verifier. Register/require the JARM signature algorithm and select response_mode=query.jwt. This scenario uses a signed response; optional JWE response encryption is a separate configuration.',[...protOps(['protResponseMode','protJarmAlg'],'use','app','Requests the configured signed JWT authorization-response mode.'),...protOps(['protJarmPending'],'store','app','Retains expected issuer/client/state and pending/consumed context.')],[protPayload('protResponseMode')]),
 protWire('prot-jarm-browser','Open the authorization request','app','browser','The browser receives an ordinary code request asking for a JWT-secured response.','The URL contains the ordinary client/redirect/scope/state/PKCE commitment plus response_mode=query.jwt. Neither verifier nor client credentials are in this URL.',[...protAuthIds,'protResponseMode'],[labP('URL',protAuthUrl),...[...protAuthIds,'protResponseMode'].map(id=>protPayload(id))],[],[],'local'),
 protWire('prot-jarm-authorize','Ask Realm A for a JARM-protected code response','browser','realmA','The realm receives and validates the authorization request and response-mode policy.','Realm A checks the registered client, permitted callback/scopes, PKCE commitment and supported JARM configuration before its configured user authentication/approval.',[...protAuthIds,'protResponseMode'],[...protAuthIds,'protResponseMode'].map(id=>protPayload(id))),
 protApprove('prot-jarm-approve'),protCodeCreate('prot-jarm-code'),
 protLocal('prot-jarm-sign','Sign the authorization response JWT','realmA','Realm A packages code and state with issuer, audience and short expiry.','Create a JARM JWT containing iss=Realm A issuer, aud=client_id, exp and the successful authorization response’s code and original state. Sign it with Realm A’s issuer signing key and the configured allowed algorithm. The object is an authorization response, not id_token; it does not introduce an OIDC identity-token nonce or subject claim.',[...protOps(['protCode','protState','protJarmAlg','protRealmSigningKey'],'use','realmA','Uses the completed code response and protected realm signing key.'),...protOps(['protJarmIss','protJarmAud','protJarmExp'],'create','realmA','Adds expected issuer, intended client and response expiry.'),...protOps(['protJarmResponse'],'derive','realmA','Signs the JWT authorization response.')],[protPayload('protJarmResponse')]),
 protWire('prot-jarm-redirect','Redirect with one response JWT','realmA','browser','The callback query carries response=<signed authorization response>.','Under query.jwt, code and state are claims inside response. They are not separate plaintext callback query parameters in this model. The signed claims are readable because response encryption is not selected.',['protJarmResponse'],[labP('Location',protCallback+'?response=<signed-jarm-jwt>')],labWire([...protJarmClaims,'protJarmAlg'],'realmA','browser','Claim/header member nested inside the signed authorization response.','response → signed JARM JWT'),[],'redirect'),
 protWire('prot-jarm-callback','Deliver the JARM callback to the backend','browser','app','The backend receives the JWT authorization response through the browser.','The browser delivers response=<signed JWT>. The backend may parse it locally, but must finish issuer/audience/expiry/signature/state validation before accepting or redeeming the contained code.',['protJarmResponse'],[protPayload('protJarmResponse')],labWire([...protJarmClaims,'protJarmAlg'],'browser','app','Member carried inside the signed JWT authorization response.','response → signed JARM JWT')),
 protLocal('prot-jarm-verify','Validate the entire response before using code','app','The backend checks the expected issuer, its audience, expiry, signature and pending state.','Use the trusted expected issuer’s public signing key and configured algorithm allowlist; reject alg=none. Check exact issuer, intended client audience and exp, then validate original state/pending attempt and mark it consumed under local policy. Grant-specific response parameters must not be processed before all checks succeed. JARM’s signing key is unrelated to a client private_key_jwt key.',[...protOps(['protRealmPublicKey','protJarmPending'],'use','app','Uses trusted expected issuer signing keys and original pending context.'),...protOps(['protJarmResponse','protJarmIss','protJarmAud','protJarmExp','protJarmAlg','protState'],'verify','app','Verifies JARM signature/claims/allowlist and original state before accepting its authorization code.'),...protOps(['protJarmPending'],'store','app','Marks the original attempt accepted/consumed after all checks.'),...protOps(['protCode'],'derive','app','Only now makes the validated grant-specific code available for redemption.')],[],['Expected issuer exact match','Audience matches original client_id','Response unexpired','Issuer signature valid; alg none forbidden','Original state/pending context valid','All checks before code processing']),
 ...protCodeFinish('prot-jarm'),
];

const protDpopCommon=['protDpopTyp','protDpopAlg','protDpopJwk','protDpopJti','protDpopHtm','protDpopHtu','protDpopIat'];
const protProofStep=(id,target,jti,withNonce=false)=>{
 const api=target==='api',proof=api?'protDpopApiProof':'protDpopTokenProof',claims=[...protDpopCommon,...(api?['protDpopAth']:[]),...(withNonce?['protDpopNonce']:[])];
 const step=protLocal(id,api?'Sign a fresh API request proof':'Sign a fresh token request proof','app',api?'The backend signs a new proof for this API method, target and token.':'The backend signs a proof binding its key to this token request.',api?'Create a new unique jti, current iat, htm=GET and htu equal to the API URI without query/fragment. Compute ath from the exact ASCII access-token string. Include the resource nonce only on the challenged retry. Sign using the same local DPoP key; never reuse the token-endpoint proof.':'Use the client-local DPoP key and prepare a proof protected header with typ=dpop+jwt, allowed asymmetric alg and its same public-only jwk. Its claims bind a fresh jti, current iat, htm=POST and htu equal to the token URL without query/fragment. This endpoint request is not a protected-resource token presentation, so it has no ath.',[...protOps(['protDpopPrivate','protDpopJwk','protDpopTyp','protDpopAlg',...(api?['protAccessToken']:[])],'use','app','Uses the same retained DPoP key/public JWK, configured proof header and, at the resource, exact issued token.'),...protOps(claims.filter(field=>!['protDpopAth','protDpopNonce','protDpopJwk','protDpopTyp','protDpopAlg'].includes(field)),'create','app','Creates fresh request-specific proof identifier, method, target and creation time.'),...(api?protOps(['protDpopAth','protDpopAuthorization'],'derive','app','Computes BASE64URL(SHA256(ASCII(access_token))) without padding and prepares Authorization: DPoP.'):[]),...(withNonce?protOps(['protDpopNonce'],'use','app','Copies the API-provided nonce into this fresh retry proof.'):[]),...protOps([proof],'derive','app','Signs a fresh proof using the retained local DPoP private key.')],[protPayload('protDpopJti',jti),protPayload('protDpopHtm',api?'GET':'POST'),protPayload('protDpopHtu',api?protApiUrl:protTokenUrl),...(api?[protPayload('protDpopAth')]:[]),...(withNonce?[protPayload('protDpopNonce')]:[])]);
 step.attributeValues={protDpopJti:jti,protDpopHtm:api?'GET':'POST',protDpopHtu:api?protApiUrl:protTokenUrl};return step;
};
const protDpopSteps=[
 protLocal('prot-dpop-keys','Keep a separate DPoP key pair locally','app','The backend creates the key that will constrain its API token.','DPoP is proof of key possession at the application layer, separate from OAuth client authentication. This confidential backend still uses its registered Basic client authentication for the selected client_credentials grant. Its DPoP private key stays local; public key material is carried in each proof header.',[...protOps(['protDpopPrivate'],'create','app','Creates and protects the client-local DPoP private key.'),...protOps(['protDpopJwk'],'derive','app','Derives public-only JWK key material from the key pair.'),...protOps(['protDpopPrivate','protDpopJwk'],'store','app','Retains the DPoP pair for this token’s subsequent proofs.')]),
 protProofStep('prot-dpop-token-sign','token','dpop_token_jti_51'),
 protWire('prot-dpop-token-request','Send client authentication and a DPoP proof','app','realmA','The token request includes a signed DPoP header and the independently authenticated grant.','POST the token endpoint with DPoP proof header plus the confidential client’s HTTP Basic authentication and grant_type=client_credentials/scope. DPoP does not replace confidential client authentication. Token-request proof members are inside the proof JWT; there is no ath in this request.',['protDpopTokenProof','protServiceGrant','protScope'],[protPayload('protDpopTokenProof'),protPayload('protBasic'),protPayload('protServiceGrant'),protPayload('protScope')],[...protBasicWire('app','realmA'),...labWire(protDpopCommon,'app','realmA','Protected header/claim inside the token-request DPoP JWT.','DPoP header → token request proof')]),
 protLocal('prot-dpop-token-check','Check request proof and bind the result to its public key','realmA','The realm validates client authentication and DPoP signature/method/target/freshness.','Check typ=dpop+jwt, allowed asymmetric alg, public-only jwk and proof signature. Require exact request method/URI binding, permitted iat freshness and unique jti under replay policy. Authenticate the confidential client separately and authorize its grant/scopes. Compute the RFC 7638 public JWK thumbprint and place it in the result token’s cnf.jkt. This model’s token endpoint does not require a nonce; the API will independently require one.',[...protOps([...protBasicIds,'protServiceGrant','protScope','protDpopTokenProof',...protDpopCommon,'protDpopReplay'],'verify','realmA','Checks client/grant and DPoP proof signature, type, algorithm, public JWK, method/target/time/replay.'),...protOps(['protDpopReplay'],'store','realmA','Records the accepted token-request proof identifier within its validation window.'),...protOps(['protDpopJkt'],'derive','realmA','Computes the canonical public JWK SHA-256 thumbprint for cnf.jkt.')],[protPayload('protDpopJkt')],['Client authenticated and grant allowed','Public-only jwk and valid asymmetric proof signature','POST/token target/current iat/fresh jti valid']),
 protApiIssue('prot-dpop-issue',['protDpopJkt']),protTokenResponse('prot-dpop-token-response','DPoP',['protDpopJkt']),
 protProofStep('prot-dpop-api-sign','api','dpop_api_jti_52'),
 protWire('prot-dpop-api-request','Present the key-bound token and a new API proof','app','realmB','The API receives Authorization: DPoP and a separate DPoP proof header.','Use the DPoP authorization scheme with the access token. The fresh proof covers GET, this API URI without query/fragment, fresh iat/jti and ath for this exact token. It is signed with the key whose thumbprint is in cnf.jkt. This first proof does not yet contain the API-required nonce.',['protAccessToken','protDpopAuthorization','protDpopApiProof'],[protPayload('protDpopAuthorization'),protPayload('protDpopApiProof')],[...labWire([...protDpopCommon,'protDpopAth'],'app','realmB','Member inside the new API-specific DPoP proof.','DPoP header → API request proof'),...labWire(['protDpopJkt','protApiAudience'],'app','realmB','Nested claim inside the presented key-bound token.','Authorization → access_token')]),
 protLocal('prot-dpop-api-challenge-create','Require a resource-specific nonce','realmB','The API’s policy requests its own freshness challenge before accepting access.','The resource server can require an unpredictable nonce. It checks the existing proof sufficiently to identify the nonce requirement but has not yet authorized access. API and authorization-server nonces are separate contexts. This is a standards-level resource policy, not a claim that every Keycloak deployment challenges every request.',[...protOps(['protDpopApiProof','protDpopJti','protDpopHtm','protDpopHtu','protDpopIat'],'verify','realmB','Checks incoming request-proof context before responding with the selected nonce policy.'),...protOps(['protDpopNonceHeader','protDpopChallenge'],'create','realmB','Creates an unpredictable API nonce and DPoP use_dpop_nonce challenge.'),...protOps(['protDpopReplay'],'store','realmB','Retains its current nonce/freshness policy locally.')]),
 protWire('prot-dpop-api-challenge','Return HTTP 401 with DPoP-Nonce','realmB','app','The resource tells the client which nonce to include in a fresh retry proof.','A protected resource responds HTTP 401 Unauthorized with WWW-Authenticate: DPoP error="use_dpop_nonce" and DPoP-Nonce. At a token endpoint the RFC instead uses HTTP 400 with JSON error=use_dpop_nonce. This animation shows the resource challenge only.',['protDpopNonceHeader','protDpopChallenge'],[labP('HTTP','401 Unauthorized'),protPayload('protDpopChallenge'),protPayload('protDpopNonceHeader')]),
 protLocal('prot-dpop-save-nonce','Retain the API nonce for this resource','app','The client stores the resource challenge and prepares to retry.','Treat the nonce as opaque and retain it for this resource server. Copy it into a newly signed proof as nonce; keep the same DPoP key and access token, but create a new jti and current iat.',[...protOps(['protDpopNonceHeader'],'use','app','Reads the opaque resource-server nonce from its challenge header.'),...protOps(['protDpopNonce'],'derive','app','Copies the supplied header value into the retry proof nonce claim.'),...protOps(['protDpopNonce'],'store','app','Retains this resource-specific nonce for the next proof.')]),
 protProofStep('prot-dpop-api-retry-sign','api','dpop_api_retry_jti_53',true),
 protWire('prot-dpop-api-retry','Retry with a freshly signed nonce-bound proof','app','realmB','The client presents the same token with a new proof containing the resource nonce.','The retried HTTP GET uses a different fresh jti and current iat, the same target/method and access-token hash, and the supplied nonce. The old proof is not replayed.',['protAccessToken','protDpopAuthorization','protDpopApiProof'],[protPayload('protDpopAuthorization'),protPayload('protDpopApiProof'),protPayload('protDpopNonce')],[...labWire([...protDpopCommon,'protDpopAth','protDpopNonce'],'app','realmB','Member inside the freshly signed API retry proof.','DPoP header → fresh nonce-bound API proof'),...labWire(['protDpopJkt','protApiAudience'],'app','realmB','Nested claim in the presented access token.','Authorization → access_token')]),
 protLocal('prot-dpop-api-accept','Validate token, proof key, token hash and nonce together','realmB','The API accepts only the correct token/key/request/nonce combination.','Validate the issuer-signed token’s ordinary lifetime/audience/scope authorization. Validate the fresh proof signature/header/type/allowed asymmetric algorithm/public-only jwk, current method/URI, iat/jti replay and resource nonce. Recompute the proof JWK thumbprint and require equality with cnf.jkt. Recompute BASE64URL(SHA256(ASCII(received access_token))) and require equality with ath. A missing or different key, token hash or nonce is rejected even when the access-token signature is valid.',[...protOps(['protRealmPublicKey'],'use','realmB','Uses trusted token-issuer public signing keys.'),...protOps(['protAccessToken','protApiAudience','protScope','protDpopApiProof',...protDpopCommon,'protDpopAth','protDpopNonce','protDpopJkt','protDpopReplay'],'verify','realmB','Checks token authorization, proof signature/key binding, exact token hash, actual request binding, time/replay and API nonce.'),...protOps(['protDpopReplay'],'store','realmB','Retains accepted proof freshness/replay state under the resource policy.')],[],['Issuer token/signature/lifetime/audience/scope valid','Proof typ/alg/public JWK/signature valid','Proof htm/htu/current iat/fresh jti valid','Proof key thumbprint equals cnf.jkt','ath equals exact received access-token hash','Resource-specific nonce valid']),
];

const protGrantClaims=['protGrantIss','protGrantSub','protGrantAud','protGrantExp','protGrantIat','protGrantJti'];
const protJwtGrantSteps=[
 protLocal('prot-jwt-grant-sign','Start with a trusted issuer’s subject assertion','realmB','The trusted external issuer prepares a short-lived JWT for an already verified subject.','This profile begins after the external identity was verified. The issuer signs iss, external-user sub, single aud equal to Realm A issuer, exp and this profile’s iat/jti. How the client obtained this assertion is outside RFC 7523; this local preparation/delivery is an explicit prerequisite, not a fictional mandatory OAuth endpoint. The subject is already linked to a local Realm A user.',[...protOps(['protGrantPrivate'],'use','realmB','Uses the trusted issuer’s locally retained private signing key.'),...protOps(protGrantClaims,'create','realmB','Creates a one-time short-lived subject assertion intended for Realm A.'),...protOps(['protGrantAssertion'],'derive','realmB','Signs the external subject assertion locally.')],protGrantClaims.map(id=>protPayload(id))),
 protWire('prot-jwt-grant-prerequisite','Obtain the signed subject assertion','realmB','app','The backend holds the trusted issuer’s JWT before requesting Realm A authorization.','This is illustrative prior delivery, whose transport is issuer/application-specific and outside the JWT authorization-grant profile. Only the signed assertion and its claims travel; the issuer private key stays local.',['protGrantAssertion'],[protPayload('protGrantAssertion')],labWire(protGrantClaims,'realmB','app','Claim inside the signed subject assertion obtained as a prerequisite.','assertion → trusted issuer JWT')),
 protWire('prot-jwt-grant-request','Use assertion as the authorization grant','app','realmA','The backend authenticates separately and posts the signed subject assertion.','The form selects grant_type=urn:ietf:params:oauth:grant-type:jwt-bearer and carries assertion plus scope. This confidential client uses HTTP Basic to authenticate independently. assertion represents the external subject; client_assertion would instead authenticate an OAuth client and is absent from this selected example. There is no browser code callback or PKCE in this grant.',['protJwtGrant','protGrantAssertion','protScope'],[protPayload('protBasic'),protPayload('protJwtGrant'),protPayload('protGrantAssertion'),protPayload('protScope')],[...protBasicWire('app','realmA'),...labWire(protGrantClaims,'app','realmA','Claim inside the authorization-grant assertion, not independent form parameters.','assertion → trusted issuer JWT')]),
 protLocal('prot-jwt-grant-validate','Check client, permitted issuer, linked subject and one-time assertion','realmA','Realm A verifies the configured external trust relationship independently from client authentication.','Current Keycloak requires a confidential client with JWT Authorization Grant enabled and the issuer in its allowed IdPs; the IdP must also allow JWT grants. Validate trusted issuer/signature/algorithm, external subject linked to an existing local user, exactly one configured issuer/token-endpoint audience, exp and configured freshness/replay policy. Default assertion reuse is disabled, so a unique jti is checked/remembered. Authorize requested client scopes under policy; possession of any signed JWT is not automatic authorization.',[...protOps(['protGrantPublic'],'use','realmA','Uses the specifically trusted external issuer public key and allowed algorithm.'),...protOps([...protBasicIds,'protJwtGrant','protScope','protGrantAssertion',...protGrantClaims,'protGrantPolicy','protGrantLink','protGrantReplay'],'verify','realmA','Authenticates the client, checks enabled/allowed issuer, signature/time/single audience, existing linked subject and default one-time assertion policy.'),...protOps(['protGrantReplay'],'store','realmA','Records the consumed subject assertion identifier while it could remain valid.'),...protOps(['protTransientSession'],'create','realmA','Creates the implementation’s transient user session after resolving the previously linked subject.')],[],['Confidential client independently authenticated','Client and IdP grant switches/allowlist permit issuer','Trusted external signature and short validity valid','Single configured Realm A audience','External subject already linked','Default one-time jti not reused']),
 protApiIssue('prot-jwt-grant-issue'),protTokenResponse('prot-jwt-grant-response'),
 protLocal('prot-jwt-grant-result','Retain the subject’s API authorization token','app','The backend receives a new Realm A access token under the linked subject’s authorization.','Current Keycloak creates a transient session for this grant and never issues a refresh token. The subject assertion is a grant credential distinct from any client-authentication assertion. A later request requires a new permitted subject assertion under the default no-reuse policy.',protOps(['protAccessToken','protTokenType','protExpiresIn','protScope'],'store','app','Retains the returned access token and metadata; no refresh token is issued.')),
];

export const PROTLAB_SCENARIOS=[
 protMakeScenario(protMeta('lab-client-jwt','private_key_jwt · signed client authentication','Authenticate a service-account request with a short-lived, one-time client JWT.',protUrls.jwt),protClientJwtSteps,{app:protBackend,realmA:protRealm}),
 protMakeScenario(protMeta('lab-mtls','mTLS · client authentication and certificate-bound API token','Use the client certificate twice and require its exact thumbprint at the API.',protUrls.mtls,false,'Supported in current Keycloak with X509 client credentials and certificate-bound tokens enabled separately. External API must implement RFC 8705 binding enforcement; generic adapters alone do not do so.'),protMtlsSteps,{app:protBackend,realmA:protRealm,realmB:protApi}),
 protMakeScenario(protMeta('lab-par','PAR · push authorization before opening the browser','Authenticate and store the complete request, then carry only a short-lived reference through the browser.',protUrls.par,true,'PAR is supported and enabled by default in the current feature catalog. Configure client authentication and optional PAR-only enforcement.'),protParSteps,{app:protBackend,realmA:protRealm,browser:protBrowser,user:protPerson}),
 protMakeScenario(protMeta('lab-jar','JAR · signed authorization Request Object','Sign the complete request; the realm verifies client identity and uses the signed inner parameters.',protUrls.jar,true,'Current Keycloak supports signed Request Objects and configurable strict request-object/algorithm/freshness policy. This example disables optional nbf verification and uses jti only for correlation, without claiming stock one-use caching. request_uri retrieval and optional JWE are separate variants.'),protJarSteps,{app:protBackend,realmA:protRealm,browser:protBrowser,user:protPerson}),
 protMakeScenario(protMeta('lab-jarm','JARM · signed JWT authorization response','Deliver code and state inside a signed authorization-response JWT and validate it before code redemption.',protUrls.jarm,true,'Current Keycloak advertises JWT authorization response modes and supports configured response signing/encryption algorithms. This scenario shows signed query.jwt; other transports/encryption remain variants.'),protJarmSteps,{app:protBackend,realmA:protRealm,browser:protBrowser,user:protPerson}),
 protMakeScenario(protMeta('lab-dpop','DPoP · key-bound token, fresh API proof and nonce retry','Bind the token to a public-key thumbprint, hash the exact API token and sign a fresh nonce-challenged request.',protUrls.dpop,false,'DPoP is supported and enabled by default in the current Keycloak catalog. The illustrated external API nonce challenge is an explicit RFC 9449 resource-server policy; no claim that every deployment always challenges.'),protDpopSteps,{app:protBackend,realmA:protRealm,realmB:protApi}),
 protMakeScenario(protMeta('lab-jwt-grant','JWT authorization grant · subject assertion versus client assertion','Use a trusted issuer’s subject JWT as the grant while authenticating the requesting client separately.',protUrls.jwt,false,'JWT Authorization Grant is supported and enabled by default in the current catalog. Client and IdP capabilities/allowlist, previously linked subject and default one-time assertion policy must be configured.'),protJwtGrantSteps,{app:protBackend,realmA:protRealm,realmB:{name:'Trusted external issuer',role:'JWT assertion issuer',plainRole:'Signs an existing subject’s assertion for Realm A under configured trust.',notes:['External subject was verified earlier and is already linked in Realm A.','Keeps its assertion signing private key local.']}}),
];
