// Teaching model: synthetic example values, no live network or real credentials.
// Every payload name is a protocol/API member, a standard HTTP header, or an
// explicitly labelled local operation. Example suffixes identify the two hops.

const URLS = {
  oauth: 'https://www.rfc-editor.org/rfc/rfc6749',
  native: 'https://www.rfc-editor.org/rfc/rfc8252',
  pkce: 'https://www.rfc-editor.org/rfc/rfc7636',
  oidc: 'https://openid.net/specs/openid-connect-core-1_0.html',
  discovery: 'https://openid.net/specs/openid-connect-discovery-1_0.html',
  jwt: 'https://www.rfc-editor.org/rfc/rfc7519',
  webauthn: 'https://www.w3.org/TR/webauthn-3/',
  keycloak: 'https://www.keycloak.org/docs/latest/server_admin/index.html',
};

export const EXAMPLE = {
  issuerA: 'https://idp1.example.test/realms/realm-a',
  issuerB: 'https://idp2.example.test/realms/realm-b',
  authA: 'https://idp1.example.test/realms/realm-a/protocol/openid-connect/auth',
  authB: 'https://idp2.example.test/realms/realm-b/protocol/openid-connect/auth',
  tokenA: 'https://idp1.example.test/realms/realm-a/protocol/openid-connect/token',
  tokenB: 'https://idp2.example.test/realms/realm-b/protocol/openid-connect/token',
  brokerCallback: 'https://idp1.example.test/realms/realm-a/broker/realm-b/endpoint',
  appCallback: 'http://127.0.0.1:54321/callback',
  rpId: 'idp2.example.test',
  origin: 'https://idp2.example.test',
  clientApp: 'desktop-app',
  clientBroker: 'realm-a-broker',
  stateApp: 'st_app_7f81',
  stateBroker: 'st_broker_94ac',
  nonceApp: 'n_app_a92c',
  nonceBroker: 'n_broker_f19d',
  verifier: 'dBjftJeZ4CVP-mB92K27uhbUJU1p1r_wW1gFWFOEjXk',
  challenge: 'E9Melhoa2OwvFrEMTJguCHaoeK1t8URWbuGJSstw-cM',
  loginChallenge: 'wa_login_random_bytes',
  registrationChallenge: 'wa_register_random_bytes',
  codeB: 'c_broker_83ab',
  codeA: 'c_app_69d1',
};

const attribute = (name, meaning, origin, purpose, example, standard, source) => ({
  name, meaning, description: meaning, origin, generator: origin, purpose, example, standard, source,
});

export const ATTRIBUTES = {
  clientIdApp: attribute('client_id', 'The public identifier of the application’s OAuth/OIDC client registration in Realm A.', 'Assigned during client registration, then configured in the application. Reused across sign-ins; not generated for each login.', 'Selects the application’s registered settings and binds the authorization code to this client. A public client sends it in the token-request body; the illustrated confidential backend includes it in HTTP Basic client authentication. The identifier alone is not a password or proof of authentication.', EXAMPLE.clientApp, 'RFC 6749 §2.2 / §2.3.1 / §4.1', URLS.oauth),
  clientIdBroker: attribute('client_id', 'The registration name of Realm A acting as a client of Realm B.', 'Registered by an administrator in Realm B.', 'Tells B which broker is requesting authentication.', EXAMPLE.clientBroker, 'RFC 6749 §2.2', URLS.oauth),
  clientSecret: attribute('client_secret', 'A confidential client credential used by the broker, not by the native app.', 'Provisioned for the broker client in Realm B and configured securely in A.', 'Authenticates the A-to-B token request. This example uses HTTP Basic client authentication.', 'broker-only secret; never shown to the browser', 'RFC 6749 §2.3.1', URLS.oauth),
  redirectApp: attribute('redirect_uri', 'The local address where the desktop app receives the browser callback.', 'The app binds a loopback listener; the allowed redirect is registered in A.', 'Lets the browser deliver the authorization code to the app on this computer.', EXAMPLE.appCallback, 'RFC 8252 §7.3', URLS.native),
  redirectBroker: attribute('redirect_uri', 'The HTTPS callback where Realm A receives Realm B’s authorization response.', 'Derived from Realm A’s broker configuration and registered on the broker client in B.', 'Returns the browser to A after authentication in B.', EXAMPLE.brokerCallback, 'RFC 6749 §4.1.1 / Keycloak brokering', URLS.keycloak),
  responseType: attribute('response_type', 'Chooses an authorization code response.', 'Set to code by each OIDC client.', 'Keeps tokens out of these browser redirects.', 'code', 'OIDC Core §3.1.2.1', URLS.oidc),
  scope: attribute('scope', 'A space-separated list of requested permissions and identity features.', 'Chosen by the requesting client and constrained by the realm’s configuration.', 'openid selects OIDC; other scopes affect claims and permissions.', 'openid profile', 'OIDC Core §3.1.2.1', URLS.oidc),
  stateApp: attribute('state', 'A random label for the app’s own sign-in attempt.', 'Generated by the native app and retained locally.', 'The app compares the returned value before accepting its callback.', EXAMPLE.stateApp, 'RFC 6749 §4.1.1 and §10.12', URLS.oauth),
  stateBroker: attribute('state', 'A separate correlation value for the broker’s sign-in attempt in B.', 'Generated by Realm A for the A-to-B request.', 'Lets A match B’s callback to the correct broker session.', EXAMPLE.stateBroker, 'RFC 6749 §4.1.1 and §10.12', URLS.oauth),
  nonceApp: attribute('nonce', 'A random value the app expects inside A’s ID token.', 'Generated by the app for this OIDC request.', 'Binds the received identity token to this sign-in attempt.', EXAMPLE.nonceApp, 'OIDC Core §3.1.2.1 and §3.1.3.7', URLS.oidc),
  nonceBroker: attribute('nonce', 'A different nonce that A expects inside B’s ID token.', 'Generated by A; this example explicitly includes it on the broker hop.', 'Binds B’s identity token to A’s authentication request.', EXAMPLE.nonceBroker, 'OIDC Core §3.1.2.1 and §3.1.3.7', URLS.oidc),
  codeVerifier: attribute('code_verifier', 'A high-entropy one-time secret for the app’s authorization code exchange.', 'Generated and retained by the app before opening the browser.', 'Proves that the app redeeming the code began the PKCE request.', EXAMPLE.verifier, 'RFC 7636 §4.1', URLS.pkce),
  codeChallenge: attribute('code_challenge', 'The public PKCE commitment derived from code_verifier.', 'The app computes BASE64URL(SHA256(ASCII(code_verifier))), without padding.', 'A remembers it and checks the verifier during the token exchange.', EXAMPLE.challenge, 'RFC 7636 §4.2', URLS.pkce),
  codeChallengeMethod: attribute('code_challenge_method', 'The method used to derive the PKCE challenge.', 'Selected by the app.', 'S256 tells A to compare the SHA-256-based commitment.', 'S256', 'RFC 7636 §4.2', URLS.pkce),
  grantType: attribute('grant_type', 'Names the operation requested at the token endpoint.', 'Set by the client redeeming an authorization code.', 'Selects authorization-code exchange instead of another grant.', 'authorization_code', 'RFC 6749 §4.1.3', URLS.oauth),
  codeA: attribute('code', 'A short-lived, single-use authorization code issued by Realm A.', 'Generated by A after the brokered sign-in succeeds.', 'The app exchanges it at A’s token endpoint with its PKCE verifier.', EXAMPLE.codeA, 'RFC 6749 §4.1.2', URLS.oauth),
  codeB: attribute('code', 'A different short-lived, single-use code issued by Realm B.', 'Generated by B after its configured authentication factors succeed.', 'Only the registered broker redeems it at B’s token endpoint.', EXAMPLE.codeB, 'RFC 6749 §4.1.2', URLS.oauth),
  authorizationHeader: attribute('Authorization', 'An HTTP request header carrying broker client authentication in this example.', 'A encodes the broker client ID and secret according to HTTP Basic.', 'Authenticates the confidential broker on the HTTPS token request to B.', 'Basic base64(encoded-client-id:encoded-client-secret)', 'RFC 6749 §2.3.1', URLS.oauth),
  location: attribute('Location', 'The destination URL supplied in an HTTP redirect response.', 'The realm constructs the next browser destination.', 'The browser follows it. The realm does not itself call the destination.', 'HTTP 302 → next URL', 'RFC 9110 §10.2.2', 'https://www.rfc-editor.org/rfc/rfc9110'),
  idTokenA: attribute('id_token', 'A signed OIDC identity statement issued by Realm A to the app.', 'A creates and signs it using its realm signing key.', 'The app validates it to establish the signed-in user. Its audience is desktop-app.', 'JWT: iss=A, aud=desktop-app, sub=user-in-A, nonce=n_app_a92c', 'OIDC Core §2', URLS.oidc),
  idTokenB: attribute('id_token', 'A signed OIDC identity statement issued by Realm B to the broker.', 'B creates and signs it using B’s realm signing key.', 'A validates it before accepting B’s identity result. Its audience is realm-a-broker.', 'JWT: iss=B, aud=realm-a-broker, sub=user-in-B, nonce=n_broker_f19d', 'OIDC Core §2', URLS.oidc),
  accessTokenA: attribute('access_token', 'An authorization token issued by A for permitted resources.', 'Realm A issues it according to client scopes and audience configuration.', 'The app presents it to an appropriate API; it is not a replacement for ID-token validation.', 'A-issued access token; API audience depends on configuration', 'RFC 6749 §1.4', URLS.oauth),
  accessTokenB: attribute('access_token', 'An authorization token issued by B on the broker hop.', 'Realm B issues it in the token response to A.', 'A may use it for B’s UserInfo endpoint. It is not the app’s A-issued token.', 'B-issued access token', 'RFC 6749 §1.4 / OIDC Core §5.3', URLS.oidc),
  refreshToken: attribute('refresh_token', 'An optional credential for obtaining another access token.', 'Issued by A if the client and realm policies allow it.', 'Lets the app request fresh tokens without repeating the full browser sign-in.', 'optional, according to Realm A policy', 'RFC 6749 §1.5', URLS.oauth),
  tokenType: attribute('token_type', 'Names the access-token usage scheme.', 'Included by the token endpoint.', 'Bearer means possession authorizes use; protect the token.', 'Bearer', 'RFC 6749 §5.1', URLS.oauth),
  expiresIn: attribute('expires_in', 'Access-token lifetime in seconds, relative to the token response.', 'Set by the issuing realm.', 'Lets the client know when its access token expires.', '300 (illustrative)', 'RFC 6749 §5.1', URLS.oauth),
  issuerA: attribute('iss', 'The exact issuer identifier inside A’s token.', 'Realm A includes its configured issuer URL.', 'The app checks that the token came from its intended realm.', EXAMPLE.issuerA, 'OIDC Core §2', URLS.oidc),
  issuerB: attribute('iss', 'The exact issuer identifier inside B’s token.', 'Realm B includes its configured issuer URL.', 'A checks that the upstream token came from the configured B realm.', EXAMPLE.issuerB, 'OIDC Core §2', URLS.oidc),
  audience: attribute('aud', 'The intended recipient or recipients of a token.', 'Chosen by the issuer for the token’s type and client configuration.', 'An ID token must include the receiving OIDC client’s client_id; an API access token has its own audience rules.', 'ID token A: desktop-app; ID token B: realm-a-broker', 'OIDC Core §2 / RFC 7519 §4.1.3', URLS.jwt),
  subjectA: attribute('sub', 'The subject identifier of this user within A.', 'Assigned by Realm A to its local linked or imported user.', 'Identifies the app’s user together with A’s iss; it need not equal B’s sub.', 'user-in-A-204', 'OIDC Core §2', URLS.oidc),
  subjectB: attribute('sub', 'The subject identifier of this user within B.', 'Assigned by Realm B.', 'A uses the trusted external identity and broker mapping policy to resolve its local user.', 'user-in-B-913', 'OIDC Core §2', URLS.oidc),
  exp: attribute('exp', 'The time after which the token must not be accepted.', 'Set by the issuer as a NumericDate, measured in seconds since the Unix epoch.', 'Limits how long a token is valid.', 'iat + 300 (illustrative)', 'RFC 7519 §4.1.4', URLS.jwt),
  iat: attribute('iat', 'The time when the token was issued.', 'Set by the issuer as a NumericDate.', 'Helps clients assess the token’s issuance time under their validation policy.', 'Unix-epoch seconds', 'RFC 7519 §4.1.6', URLS.jwt),
  jwksUri: attribute('jwks_uri', 'The discovery address of a realm’s public token-verification keys.', 'Published in OIDC provider metadata.', 'Lets a client retrieve public keys to validate realm-signed tokens.', 'https://idp1.example.test/realms/realm-a/protocol/openid-connect/certs', 'OIDC Discovery §3', URLS.discovery),
  authorizationEndpoint: attribute('authorization_endpoint', 'The metadata address that begins browser-based authorization.', 'Published in the realm’s OIDC discovery document.', 'The client sends the browser here with its authorization request.', 'A or B: /protocol/openid-connect/auth', 'OIDC Discovery §3', URLS.discovery),
  tokenEndpoint: attribute('token_endpoint', 'The metadata address for direct code-to-token exchange.', 'Published in the realm’s discovery document.', 'The native app or broker calls it directly over HTTPS.', 'A or B: /protocol/openid-connect/token', 'OIDC Discovery §3', URLS.discovery),
  realmSigningKey: attribute('realm signing key (private)', 'The realm’s private key used to sign tokens; this is not a request parameter.', 'Provisioned and retained by the Keycloak realm’s key provider.', 'Lets receivers validate realm-issued JWTs with the matching published public key.', 'Separate signing keys for A and B', 'Keycloak realm keys / OIDC Core §2', URLS.keycloak),
  session: attribute('authentication session / SSO session', 'Keycloak’s server-side sign-in context; its cookie details are implementation-specific.', 'Created and managed by the relevant realm.', 'Connects browser actions and can enable later single sign-on.', 'A session and B session are separate', 'Keycloak sessions', URLS.keycloak),
  challengeLogin: attribute('challenge', 'Fresh unpredictable bytes for this WebAuthn sign-in.', 'Generated by Realm B and bound to its current authentication attempt.', 'The signed response must match this challenge, so an old assertion cannot complete a new attempt.', EXAMPLE.loginChallenge + ' (bytes; symbolic)', 'WebAuthn §5.5 / §7.2', URLS.webauthn),
  challengeRegistration: attribute('challenge', 'Fresh unpredictable bytes for this separate passkey registration.', 'Generated by B after the user has a verified account/session.', 'B matches the registration response to this enrollment ceremony.', EXAMPLE.registrationChallenge + ' (bytes; symbolic)', 'WebAuthn §5.4 / §7.1', URLS.webauthn),
  rpId: attribute('rpId / rp.id', 'The domain that scopes this WebAuthn credential.', 'Configured by Realm B, then checked against the browser page’s origin.', 'The authenticator selects a key registered for this RP. It is a domain, without scheme, path or port.', EXAMPLE.rpId, 'WebAuthn §5.4.2 / §5.5', URLS.webauthn),
  rpName: attribute('rp.name', 'The readable name of the relying party during registration.', 'Configured by B.', 'Helps the user recognize the service creating a passkey.', 'Keycloak Realm B', 'WebAuthn §5.4.2', URLS.webauthn),
  origin: attribute('origin', 'The security origin of the page invoking WebAuthn.', 'The browser derives it from B’s loaded HTTPS page.', 'B checks it to prevent another website from impersonating its sign-in page.', EXAMPLE.origin, 'WebAuthn §5.8.1 / §7.2', URLS.webauthn),
  allowCredentials: attribute('allowCredentials', 'The credential IDs accepted for this WebAuthn request.', 'Prepared by B from its known credentials, or left empty for account discovery.', 'An empty array allows a discoverable passkey to select the account.', '[] in this username-free example', 'WebAuthn §5.5', URLS.webauthn),
  userVerification: attribute('userVerification', 'The policy requiring a local check of the user.', 'Configured in B’s WebAuthn policy and requested in the ceremony.', 'required asks for PIN, biometrics or another supported local verification mechanism.', 'required', 'WebAuthn §5.4.6 / §5.5', URLS.webauthn),
  timeout: attribute('timeout', 'A browser waiting-time hint for the WebAuthn operation, in milliseconds.', 'Chosen by the relying party.', 'Controls the interaction window; it is not an authorization-code or token lifetime.', '60000', 'WebAuthn §5.4 / §5.5', URLS.webauthn),
  residentKey: attribute('authenticatorSelection.residentKey', 'The registration policy for a discoverable credential.', 'Requested by B during passkey enrollment.', 'required makes later account selection possible without a typed username.', 'required', 'WebAuthn §5.4.4', URLS.webauthn),
  userId: attribute('user.id', 'An opaque user handle supplied during registration.', 'B assigns stable opaque bytes for the B account.', 'Associates the new credential with that account. It should not contain identifying personal data.', 'opaque-user-B-bytes', 'WebAuthn §5.4.3', URLS.webauthn),
  userName: attribute('user.name', 'The readable account name displayed during passkey selection.', 'B supplies it from the verified account.', 'Helps the user choose the intended account.', 'alice', 'WebAuthn §5.4.3', URLS.webauthn),
  displayName: attribute('user.displayName', 'A user-friendly account label.', 'B supplies it during registration.', 'Makes the authenticator’s account picker understandable.', 'Alice', 'WebAuthn §5.4.3', URLS.webauthn),
  pubKeyCredParams: attribute('pubKeyCredParams', 'The ordered list of acceptable credential types and signature algorithms.', 'B prepares it from its configured WebAuthn policy.', 'The authenticator chooses a supported algorithm; include appropriate options for the chosen device.', '[{type: "public-key", alg: -7}, {type: "public-key", alg: -257}]', 'WebAuthn §5.3 / §5.4', URLS.webauthn),
  attestation: attribute('attestation', 'The registration request’s preference for device-provenance evidence conveyed to the relying party.', 'Chosen by the relying party’s enrollment policy.', 'none requests that identifying attestation evidence is not conveyed to the relying party; the browser may replace the authenticator’s attestation statement with none.', 'none', 'WebAuthn §5.4.7', URLS.webauthn),
  rpObject: attribute('rp', 'The relying-party identity object in WebAuthn creation options.', 'Realm B prepares it from its configured RP ID and readable RP name.', 'Scopes the new credential to the intended relying party and identifies that service to the person.', '{ id: "idp2.example.test", name: "Keycloak Realm B" }', 'WebAuthn §5.4.2', URLS.webauthn),
  userObject: attribute('user', 'The verified account identity object in WebAuthn creation options.', 'Realm B prepares it from the account being enrolled.', 'Binds the credential to opaque user.id and gives the authenticator readable account labels.', '{ id: opaque-user-B-bytes, name: "alice", displayName: "Alice" }', 'WebAuthn §5.4.3', URLS.webauthn),
  authenticatorSelection: attribute('authenticatorSelection', 'The selection and capability policy for creating the passkey.', 'Realm B prepares it from its WebAuthn Passwordless Policy.', 'This example requires a discoverable credential and local user verification, allowing either illustrated authenticator when compatible.', '{ residentKey: "required", userVerification: "required" }', 'WebAuthn §5.4.4', URLS.webauthn),
  credentialId: attribute('id / rawId', 'The opaque identifier of this WebAuthn credential.', 'Generated by the authenticator during registration; id encodes rawId as base64url.', 'B uses it to find the matching stored public key and account.', 'credential-id-bytes (symbolic)', 'WebAuthn §5.1', URLS.webauthn),
  credentialType: attribute('type', 'The credential type of a PublicKeyCredential.', 'Defined by the WebAuthn API.', 'Distinguishes this public-key credential from other credential types.', 'public-key', 'WebAuthn §5.1', URLS.webauthn),
  privateKey: attribute('privateKey (credential source)', 'The secret key that creates WebAuthn signatures.', 'Created by the selected authenticator during registration.', 'Proves possession of the credential. It stays in the authenticator/provider’s protected environment and is not sent to Keycloak.', 'protected credential private key; never transmitted', 'WebAuthn §6.1 / credential source', URLS.webauthn),
  credentialPublicKey: attribute('credentialPublicKey', 'The public half of the passkey’s key pair.', 'Created by the authenticator and supplied in registration attested credential data.', 'B stores it to verify later signatures; it cannot create those signatures.', 'COSE_Key: ES256 or RS256, selected at enrollment', 'WebAuthn §6.5.1', URLS.webauthn),
  clientDataJSON: attribute('clientDataJSON', 'Browser-produced JSON bytes describing this ceremony.', 'The browser serializes type, challenge, origin and related context.', 'Its exact bytes are hashed and bound into the signed assertion.', '{type: "webauthn.get", challenge: "…", origin: "https://idp2.example.test"}', 'WebAuthn §5.8.1', URLS.webauthn),
  clientDataHash: attribute('clientDataHash', 'The SHA-256 digest of the browser’s exact clientDataJSON bytes.', 'Calculated by the browser/client platform.', 'Passed to the authenticator and included in what it signs. Re-serializing the JSON can change the hash.', 'SHA256(clientDataJSON bytes)', 'WebAuthn §6.3.3', URLS.webauthn),
  clientDataType: attribute('clientDataJSON.type', 'Names the WebAuthn ceremony in the browser’s signed context.', 'Set by the browser.', 'B checks webauthn.get for sign-in and webauthn.create for registration.', 'webauthn.get or webauthn.create', 'WebAuthn §5.8.1', URLS.webauthn),
  crossOrigin: attribute('crossOrigin', 'Reports whether the ceremony comes from a cross-origin frame.', 'Determined by the browser and included in clientDataJSON.', 'Lets B enforce the permitted embedding context.', 'false for this top-level sign-in page', 'WebAuthn §5.8.1', URLS.webauthn),
  authenticatorData: attribute('authenticatorData', 'Binary authenticator data that is signed with clientDataHash.', 'Constructed by the authenticator.', 'Contains RP binding, UP/UV flags, signCount and possible extension or backup metadata.', 'rpIdHash || flags || signCount || optional data', 'WebAuthn §6.1', URLS.webauthn),
  rpIdHash: attribute('rpIdHash', 'The SHA-256 hash of the RP ID inside authenticatorData.', 'Computed by the authenticator.', 'B compares it with SHA256 of the configured RP ID.', 'SHA256("idp2.example.test")', 'WebAuthn §6.1', URLS.webauthn),
  flagsUP: attribute('UP (User Present flag)', 'The authenticator-data flag reporting that user presence was checked.', 'Set by the authenticator in authenticatorData.', 'During sign-in it is covered by the verified assertion signature. Registration requires the full creation-ceremony checks and applicable attestation policy; fmt none supplies no attestation signature. Presence alone does not imply user verification.', 'UP = 1', 'WebAuthn §6.1 / §7.1 / §7.2 / §8.7', URLS.webauthn),
  flagsUV: attribute('UV (User Verified flag)', 'The authenticator-data flag reporting successful local user verification.', 'Set by the authenticator after its supported verification mechanism succeeds.', 'The relying party checks UV when user verification is required. Sign-in binds it with the verified assertion signature. Registration requires the full creation-ceremony checks and applicable attestation policy; fmt none supplies no attestation signature. PINs and biometric samples stay local.', 'UV = 1', 'WebAuthn §6.1 / §7.1 / §7.2 / §8.7', URLS.webauthn),
  signCount: attribute('signCount', 'An authenticator signature counter value.', 'Maintained by the authenticator and stored by B as appropriate.', 'Can help assess possible credential cloning when supported; some credentials keep it zero.', 'device-dependent; may be 0', 'WebAuthn §6.1.1 / §7.2', URLS.webauthn),
  signature: attribute('signature', 'The cryptographic assertion signature returned for sign-in.', 'The authenticator signs authenticatorData || SHA256(clientDataJSON bytes) using the credential private key.', 'B verifies it with the stored credential public key.', 'Sign(privateKey, authenticatorData || clientDataHash)', 'WebAuthn §6.3.3 / §7.2', URLS.webauthn),
  userHandle: attribute('userHandle', 'The account’s opaque user.id returned by a discoverable credential.', 'Stored by the authenticator at registration and returned for this selected account.', 'B resolves the account and checks the credential belongs to it; it is not an OIDC sub.', 'opaque-user-B-bytes', 'WebAuthn §5.2.2', URLS.webauthn),
  attestationObject: attribute('attestationObject', 'The binary CBOR registration response containing authenticator data and an attestation statement.', 'Produced for registration and returned via the browser.', 'B extracts the credential ID/public key and applies the registration verification policy.', 'CBOR {fmt: "none", authData: …, attStmt: {}}', 'WebAuthn §6.5.4 / §7.1', URLS.webauthn),
  localVerification: attribute('User verification (local operation)', 'The person unlocks the selected authenticator using its supported mechanism.', 'The user supplies a PIN, biometric gesture or other supported verification locally.', 'Authorizes the use of the private key. The server receives a signed verification flag, not the PIN or fingerprint.', 'YubiKey: PIN + touch; Windows Hello: PIN or biometrics', 'WebAuthn user verification', URLS.webauthn),
  acr: attribute('acr', 'An optional authentication-context class claim.', 'Set by the issuer according to its configured authentication policy.', 'Can describe an assurance class, but only when policy and validation agree on its meaning.', 'policy-defined; not automatically a passkey guarantee', 'OIDC Core §2', URLS.oidc),
  amr: attribute('amr', 'An optional array of authentication-method reference values.', 'Set by the issuer when configured to describe authentication methods.', 'Requires agreed semantics; A must not invent proof that B used a passkey.', 'configuration-dependent array', 'OIDC Core §2', URLS.oidc),
};

const attr = (id, kind) => ({ id, kind });

export const ACTORS = {
  user: {
    id: 'user', name: 'Person', role: 'End user', plainRole: 'Starts sign-in and approves using a passkey.', color: '#fbbf24',
    attributes: [attr('userName', 'static'), attr('displayName', 'static'), attr('localVerification', 'generated')],
    notes: ['In passkey modes, uses one selected authenticator for this attempt.', 'PINs and biometric samples stay within the local verification mechanism.'],
  },
  app: {
    id: 'app', name: 'Local application', role: 'Public native OIDC client', plainRole: 'Receives the final login result on this computer.', color: '#38bdf8',
    attributes: [attr('clientIdApp', 'static'), attr('redirectApp', 'static'), attr('authorizationEndpoint', 'static'), attr('tokenEndpoint', 'static'), attr('jwksUri', 'static'), attr('scope', 'static'), attr('stateApp', 'generated'), attr('nonceApp', 'generated'), attr('codeVerifier', 'generated'), attr('codeChallenge', 'generated'), attr('codeChallengeMethod', 'static'), attr('codeA', 'received'), attr('idTokenA', 'received'), attr('accessTokenA', 'received'), attr('refreshToken', 'received')],
    notes: ['Public client: no embedded client_secret.', 'Starts an HTTP listener on 127.0.0.1 and opens the system browser.', 'Uses Realm A’s issuer and verification keys, not B’s passkey public key.'],
  },
  browser: {
    id: 'browser', name: 'System browser', role: 'External user-agent / WebAuthn client', plainRole: 'Carries redirects and displays the secure login pages.', color: '#a78bfa',
    attributes: [attr('origin', 'static'), attr('location', 'received'), attr('session', 'received'), attr('challengeLogin', 'received'), attr('challengeRegistration', 'received'), attr('rpId', 'received'), attr('clientDataJSON', 'generated'), attr('clientDataHash', 'generated'), attr('crossOrigin', 'generated'), attr('authenticatorData', 'received'), attr('signature', 'received'), attr('attestationObject', 'received')],
    notes: ['WebAuthn runs on Realm B’s HTTPS page.', 'It follows both callbacks: B → A and A → loopback.', 'It cannot read the passkey private key.'],
  },
  realmA: {
    id: 'realmA', name: 'IdP 1 · Realm A', role: 'OIDC provider + identity broker', plainRole: 'Trusts the upstream sign-in and issues the app’s tokens.', color: '#22d3ee',
    attributes: [attr('issuerA', 'static'), attr('realmSigningKey', 'static'), attr('clientIdBroker', 'static'), attr('clientSecret', 'static'), attr('redirectBroker', 'static'), attr('stateBroker', 'generated'), attr('nonceBroker', 'generated'), attr('session', 'generated'), attr('codeB', 'received'), attr('idTokenB', 'received'), attr('accessTokenB', 'received'), attr('subjectA', 'generated'), attr('codeA', 'generated'), attr('idTokenA', 'generated'), attr('accessTokenA', 'generated'), attr('refreshToken', 'generated')],
    notes: ['Acts as a confidential OIDC client when talking to B.', 'B’s sub is mapped to a distinct local A identity according to broker policy.', 'A does not inspect the passkey signature directly.'],
  },
  realmB: {
    id: 'realmB', name: 'IdP 2 · Realm B', role: 'OIDC provider + WebAuthn relying party', plainRole: 'Checks the required factors and authenticates the person.', color: '#f472b6',
    attributes: [attr('issuerB', 'static'), attr('realmSigningKey', 'static'), attr('rpId', 'static'), attr('origin', 'static'), attr('userId', 'static'), attr('subjectB', 'static'), attr('userVerification', 'static'), attr('residentKey', 'static'), attr('challengeLogin', 'generated'), attr('challengeRegistration', 'generated'), attr('allowCredentials', 'generated'), attr('pubKeyCredParams', 'static'), attr('credentialId', 'received'), attr('credentialPublicKey', 'received'), attr('signature', 'received'), attr('codeB', 'generated'), attr('idTokenB', 'generated'), attr('accessTokenB', 'generated')],
    notes: ['Stores the registered public key and account binding.', 'This model starts with no SSO session, so a fresh passkey ceremony is visible.', 'Passkey assertions and OIDC tokens use different signing keys.'],
  },
  yubikey: {
    id: 'yubikey', name: 'YubiKey', role: 'Roaming FIDO2 authenticator', plainRole: 'A physical security key that protects and uses the passkey.', color: '#a3e635',
    attributes: [attr('privateKey', 'generated'), attr('credentialPublicKey', 'generated'), attr('credentialId', 'generated'), attr('rpId', 'received'), attr('userId', 'received'), attr('clientDataHash', 'received'), attr('rpIdHash', 'generated'), attr('flagsUP', 'generated'), attr('flagsUV', 'generated'), attr('signCount', 'generated'), attr('signature', 'generated'), attr('userHandle', 'generated')],
    notes: ['Example: a FIDO2-capable YubiKey with discoverable-credential support.', 'User verification uses the security-key PIN; a touch confirms presence.', 'Selected as an alternative to Windows Hello, not an additional required step.'],
  },
  hello: {
    id: 'hello', name: 'Windows Hello', role: 'Platform authenticator', plainRole: 'Uses the computer’s protected passkey with a local unlock.', color: '#fb923c',
    attributes: [attr('privateKey', 'generated'), attr('credentialPublicKey', 'generated'), attr('credentialId', 'generated'), attr('rpId', 'received'), attr('userId', 'received'), attr('clientDataHash', 'received'), attr('rpIdHash', 'generated'), attr('flagsUP', 'generated'), attr('flagsUV', 'generated'), attr('signCount', 'generated'), attr('signature', 'generated'), attr('userHandle', 'generated')],
    notes: ['User verification uses a supported Hello PIN or biometric gesture.', 'Include compatible signature algorithms in B’s policy; Keycloak’s guide mentions RS256.', 'Selected as an alternative to YubiKey.'],
  },
};

const payload = (name, value, description) => ({ name, value, ...(description ? { description } : {}) });
const tokenClaim = (name, value) => payload(name, value, 'A claim inside the decoded id_token, not a separate top-level token endpoint response field.');
const step = (id, title, from, to, phase, channel, summary, detail, fields, data, checks = []) => ({
  id, title, from, to, phase, channel, summary, detail, fields, payload: data, checks,
});

export const FLOWS = {
  login: [
    step('l01', 'Start sign-in', 'user', 'app', 'prepare', 'local',
      'The person clicks Sign in in the local application.',
      'This is a native desktop or CLI app. It will ask Realm A for an identity result through the system browser.',
      ['clientIdApp', 'redirectApp'], [payload('Local action', 'Sign in', 'A UI action, not an OAuth wire parameter.')]),
    step('l02', 'Prepare a protected request', 'app', 'app', 'prepare', 'internal',
      'The app opens its callback listener and creates one-time protections.',
      'The app binds 127.0.0.1:54321, generates independent state, nonce and code_verifier values, and computes the S256 code_challenge. The verifier stays in the app until the token exchange.',
      ['redirectApp', 'stateApp', 'nonceApp', 'codeVerifier', 'codeChallenge', 'codeChallengeMethod'],
      [payload('redirect_uri', EXAMPLE.appCallback), payload('state', EXAMPLE.stateApp), payload('nonce', EXAMPLE.nonceApp), payload('code_verifier', EXAMPLE.verifier, 'Retained locally; not placed in the browser URL.'), payload('code_challenge', EXAMPLE.challenge)]),
    step('l03', 'Open the system browser', 'app', 'browser', 'prepare', 'local',
      'The app asks the operating system to open A’s authorization URL.',
      'A separate browser keeps authentication pages and cookies outside the app. The opened URL contains the authorization request, but never the PKCE verifier.',
      ['clientIdApp', 'redirectApp', 'stateApp', 'nonceApp', 'codeChallenge', 'codeChallengeMethod', 'scope', 'responseType'],
      [payload('URL', EXAMPLE.authA), payload('client_id', EXAMPLE.clientApp), payload('redirect_uri', EXAMPLE.appCallback), payload('response_type', 'code'), payload('scope', 'openid profile'), payload('state', EXAMPLE.stateApp), payload('nonce', EXAMPLE.nonceApp), payload('code_challenge', EXAMPLE.challenge), payload('code_challenge_method', 'S256')]),
    step('l04', 'Ask Realm A for sign-in', 'browser', 'realmA', 'prepare', 'https',
      'The browser delivers the app’s authorization request to A.',
      'A validates the registered public client, allowed redirect URI, requested scopes and PKCE parameters, and creates an authentication session. The demo assumes a configured redirector chooses B.',
      ['clientIdApp', 'redirectApp', 'responseType', 'scope', 'stateApp', 'nonceApp', 'codeChallenge', 'codeChallengeMethod'],
      [payload('HTTP', 'GET authorization_endpoint A'), payload('client_id', EXAMPLE.clientApp), payload('redirect_uri', EXAMPLE.appCallback), payload('state', EXAMPLE.stateApp), payload('nonce', EXAMPLE.nonceApp), payload('code_challenge', EXAMPLE.challenge), payload('code_challenge_method', 'S256')],
      ['Known public client', 'Allowed loopback redirect', 'S256 PKCE present']),
    step('l05', 'Prepare a separate broker request', 'realmA', 'realmA', 'broker', 'internal',
      'A starts its own OIDC request to B.',
      'For this hop, A is the confidential client realm-a-broker. It creates its own state and nonce and uses its HTTPS broker callback. The app’s verifier and nonce are not forwarded as B’s values. Broker PKCE may also be configured; it is omitted on this confidential-client hop in the model.',
      ['clientIdBroker', 'redirectBroker', 'stateBroker', 'nonceBroker', 'clientSecret'],
      [payload('client_id', EXAMPLE.clientBroker), payload('redirect_uri', EXAMPLE.brokerCallback), payload('state', EXAMPLE.stateBroker), payload('nonce', EXAMPLE.nonceBroker)]),
    step('l06', 'Tell the browser to visit B', 'realmA', 'browser', 'broker', 'redirect',
      'A sends a redirect; the browser will carry the next request.',
      'The HTTP Location points to B’s authorization endpoint with A’s broker-client parameters. A has not called B’s login page itself.',
      ['location', 'clientIdBroker', 'redirectBroker', 'stateBroker', 'nonceBroker', 'scope', 'responseType'],
      [payload('HTTP', '302 Found'), payload('Location', EXAMPLE.authB), payload('client_id', EXAMPLE.clientBroker), payload('redirect_uri', EXAMPLE.brokerCallback), payload('response_type', 'code'), payload('scope', 'openid profile'), payload('state', EXAMPLE.stateBroker), payload('nonce', EXAMPLE.nonceBroker)]),
    step('l07', 'Open Realm B’s login page', 'browser', 'realmB', 'broker', 'https',
      'The browser follows the redirect to B.',
      'B validates the broker registration and callback and begins authentication. This example uses a previously enrolled discoverable passkey and requires local user verification.',
      ['clientIdBroker', 'redirectBroker', 'stateBroker', 'nonceBroker', 'session'],
      [payload('HTTP', 'GET authorization_endpoint B'), payload('client_id', EXAMPLE.clientBroker), payload('redirect_uri', EXAMPLE.brokerCallback), payload('state', EXAMPLE.stateBroker), payload('nonce', EXAMPLE.nonceBroker)]),
    step('l08', 'Send a fresh passkey challenge', 'realmB', 'browser', 'passkey', 'https',
      'B supplies the page and WebAuthn sign-in options.',
      'B creates a fresh random challenge tied to this authentication session. On B’s HTTPS page, the options become real byte arrays for navigator.credentials.get({publicKey: …}). An empty allowCredentials array enables account discovery.',
      ['challengeLogin', 'rpId', 'allowCredentials', 'userVerification', 'timeout'],
      [payload('challenge', EXAMPLE.loginChallenge + ' (bytes)'), payload('rpId', EXAMPLE.rpId), payload('allowCredentials', '[]'), payload('userVerification', 'required'), payload('timeout', '60000')]),
    step('l09', 'Ask the selected authenticator', 'browser', 'authenticator', 'passkey', 'webauthn',
      'The browser connects B’s page to the selected passkey device.',
      'The page invokes navigator.credentials.get(). The browser checks RP ID against the secure page origin, constructs clientDataJSON with type webauthn.get, and sends the authenticator the RP ID and clientDataHash through the platform’s authenticator interface.',
      ['origin', 'clientDataJSON', 'clientDataHash', 'clientDataType', 'rpId', 'crossOrigin', 'userVerification'],
      [payload('API', 'navigator.credentials.get({ publicKey: options })'), payload('rpId', EXAMPLE.rpId), payload('clientDataHash', 'SHA256(clientDataJSON bytes)'), payload('userVerification', 'required')]),
    step('l10', 'Approve locally', 'user', 'authenticator', 'passkey', 'local',
      'The person unlocks the selected authenticator.',
      'For YubiKey, this example uses a FIDO2 security-key PIN and touch. For Windows Hello, a supported PIN or biometric gesture verifies the person. No PIN or biometric sample is sent to Keycloak. The authenticator later reports successful presence and verification in signed flags.',
      ['localVerification', 'flagsUP', 'flagsUV'],
      [payload('Local operation', 'User verification + user presence'), payload('Server-bound secrets', 'None; PIN and biometric samples stay local')]),
    step('l11', 'Create the signed proof', 'authenticator', 'authenticator', 'passkey', 'internal',
      'The authenticator signs with the existing credential private key.',
      'It selects a credential for B’s RP ID and builds authenticatorData. The assertion signature covers authenticatorData concatenated with the SHA-256 hash of the exact clientDataJSON bytes. The private key stays protected in the authenticator.',
      ['privateKey', 'rpIdHash', 'flagsUP', 'flagsUV', 'signCount', 'authenticatorData', 'clientDataHash', 'signature'],
      [payload('authenticatorData', 'rpIdHash || flags || signCount || optional data'), payload('signature', 'Sign(privateKey, authenticatorData || clientDataHash)'), payload('privateKey', 'Never transmitted')]),
    step('l12', 'Return the authenticator response', 'authenticator', 'browser', 'passkey', 'webauthn',
      'The authenticator returns a signed assertion response.',
      'The platform/browser receives the credential ID, authenticatorData, signature and userHandle for the selected discoverable credential. The browser attaches its own clientDataJSON to produce the WebAuthn API result.',
      ['credentialId', 'authenticatorData', 'signature', 'userHandle'],
      [payload('rawId', 'credential-id-bytes'), payload('authenticatorData', 'Binary signed authenticator data'), payload('signature', 'Assertion signature bytes'), payload('userHandle', 'opaque-user-B-bytes')]),
    step('l13', 'Submit the assertion to B', 'browser', 'realmB', 'passkey', 'https',
      'B’s login page sends the WebAuthn result to B’s current login action.',
      'The browser serializes binary fields, typically as base64url, for the server. The exact Keycloak form/action transport is implementation-specific; the field names shown are the canonical WebAuthn response members.',
      ['credentialId', 'credentialType', 'clientDataJSON', 'authenticatorData', 'signature', 'userHandle'],
      [payload('id / rawId', 'Selected credential identifier'), payload('type', 'public-key'), payload('response.clientDataJSON', 'Base64url of original JSON bytes'), payload('response.authenticatorData', 'Base64url of authenticator data bytes'), payload('response.signature', 'Base64url of signature bytes'), payload('response.userHandle', 'Base64url of opaque-user-B-bytes')]),
    step('l14', 'Verify the passkey proof', 'realmB', 'realmB', 'passkey', 'internal',
      'B checks the challenge, website binding and public-key signature.',
      'B resolves the credential/account, verifies type, current challenge, permitted origin and RP ID hash, requires UP and UV, and verifies the signature using its stored credentialPublicKey. It evaluates signCount and any backup metadata according to credential properties. A successful check completes authentication in B.',
      ['challengeLogin', 'origin', 'rpIdHash', 'flagsUP', 'flagsUV', 'credentialPublicKey', 'signature', 'signCount'],
      [payload('Expected type', 'webauthn.get'), payload('Expected origin', EXAMPLE.origin), payload('Expected challenge', EXAMPLE.loginChallenge), payload('Signature check', 'Stored credentialPublicKey verifies the signed bytes')],
      ['Credential belongs to resolved B account', 'Challenge matches current attempt', 'Origin and RP ID hash allowed', 'UP = 1 and UV = 1', 'Signature valid']),
    step('l15', 'Issue B’s authorization code', 'realmB', 'browser', 'return', 'redirect',
      'B redirects the browser to A’s broker callback.',
      'B creates its SSO session and issues a single-use authorization code to its registered broker client. The browser receives code and the unchanged broker state, not an ID token or passkey private key.',
      ['location', 'codeB', 'stateBroker', 'redirectBroker', 'session'],
      [payload('HTTP', '302 Found'), payload('Location', EXAMPLE.brokerCallback + '?code=' + EXAMPLE.codeB + '&state=' + EXAMPLE.stateBroker)]),
    step('l16', 'Deliver B’s callback to A', 'browser', 'realmA', 'return', 'https',
      'The browser carries B’s code back to A.',
      'A validates broker state against its own pending session before accepting the callback. The code is only a ticket to redeem at B’s token endpoint.',
      ['codeB', 'stateBroker', 'redirectBroker'],
      [payload('HTTP', 'GET A broker callback'), payload('code', EXAMPLE.codeB), payload('state', EXAMPLE.stateBroker)], ['Broker state matches the pending request']),
    step('l17', 'Redeem B’s code server to server', 'realmA', 'realmB', 'tokens', 'backchannel',
      'A contacts B directly and authenticates as the broker client.',
      'This HTTPS POST is a backchannel call. A supplies the code and identical redirect_uri and authenticates with its broker client ID/secret using HTTP Basic. These credentials never pass through the browser.',
      ['grantType', 'codeB', 'redirectBroker', 'authorizationHeader', 'clientSecret'],
      [payload('HTTP', 'POST token_endpoint B'), payload('Authorization', 'Basic base64(realm-a-broker:broker-secret)'), payload('grant_type', 'authorization_code'), payload('code', EXAMPLE.codeB), payload('redirect_uri', EXAMPLE.brokerCallback)]),
    step('l18', 'Return B-issued tokens to A', 'realmB', 'realmA', 'tokens', 'backchannel',
      'B sends an identity token for A’s broker client.',
      'B validates the code and client and returns an ID token signed by B’s realm signing key, plus an access token. The ID token has issuer B, audience realm-a-broker and the broker nonce. The passkey private key does not sign this JWT.',
      ['idTokenB', 'accessTokenB', 'tokenType', 'expiresIn', 'issuerB', 'audience', 'subjectB', 'nonceBroker', 'realmSigningKey'],
      [payload('id_token', 'JWT signed by Realm B'), payload('access_token', 'B-issued access token'), payload('token_type', 'Bearer'), tokenClaim('iss', EXAMPLE.issuerB), tokenClaim('aud', EXAMPLE.clientBroker), tokenClaim('sub', 'user-in-B-913'), tokenClaim('nonce', EXAMPLE.nonceBroker)]),
    step('l19', 'Validate B’s identity and map the user', 'realmA', 'realmA', 'tokens', 'internal',
      'A validates the upstream result and resolves its own local user.',
      'A checks B’s token signature with B’s trusted public keys and validates issuer, audience, expiry and the request nonce. Broker policy links or imports the external identity to a local A account and creates A’s session. Extra first-broker-login actions can occur when policy requires them.',
      ['idTokenB', 'issuerB', 'audience', 'exp', 'nonceBroker', 'subjectB', 'subjectA', 'session'],
      [payload('External identity', '(iss B, sub user-in-B-913)'), payload('Local identity', '(iss A, sub user-in-A-204)'), payload('Passkey re-check in A', 'No; A trusts the validated OIDC result from B')],
      ['B signature and exact issuer valid', 'ID-token audience contains realm-a-broker', 'Expiry and nonce valid', 'Broker account-linking policy satisfied']),
    step('l20', 'Issue A’s authorization code', 'realmA', 'browser', 'return', 'redirect',
      'A redirects the browser to the local app’s callback.',
      'A issues a new code for desktop-app, bound to its original PKCE challenge. It returns the original app state. This is a separate code from the one B gave to A.',
      ['location', 'codeA', 'stateApp', 'redirectApp', 'codeChallenge'],
      [payload('HTTP', '302 Found'), payload('Location', EXAMPLE.appCallback + '?code=' + EXAMPLE.codeA + '&state=' + EXAMPLE.stateApp)]),
    step('l21', 'Reach the loopback listener', 'browser', 'app', 'return', 'local',
      'The browser calls the app on the same computer.',
      'The browser follows http://127.0.0.1:54321/callback and the app’s listener receives code and state. Keycloak does not need a network route to the user’s computer: the browser is making this local request.',
      ['redirectApp', 'codeA', 'stateApp'],
      [payload('HTTP', 'GET ' + EXAMPLE.appCallback), payload('code', EXAMPLE.codeA), payload('state', EXAMPLE.stateApp)]),
    step('l22', 'Check the local callback', 'app', 'app', 'return', 'internal',
      'The app accepts only the callback for its pending attempt.',
      'The app compares returned state with the locally stored value, checks the expected redirect context and rejects errors or unexpected responses. It still needs to redeem the code before it has a validated identity.',
      ['stateApp', 'codeA', 'redirectApp'],
      [payload('state comparison', EXAMPLE.stateApp + ' === stored state')], ['Callback belongs to the pending sign-in attempt']),
    step('l23', 'Redeem A’s code with PKCE', 'app', 'realmA', 'tokens', 'backchannel',
      'The app directly sends A the code and its secret verifier.',
      'The native public client posts to A’s HTTPS token endpoint with client_id, grant_type, code, the identical redirect_uri and code_verifier. It sends no client_secret. A recomputes S256 and compares it with the original challenge.',
      ['clientIdApp', 'grantType', 'codeA', 'redirectApp', 'codeVerifier', 'codeChallenge'],
      [payload('HTTP', 'POST token_endpoint A'), payload('client_id', EXAMPLE.clientApp), payload('grant_type', 'authorization_code'), payload('code', EXAMPLE.codeA), payload('redirect_uri', EXAMPLE.appCallback), payload('code_verifier', EXAMPLE.verifier)],
      ['Single-use code valid and unexpired', 'Code bound to this client and redirect', 'S256 verifier matches original challenge']),
    step('l24', 'Return A-issued tokens to the app', 'realmA', 'app', 'tokens', 'backchannel',
      'The app receives its tokens directly from A.',
      'A signs its own ID token for desktop-app and issues its own access token. An optional refresh token depends on A’s policy. B’s ID token and passkey assertion are not forwarded as the app’s login result.',
      ['idTokenA', 'accessTokenA', 'refreshToken', 'tokenType', 'expiresIn', 'issuerA', 'audience', 'subjectA', 'nonceApp'],
      [payload('id_token', 'JWT signed by Realm A'), payload('access_token', 'A-issued access token'), payload('refresh_token', 'Optional, policy-dependent'), payload('token_type', 'Bearer'), payload('expires_in', '300 (illustrative)'), tokenClaim('iss', EXAMPLE.issuerA), tokenClaim('aud', EXAMPLE.clientApp), tokenClaim('sub', 'user-in-A-204'), tokenClaim('nonce', EXAMPLE.nonceApp)]),
    step('l25', 'Validate identity and show signed-in state', 'app', 'user', 'complete', 'local',
      'The app validates A’s ID token and welcomes the person.',
      'The app uses A’s trusted discovered public keys and validates signature, exact issuer, audience, expiry and its own nonce, with any additional required OIDC checks. Its accepted identity is (iss A, sub user-in-A-204). An A token alone does not prove a fresh passkey ceremony unless agreed policy and claims establish that.',
      ['idTokenA', 'jwksUri', 'issuerA', 'audience', 'exp', 'iat', 'nonceApp', 'subjectA', 'acr', 'amr'],
      [payload('Validated identity', 'Realm A / user-in-A-204'), payload('Local UI', 'Signed in')],
      ['A signature and exact issuer valid', 'ID-token audience contains desktop-app', 'Expiry and original app nonce valid']),
  ],
  enrollment: [
    step('e01', 'Begin from a verified B account', 'user', 'browser', 'enrollment', 'local',
      'The person chooses to add a passkey in a verified Realm B session.',
      'Enrollment is a separate setup ceremony. B must already know which verified account owns the new credential; account recovery and initial verification are outside this diagram. In Keycloak, a configured WebAuthn Register Passwordless required action can initiate registration.',
      ['session', 'userId', 'userName'], [payload('Local action', 'Add passkey to verified B account')]),
    step('e02', 'Request registration options', 'browser', 'realmB', 'enrollment', 'https',
      'The browser requests enrollment for the verified account.',
      'B checks its account/session and enrollment authorization, then prepares the new credential policy. This step does not create an OAuth authorization code.',
      ['session', 'userId'], [payload('HTTPS action', 'Realm B enrollment action'), payload('Account', 'Verified user-in-B-913')], ['Account identity verified', 'Enrollment authorized']),
    step('e03', 'Send passkey creation options', 'realmB', 'browser', 'enrollment', 'https',
      'B sends a fresh challenge, account handle and credential policy.',
      'The options request a discoverable credential with required user verification and no identifying attestation. Algorithms ES256 (-7) and RS256 (-257) are offered in this example to support the illustrated authenticators. Actual policy must fit the selected devices.',
      ['challengeRegistration', 'rpObject', 'rpId', 'rpName', 'userObject', 'userId', 'userName', 'displayName', 'pubKeyCredParams', 'authenticatorSelection', 'residentKey', 'userVerification', 'attestation'],
      [payload('challenge', EXAMPLE.registrationChallenge + ' (bytes)'), payload('rp', '{ id: "idp2.example.test", name: "Keycloak Realm B" }'), payload('user', '{ id: opaque-user-B-bytes, name: "alice", displayName: "Alice" }'), payload('pubKeyCredParams', '[{type: "public-key", alg: -7}, {type: "public-key", alg: -257}]'), payload('authenticatorSelection', '{ residentKey: "required", userVerification: "required" }'), payload('attestation', 'none')]),
    step('e04', 'Ask the selected authenticator to create a passkey', 'browser', 'authenticator', 'enrollment', 'webauthn',
      'The browser calls navigator.credentials.create() on B’s page.',
      'The browser checks the secure origin and RP scope, builds clientDataJSON with type webauthn.create and hashes its exact bytes. The selected authenticator receives RP/account information, policy and clientDataHash through the local platform interface.',
      ['origin', 'clientDataJSON', 'clientDataType', 'clientDataHash', 'rpId', 'userId'],
      [payload('API', 'navigator.credentials.create({ publicKey: options })'), payload('rp.id', EXAMPLE.rpId), payload('user.id', 'opaque-user-B-bytes'), payload('clientDataHash', 'SHA256(clientDataJSON bytes)')]),
    step('e05', 'Approve creating the credential', 'user', 'authenticator', 'enrollment', 'local',
      'The person approves passkey creation using local verification.',
      'The selected YubiKey or Windows Hello performs its supported local user verification and presence interaction. The PIN or biometric sample is not delivered to the Keycloak realms.',
      ['localVerification', 'flagsUP', 'flagsUV'], [payload('Local operation', 'Approve creating a new passkey')]),
    step('e06', 'Create keys and return registration data', 'authenticator', 'browser', 'enrollment', 'webauthn',
      'The authenticator creates a protected private key and matching public key.',
      'The credential source records the private key, RP ID and account handle. The registration response exposes the credential ID and public-key data, not the private key. The browser returns clientDataJSON plus attestationObject to the page; with none attestation, the object uses fmt none and an empty attStmt.',
      ['privateKey', 'credentialPublicKey', 'credentialId', 'attestationObject', 'clientDataJSON', 'rpId', 'userId'],
      [payload('rawId', 'New credential-id-bytes'), payload('response.attestationObject', 'CBOR registration data includes credentialPublicKey', 'The browser applies the requested none-attestation privacy policy to the final WebAuthn response.')]),
    step('e07', 'Submit registration to B', 'browser', 'realmB', 'enrollment', 'https',
      'The browser sends the creation result back to B.',
      'B verifies the registration challenge, expected webauthn.create type, origin, RP ID hash, required flags and algorithm/attestation policy. The payload names represent canonical WebAuthn response members; Keycloak’s login-action form encoding is implementation-specific.',
      ['credentialId', 'credentialType', 'clientDataJSON', 'attestationObject', 'challengeRegistration', 'origin', 'rpIdHash'],
      [payload('id / rawId', 'New credential identifier'), payload('type', 'public-key'), payload('response.clientDataJSON', 'Original browser context bytes'), payload('response.attestationObject', 'CBOR registration response')],
      ['Challenge and webauthn.create type match', 'Origin and RP ID binding valid', 'Required UP and UV flags present', 'Algorithm and attestation policy satisfied']),
    step('e08', 'Save the public key and account binding', 'realmB', 'browser', 'enrollment', 'https',
      'B stores the public key for this verified account and confirms enrollment.',
      'B persists the credential ID, credentialPublicKey, account association and relevant counter/credential metadata. Later sign-in uses this public key to verify signatures. A does not receive or store the private key as part of brokering.',
      ['credentialId', 'credentialPublicKey', 'userId', 'signCount'],
      [payload('HTTPS result', 'Passkey registered')]),
  ],
};

export const SOURCES = [
  { name: 'OAuth 2.0 authorization code', standard: 'RFC 6749', url: URLS.oauth, note: 'client_id, redirect_uri, state, code and token exchange.' },
  { name: 'PKCE', standard: 'RFC 7636', url: URLS.pkce, note: 'code_verifier, code_challenge and S256.' },
  { name: 'OAuth for native apps', standard: 'RFC 8252', url: URLS.native, note: 'External browser, loopback callback and public native-client model.' },
  { name: 'OpenID Connect Core', standard: 'OIDC 1.0', url: URLS.oidc, note: 'nonce, ID token and identity validation.' },
  { name: 'OpenID Connect Discovery', standard: 'OIDC Discovery 1.0', url: URLS.discovery, note: 'authorization_endpoint, token_endpoint and jwks_uri.' },
  { name: 'JSON Web Token', standard: 'RFC 7519', url: URLS.jwt, note: 'iss, aud, sub, exp and iat claims.' },
  { name: 'Web Authentication', standard: 'W3C WebAuthn Level 3', url: URLS.webauthn, note: 'Credential creation, assertions, RP ID, origin and signature verification.' },
  { name: 'Keycloak administration guide', standard: 'Keycloak latest', url: URLS.keycloak, note: 'Identity brokering, WebAuthn Passwordless Policy and passkey setup.' },
];

export const LEARNING_NOTES = [
  { title: 'Two OIDC hops, one passkey ceremony', text: 'App ↔ A and broker A ↔ B have different clients, callbacks, states, nonces, codes and tokens. The passkey ceremony takes place only on B’s login page.' },
  { title: 'One authenticator per attempt', text: 'Select YubiKey or Windows Hello. They are alternative ways to produce the same kind of WebAuthn proof.' },
  { title: 'Four different protections', text: 'state matches callbacks; nonce binds ID tokens; PKCE binds code redemption to the app; the WebAuthn challenge makes the passkey proof fresh.' },
  { title: 'The browser calls localhost', text: 'A redirects the browser to the loopback address. The browser calls the local listener; the Keycloak server does not connect to your computer.' },
  { title: 'Passkey keys and realm keys differ', text: 'The authenticator signs WebAuthn proof with the credential private key. B and A sign their own OIDC tokens with separate realm signing keys.' },
  { title: 'Same hostname does not merge realms', text: 'If A and B use one hostname, their WebAuthn RP scope may be the same because URL paths do not define RP IDs. B’s registered credential/public-key account binding is still not automatically registered in A.' },
  { title: 'Sessions can shorten real sign-in', text: 'An existing A or B SSO session can skip parts of this fresh-login demonstration. Enabling passkeys does not itself force every login to use them.' },
  { title: 'A token is not automatic passkey evidence', text: 'If an application needs proof of a fresh passkey login, enforce and validate an agreed authentication policy. acr and amr require explicit semantics and broker handling.' },
  { title: 'Canonical names, symbolic values', text: 'Protocol/API names follow IETF, OpenID and W3C specifications. Values in this simulator are illustrative; fields labelled Local operation or Stored in B describe actions, not wire parameters.' },
];

// MFA teaching extension. A TOTP app is a separate symmetric-key actor, not a
// WebAuthn authenticator. Password and OTP form fields below are application
// fields in Keycloak's login action, not RFC-defined OAuth request parameters.
const TOTP_RFC = 'https://www.rfc-editor.org/rfc/rfc6238';
const HOTP_RFC = 'https://www.rfc-editor.org/rfc/rfc4226';
const KEY_URI = 'https://github.com/google/google-authenticator/wiki/Key-Uri-Format';
const OTP_FORM = 'https://github.com/keycloak/keycloak/blob/main/themes/src/main/resources/theme/base/login/login-otp.ftl';
const DEMO_SEED = 'GEZDGNBVGY3TQOJQGEZDGNBVGY3TQOJQ'; // RFC's public test key; not a real secret.
const DEMO_OTP = '287082'; // RFC 6238 SHA1 vector at Unix time 59, reduced to six digits.
const DEMO_URI = 'otpauth://totp/Realm%20B:alice?secret=' + DEMO_SEED + '&issuer=Realm%20B&algorithm=SHA1&digits=6&period=30';

Object.assign(ATTRIBUTES, {
  password: attribute('password (login form field)', 'The account password submitted to B’s login action.', 'Chosen by the person or provisioned through the account’s password setup.', 'Provides the knowledge factor in this password-plus-TOTP example. It is not a client_secret or an OAuth password grant.', 'Password submitted to B over HTTPS; value hidden', 'Keycloak browser authentication (not an OAuth parameter)', URLS.keycloak),
  passwordHash: attribute('password hash (stored credential)', 'B’s protected password-verification record, with algorithm and salt metadata.', 'Created by B’s configured password hashing provider during account password setup.', 'Lets B verify the submitted password without storing it as plaintext. This record is not sent to the browser.', 'Salted password hash; provider and cost are configuration-dependent', 'Keycloak password policies and providers', URLS.keycloak),
  otpCode: attribute('otp (TOTP login form field)', 'The short numeric code the person types into B’s OTP form.', 'The TOTP app computes it locally from shared secret K and the current time-step counter.', 'B recomputes candidate codes to check possession of the enrolled TOTP secret. The form name is implementation-specific, not an OAuth/OIDC parameter.', DEMO_OTP + ' (public RFC test example at Unix time 59)', 'RFC 6238 algorithm / Keycloak OTP form', TOTP_RFC),
  otpSecret: attribute('K / secret', 'The per-credential symmetric secret shared by B and the TOTP app.', 'B generates a random secret during this enrollment example and provisions it once to the app.', 'Both parties need the same secret to calculate matching codes. Unlike a passkey private key, this secret is held by the server too.', DEMO_SEED + ' (public RFC test seed only)', 'RFC 6238 §3 / RFC 4226 §5.1', TOTP_RFC),
  otpAlgorithm: attribute('algorithm (provisioning setting)', 'The HMAC hash algorithm used to calculate the OTP.', 'B selects it in the OTP policy and provisions the same choice to the app.', 'Keeps the client and server’s code calculations consistent.', 'SHA1 in this example; RFC 6238 also specifies SHA256 and SHA512 variants', 'RFC 6238 / de facto otpauth URI', TOTP_RFC),
  otpDigits: attribute('Digit / digits', 'The number of decimal digits in the displayed OTP.', 'B’s OTP policy and the authenticator app agree during enrollment.', 'Both sides truncate and format the code to the same length, including leading zeros.', '6 in this example', 'RFC 4226 §5.3 / de facto otpauth URI', HOTP_RFC),
  otpPeriod: attribute('X / period', 'The length of one time step, in seconds.', 'Set by B’s OTP policy and provisioned to the app.', 'Determines when the time-step counter, and therefore the displayed code, changes.', '30 seconds', 'RFC 6238 §4.1 / de facto otpauth URI', TOTP_RFC),
  otpT0: attribute('T0', 'The starting Unix time used to count TOTP time steps.', 'Agreed as a TOTP system parameter; commonly zero.', 'Provides the same time origin for the app and server.', '0 (Unix epoch)', 'RFC 6238 §4.1', TOTP_RFC),
  otpTime: attribute('Current Unix time', 'The current time in seconds since the Unix epoch.', 'Read independently from the authenticator device’s clock and B’s server clock.', 'Each side derives a time-step counter; clock drift may require a small configured acceptance window.', '59 seconds in the fixed RFC example', 'RFC 6238 §3 / §4.2', TOTP_RFC),
  otpCounter: attribute('T (time-step counter)', 'The integer time-based moving factor for the HOTP calculation.', 'Each side computes floor((Current Unix time − T0) / X).', 'TOTP = HOTP(K, T), using the shared K and this moving factor. It is not a WebAuthn challenge.', 'floor((59 − 0) / 30) = 1', 'RFC 6238 §4.2', TOTP_RFC),
  otpUri: attribute('otpauth URI (de facto provisioning format)', 'An enrollment URI carrying the secret, label and matching OTP settings.', 'B formats a provisioning URI and renders it as a QR code.', 'The authenticator app scans the QR code to configure the shared secret. This URI format is not defined by RFC 6238.', DEMO_URI, 'Google Authenticator Key URI Format; de facto convention', KEY_URI),
  otpWindow: attribute('TOTP validation window (policy)', 'The limited set of nearby time steps that B may check.', 'Configured by the realm’s OTP policy, with clocks and permitted drift in mind.', 'Allows small clock/timing differences while limiting how long a stolen code may be useful. A 30-second display period is not necessarily a 30-second acceptance window.', 'Keycloak default look-around 1: previous/current/next 30s steps; configurable', 'RFC 6238 §5.2 / §6 and Keycloak OTP policy', TOTP_RFC),
  otpReplay: attribute('Accepted time-step / replay state (server policy)', 'Server state recording which OTP time step has already succeeded.', 'Updated by the verifier after successful validation; implementation details vary.', 'A one-time verifier rejects a second successful use of the same OTP. In current Keycloak, Reusable code is disabled by default; enabling it changes this protection.', 'Reusable code disabled; previously successful time-step rejected', 'RFC 6238 §5.2 and Keycloak OTP policy', TOTP_RFC),
});

ACTORS.totp = {
  id: 'totp', name: 'Authenticator app', role: 'TOTP prover / possession factor',
  plainRole: 'Stores a shared secret and shows a changing numeric code.', color: '#2dd4bf',
  attributes: [attr('otpSecret', 'received'), attr('otpAlgorithm', 'static'), attr('otpDigits', 'static'), attr('otpPeriod', 'static'), attr('otpT0', 'static'), attr('otpTime', 'generated'), attr('otpCounter', 'generated'), attr('otpCode', 'generated'), attr('otpUri', 'received')],
  notes: ['Creates TOTP codes offline from the shared secret and local time.', 'The secret exists both in this app and in B’s verifier.', 'The code can be copied or phished; it is not cryptographically bound to B’s website origin.'],
};
ACTORS.user.attributes.push(attr('password', 'static'), attr('otpCode', 'received'));
ACTORS.browser.attributes.push(attr('password', 'received'), attr('otpCode', 'received'), attr('otpUri', 'received'));
ACTORS.realmB.attributes.push(attr('passwordHash', 'static'), attr('password', 'received'), attr('otpSecret', 'generated'), attr('otpAlgorithm', 'static'), attr('otpPeriod', 'static'), attr('otpDigits', 'static'), attr('otpCounter', 'generated'), attr('otpCode', 'received'), attr('otpWindow', 'static'), attr('otpReplay', 'generated'));
ACTORS.realmB.attributes.push(attr('rpObject', 'generated'), attr('userObject', 'generated'), attr('authenticatorSelection', 'static'));
ACTORS.browser.attributes.push(attr('rpObject', 'received'), attr('userObject', 'received'), attr('authenticatorSelection', 'received'));

const otpSteps = [
  step('m01', 'Request the second factor', 'realmB', 'browser', 'mfa', 'https',
    'B asks for a current code from the enrolled TOTP app.',
    'B keeps the sign-in pending until its required OTP execution succeeds. This OTP form belongs to B’s current browser authentication session, before B creates the broker authorization code. Requiring TOTP after a passkey needs an explicitly configured B flow; it is not implied by enabling passkeys.',
    ['session', 'otpCode', 'otpWindow'], [payload('HTTPS response', 'Realm B OTP input form'), payload('Required input', 'Current TOTP code')]),
  step('m02', 'Calculate and display a TOTP code', 'totp', 'user', 'mfa', 'local',
    'The authenticator app shows a code computed from its secret and clock.',
    'The app needs no live call to Keycloak. It computes T = floor((Current Unix time − T0) / X), then TOTP = HOTP(K, T) using the agreed HMAC algorithm, truncation and digit count. The fixed teaching example uses the public RFC test key, SHA1, six digits and Unix time 59; it is not a usable enrollment secret.',
    ['otpSecret', 'otpTime', 'otpT0', 'otpPeriod', 'otpCounter', 'otpAlgorithm', 'otpDigits', 'otpCode'],
    [payload('TOTP', DEMO_OTP + ' (fixed public test example)')]),
  step('m03', 'Type the code into B’s page', 'user', 'browser', 'mfa', 'local',
    'The person copies the displayed six-digit code into the login form.',
    'This is a human-mediated code transfer. Unlike WebAuthn, the typed TOTP code has no signed origin or RP ID binding. The same code can be relayed by a phishing site during its acceptance window.',
    ['otpCode'], [payload('otp', DEMO_OTP, 'Keycloak login-form field, not an OAuth parameter.')]),
  step('m04', 'Submit the OTP to Realm B', 'browser', 'realmB', 'mfa', 'https',
    'The browser posts the OTP to B over HTTPS.',
    'The code is bound to the current pending login action by B’s authentication session. The TOTP secret is not sent again on login, and this code is not sent to A or the native application.',
    ['otpCode', 'session'], [payload('HTTP', 'POST current Realm B login action'), payload('otp', DEMO_OTP)]),
  step('m05', 'Validate the time-based second factor', 'realmB', 'realmB', 'mfa', 'internal',
    'B checks the code against its stored secret and allowed time steps.',
    'B derives candidates from the same K, HMAC algorithm, time step and digits, applies its limited clock-drift window, and enforces configured attempt protection and one-time-use policy. Only after the required factors succeed does B proceed to the normal OIDC code response.',
    ['otpSecret', 'otpAlgorithm', 'otpDigits', 'otpPeriod', 'otpT0', 'otpCounter', 'otpWindow', 'otpReplay', 'otpCode'],
    [payload('Expected code', 'HOTP(K, T) for permitted time steps'), payload('Submitted otp', DEMO_OTP), payload('Outcome', 'Required B factors satisfied')],
    ['Enrolled OTP credential belongs to this B account', 'Code matches a permitted time step', 'Attempt-limit policy satisfied', 'Previously successful OTP rejected by replay policy']),
];

const passwordSteps = [
  step('p01', 'Show the password form', 'realmB', 'browser', 'password', 'https',
    'B asks the person for the account password.',
    'This alternative uses a browser password form followed by TOTP in Realm B. It still uses the authorization code flow between the app and A and between A and B; it does not use OAuth’s resource-owner password grant.',
    ['password', 'session'], [payload('HTTPS response', 'Realm B username/password form')]),
  step('p02', 'Enter account credentials', 'user', 'browser', 'password', 'local',
    'The person enters a username and password on B’s page.',
    'The knowledge factor is the B account password. The native app and Realm A do not receive that password in this brokered browser login.',
    ['userName', 'password'], [payload('username', 'alice', 'Keycloak form field; not an OAuth parameter.'), payload('password', '••••••••')]),
  step('p03', 'Submit the password to B', 'browser', 'realmB', 'password', 'https',
    'The browser sends the account credentials directly to B over HTTPS.',
    'B checks the username and password using the configured credential provider. A successful password check completes the knowledge factor but the sign-in stays pending until the required TOTP factor succeeds.',
    ['userName', 'password', 'passwordHash', 'session'],
    [payload('HTTP', 'POST current Realm B login action'), payload('username', 'alice'), payload('password', 'Hidden; TLS-protected request')],
    ['Account resolved in B', 'Password verified using B’s protected credential record']),
];

// Clone shared steps so mode-specific text never falsely describes passkeys.
// Key lookup and audience belong to this token occurrence, not the generic
// glossary example. Preserve both through factor/deployment/JWE adapters.
FLOWS.login.find(s => s.id === 'l18').attributeValues = {
  audience: EXAMPLE.clientBroker,
};
FLOWS.login.find(s => s.id === 'l19').attributeValues = {
  jwksUri: EXAMPLE.issuerB + '/protocol/openid-connect/certs',
  audience: EXAMPLE.clientBroker,
};
FLOWS.login.find(s => s.id === 'l24').attributeValues = {
  audience: EXAMPLE.clientApp,
};
FLOWS.login.find(s => s.id === 'l25').attributeValues = {
  jwksUri: EXAMPLE.issuerA + '/protocol/openid-connect/certs',
  audience: EXAMPLE.clientApp,
};

const rename = (s, prefix) => ({ ...s, id: prefix + '-' + s.id, fields: [...s.fields], payload: s.payload.map(p => ({ ...p })), checks: [...s.checks] });
const totpStart = FLOWS.login.slice(0, 7).map(s => rename(s, 'totp'));
totpStart[6].detail = 'B validates the broker registration and callback, then starts its configured browser flow. This mode uses the account password followed by an enrolled TOTP factor.';
const totpReturn = FLOWS.login.slice(14).map(s => rename(s, 'totp'));
totpReturn[3].summary = 'B sends an identity token for A’s broker client after the required factors succeed.';
totpReturn[3].detail = 'B validates the code and client and returns its realm-signed ID token plus an access token. The ID token has issuer B, audience realm-a-broker and the broker nonce. TOTP secrets and codes are not included as the broker identity result.';
totpReturn[9].detail = 'A signs its own ID token for desktop-app and issues its own access token. An optional refresh token depends on A’s policy. B’s ID token, password and OTP code are not forwarded as the app’s login result.';
totpReturn[10].detail = 'The app uses A’s trusted discovered public keys and validates signature, exact issuer, audience, expiry and its original nonce, with any additional required OIDC checks. Its accepted identity is (iss A, sub user-in-A-204). If it must enforce a specific MFA level, it needs an agreed authentication policy and validated claim semantics.';
FLOWS.totpLogin = [...totpStart, ...passwordSteps, ...otpSteps, ...totpReturn];
FLOWS.passkeyTotpLogin = [
  ...FLOWS.login.slice(0, 14).map(s => rename(s, 'passkey-mfa')),
  ...otpSteps.map(s => rename(s, 'passkey')),
  ...FLOWS.login.slice(14).map(s => rename(s, 'passkey-mfa')),
];
FLOWS.passkeyTotpLogin[13].summary = 'B validates the passkey step; required TOTP is still pending.';
FLOWS.passkeyTotpLogin[13].detail = 'B resolves the credential/account, verifies type, current challenge, permitted origin and RP ID hash, requires UP and UV, and verifies the signature using its stored credentialPublicKey. It evaluates signCount and relevant credential metadata. This completes only the passkey step: B keeps authentication pending until its separately configured required TOTP execution succeeds.';
FLOWS.passkeyTotpLogin[14].summary = 'After validating the passkey, B still requires a separate TOTP factor.';
FLOWS.passkeyTotpLogin[14].detail = 'This mode illustrates a custom B browser authentication flow with a required OTP execution after passkey verification. It is not the default consequence of enabling passkeys; real deployments must configure and test the requirement and avoid session/fallback paths bypassing it.';

FLOWS.totpEnrollment = [
  step('t01', 'Begin from a verified B account', 'user', 'browser', 'enrollment', 'local',
    'The person chooses to add an authenticator app to a verified B account.',
    'TOTP setup is a separate enrollment ceremony. B must already know and verify the account identity before binding a new possession factor. The QR image carries a secret, so real setup pages must protect it.',
    ['session', 'otpSecret'], [payload('Local action', 'Configure OTP for verified B account')]),
  step('t02', 'Authorize TOTP setup', 'browser', 'realmB', 'enrollment', 'https',
    'The browser requests setup in the verified B session.',
    'B checks authorization for adding this credential and selects OTP settings from the realm’s OTP policy. Keycloak can initiate this using the Configure OTP required action.',
    ['session', 'otpAlgorithm', 'otpDigits', 'otpPeriod'], [payload('HTTPS action', 'Configure OTP for verified user-in-B-913')], ['Verified account and session', 'Credential enrollment authorized']),
  step('t03', 'Generate the shared secret and QR', 'realmB', 'browser', 'enrollment', 'https',
    'B creates a new per-credential secret and shows the provisioning QR.',
    'B generates a high-entropy secret K and creates a de facto otpauth URI with matching algorithm, digits and period. The QR contains this secret; it is not a public-key registration response. The shown seed is a publicly documented RFC test seed for illustration only.',
    ['otpSecret', 'otpUri', 'otpAlgorithm', 'otpDigits', 'otpPeriod', 'otpT0'],
    [payload('Provisioning URI (de facto)', DEMO_URI), payload('secret', DEMO_SEED + ' (public test seed only)'), payload('algorithm', 'SHA1'), payload('digits', '6'), payload('period', '30')]),
  step('t04', 'Scan the provisioning QR', 'browser', 'totp', 'enrollment', 'local',
    'The authenticator app scans the QR shown on the browser’s setup page.',
    'The person initiates the scan. The app decodes the secret and settings, stores them securely and can now generate codes offline. This is an intentional one-time transfer of a shared symmetric secret, unlike passkey enrollment where the private key never goes to the server.',
    ['otpUri', 'otpSecret', 'otpAlgorithm', 'otpDigits', 'otpPeriod'],
    [payload('Optical/local provisioning', 'QR encodes otpauth URI'), payload('Provisioned settings', 'Secret K + algorithm + digits + period')]),
  step('t05', 'Generate a confirmation code', 'totp', 'user', 'enrollment', 'local',
    'The app shows its first time-based code for this enrollment.',
    'The app calculates TOTP from the newly provisioned secret and its local clock. The person will submit a current code so B can confirm that the app and server agree on the secret and settings.',
    ['otpSecret', 'otpTime', 'otpCounter', 'otpCode'], [payload('TOTP', DEMO_OTP + ' (fixed RFC example at Unix time 59)')]),
  step('t06', 'Enter the confirmation code', 'user', 'browser', 'enrollment', 'local',
    'The person types the displayed code into B’s setup form.',
    'This confirms possession of the configured app. The field label below describes the enrollment code; the exact Keycloak setup form field name is implementation-specific.',
    ['otpCode'], [payload('Enrollment OTP input (form-specific)', DEMO_OTP)]),
  step('t07', 'Validate and activate the credential', 'browser', 'realmB', 'enrollment', 'https',
    'B checks the confirmation code before binding this TOTP credential.',
    'B validates the current code against the pending secret and settings, checks the authorized setup session, and persists the account’s OTP credential according to its enrollment policy. B retains the symmetric secret, not just a public verification key.',
    ['otpCode', 'otpSecret', 'otpWindow', 'otpReplay', 'session'],
    [payload('HTTPS action', 'Submit setup confirmation'), payload('OTP input', DEMO_OTP)],
    ['Setup still authorized', 'Code and current time window match', 'TOTP credential bound to the verified account']),
  step('t08', 'Confirm TOTP enrollment', 'realmB', 'browser', 'enrollment', 'https',
    'B confirms that the account can now use the TOTP app.',
    'The shared secret is held both by B’s verifier and the enrolled app. Later login submits only the short OTP code. Realm A and the native application do not receive the TOTP seed or the typed OTP through ordinary brokering.',
    ['otpSecret', 'otpAlgorithm', 'otpDigits', 'otpPeriod'],
    [payload('HTTPS result', 'Authenticator app registered')]),
];

SOURCES.push(
  { name: 'Time-based one-time passwords', standard: 'RFC 6238', url: TOTP_RFC, note: 'Shared-secret TOTP calculation, time windows and one-time-use requirement.' },
  { name: 'HMAC-based one-time passwords', standard: 'RFC 4226', url: HOTP_RFC, note: 'HOTP calculation, dynamic truncation and decimal code formatting.' },
  { name: 'Authenticator provisioning URI', standard: 'De facto convention; not an RFC wire format', url: KEY_URI, note: 'otpauth URI and QR enrollment parameters.' },
  { name: 'Keycloak OTP login form', standard: 'Implementation-specific form', url: OTP_FORM, note: 'The OTP input is a browser login form field, not an OAuth/OIDC parameter.' },
);
LEARNING_NOTES.push(
  { title: 'MFA happens where the factors are checked', text: 'In these modes, B verifies the password/passkey and TOTP. A trusts the OIDC result and issues app tokens. Requiring a factor at A would be another explicitly configured authentication step.' },
  { title: 'Passkey plus TOTP is an explicit flow', text: 'The simulator can require TOTP after passkey verification. Keycloak needs a custom flow and consistent session/fallback policy to enforce that requirement.' },
  { title: 'TOTP shares a secret; passkeys use asymmetric keys', text: 'B and the TOTP app both store secret K. With a passkey, B stores the public key and the authenticator protects the private key.' },
  { title: 'TOTP codes can be phished', text: 'A typed code is not signed for a particular website origin. Use narrow time windows, attempt limits and replay protection; origin binding is a distinct advantage of correctly configured WebAuthn.' },
);
