import { ACTORS, ATTRIBUTES, EXAMPLE } from './protocol-data.js';
import { JOURNEYS, VARIANT_ATTRIBUTES, getJourneySteps, getActorOverrides, getAttributeOverrides } from './architecture-variants.js';
import { applyFidoTransport } from './fido-direct.js';

// An educational protocol model, not an XML parser or authentication library.
// Signatures, encrypted bytes and certificates below are symbolic examples.
const samlCoreUrl='https://docs.oasis-open.org/security/saml/v2.0/saml-core-2.0-os.pdf';
const samlBindingsUrl='https://docs.oasis-open.org/security/saml/v2.0/saml-bindings-2.0-os.pdf';
const samlProfilesUrl='https://docs.oasis-open.org/security/saml/v2.0/saml-profiles-2.0-os.pdf';
const samlXmlEncUrl='https://www.w3.org/TR/xmlenc-core1/';
const samlPostBinding='urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST';
const samlRsaSha256='http://www.w3.org/2001/04/xmldsig-more#rsa-sha256';
const samlClock='2026-10-07T12:00:00Z';
const samlUntil='2026-10-07T12:05:00Z';
const samlAttr=(name,meaning,origin,purpose,example,standard='SAML 2.0 Core',source=samlCoreUrl)=>({name,meaning,description:meaning,origin,generator:origin,purpose,example,standard,source});

export const SAML_ATTRIBUTES={
  samlAuthnRequest:samlAttr('AuthnRequest','The XML message asking an IdP to authenticate for a service provider.','Created by the requesting SP for SP-initiated sign-in.','Carries the SP issuer, request ID, allowed ACS and requested response binding.','<samlp:AuthnRequest …><saml:Issuer>SP entityID</saml:Issuer></samlp:AuthnRequest>'),
  samlRequest:samlAttr('SAMLRequest','The HTTP binding field carrying encoded AuthnRequest XML.','Derived by the SP/client binding implementation.','Redirect uses raw DEFLATE, Base64 and URL encoding; POST uses Base64 XML in a form control.','Encoded AuthnRequest; symbolic bytes','SAML 2.0 Bindings §3.4 / §3.5',samlBindingsUrl),
  samlResponseXml:samlAttr('Response','The XML protocol response containing status and assertion material.','Created by the IdP after its configured authentication succeeds.','Delivers a signed identity result to the registered ACS.','<samlp:Response …>Assertion or EncryptedAssertion</samlp:Response>'),
  samlResponse:samlAttr('SAMLResponse','The HTTP-POST form control carrying Base64 Response XML.','The IdP’s binding implementation encodes the response.','The browser posts it to the SP ACS; this model always uses POST responses.','BASE64(Response XML)','SAML 2.0 HTTP-POST binding',samlBindingsUrl),
  samlAssertion:samlAttr('Assertion','An XML identity/authentication statement issued for a particular recipient.','Created and signed by the IdP under configured policy.','Carries the subject, audience, confirmation, times and authentication context.','Signed Assertion XML'),
  samlProtocolBinding:samlAttr('ProtocolBinding','The response binding requested in an AuthnRequest.','Chosen by the SP and validated against registration.','This request asks the IdP to return the response using HTTP-POST.',samlPostBinding),
  samlIssueInstant:samlAttr('IssueInstant','The XML date/time when a request, response or assertion is issued.','Set by its sender using the sender’s clock.','Supports freshness policy; it is distinct from Conditions validity bounds.',samlClock),
  samlRequestDestination:samlAttr('Destination (AuthnRequest)','The intended IdP SSO endpoint on a signed authentication request.','Taken from trusted IdP configuration or metadata.','The IdP checks that the request targets its expected endpoint.','IdP SSO endpoint'),
  samlResponseDestination:samlAttr('Destination (Response)','The intended ACS URL of the SAML response.','Resolved from the registered SP configuration.','The SP checks the signed response was addressed to its actual ACS.','Registered SP ACS URL'),
  samlStatusCode:samlAttr('StatusCode','The protocol outcome in the response Status element.','Set by the IdP.','A successful assertion must accompany an accepted success result.','urn:oasis:names:tc:SAML:2.0:status:Success'),
  samlNameIdFormat:samlAttr('NameID/@Format','The interpretation/format of the returned subject identifier.','Agreed in SP/IdP configuration and emitted by the IdP.','This example configures a persistent identifier; its value need not equal an OIDC sub.','urn:oasis:names:tc:SAML:2.0:nameid-format:persistent'),
  samlNotBefore:samlAttr('Conditions/@NotBefore','The earliest allowed time for the assertion Conditions.','Set by the IdP; verifier allows only configured clock skew.','The SP must not accept the assertion before this bound. This is not a bearer SubjectConfirmationData attribute.',samlClock),
  samlNotOnOrAfter:samlAttr('Conditions/@NotOnOrAfter','The exclusive expiry bound for assertion Conditions.','Set by the IdP.','The SP rejects an assertion at or after the bound, subject to limited configured clock skew.',samlUntil),
  samlSubjectExpiry:samlAttr('SubjectConfirmationData/@NotOnOrAfter','The exclusive expiry for bearer subject confirmation.','Set by the IdP on bearer confirmation.','The browser SSO bearer confirmation needs this expiry and must not contain NotBefore.',samlUntil,'SAML 2.0 Profiles §4.1.4',samlProfilesUrl),
  samlAuthnInstant:samlAttr('AuthnInstant','When the subject’s represented authentication occurred.','Set by the IdP according to the authenticated session/method.','Describes authentication time; existing SSO may be older than the response.',samlClock),
  samlSigAlg:samlAttr('SigAlg','The Redirect binding’s detached-signature algorithm URI.','Chosen from allowed configured signing algorithms.','Identifies the algorithm and is included in the exact signed query string.',samlRsaSha256,'SAML 2.0 Bindings §3.4.4.1',samlBindingsUrl),
  samlRedirectSignature:samlAttr('Signature (Redirect query)','The detached signature over the original URL-encoded binding parameters.','The SP signs SAMLRequest[&RelayState]&SigAlg in that exact order.','The IdP verifies those exact encoded values using its trusted SP signing key.','URL_ENCODE(BASE64(signature bytes))','SAML 2.0 Bindings §3.4.4.1',samlBindingsUrl),
  samlXmlSignature:samlAttr('ds:Signature','An enveloped XML signature on an AuthnRequest, Response or Assertion.','Created with the sender’s configured private signing key.','Protects the signed XML element. Validate the referenced element and use trusted metadata keys; the separate POST RelayState field is not covered.','XML Signature: configured canonicalization, digest and RSA-SHA256','XML Signature / SAML 2.0', 'https://www.w3.org/TR/xmldsig-core1/'),
  samlReplayState:samlAttr('Assertion ID replay cache (SP policy)','Server-side state recording accepted assertion IDs until their validity expires.','Updated by the recipient after successful acceptance.','Rejects a reused assertion; it is an implementation policy, not a SAML wire field.','Remember accepted Assertion.ID through its validity window','SAML 2.0 browser SSO profile',samlProfilesUrl),
  samlUnsolicitedPolicy:samlAttr('Unsolicited Response policy (SP)','The SP’s explicit permission and safeguards for IdP-initiated sign-in.','Configured by the SP administrator.','Accepts a response without a pending AuthnRequest only when allowed. Request correlation is absent; evaluate login-CSRF and account-switching risks.','Explicitly enabled; no fabricated AuthnRequest or InResponseTo','SAML 2.0 Profiles §4.1.5',samlProfilesUrl),
  samlIdpStartUrl:samlAttr('IdP-initiated SSO URL (configured action)','The IdP page/action starting an unsolicited application response.','Configured in the IdP; Keycloak uses an IdP Initiated SSO URL Name.','Selects the registered SAML application without sending an SP AuthnRequest.','https://idp1.example.test/realms/realm-a/protocol/saml/clients/app-saml','Keycloak setting / SAML IdP-initiated SSO','https://www.keycloak.org/docs/latest/server_admin/index.html'),
  samlEncryptedAssertion:samlAttr('EncryptedAssertion','The XML Encryption wrapper replacing a plaintext Assertion.','The IdP encrypts the already signed assertion for the SP’s public encryption certificate.','Only the SP holding the private decryption key can recover the assertion. It is XML Encryption, not JWE.','<saml:EncryptedAssertion><xenc:EncryptedData>…</xenc:EncryptedData><xenc:EncryptedKey>…</xenc:EncryptedKey></saml:EncryptedAssertion>','SAML 2.0 XML Encryption',samlXmlEncUrl),
  samlContentEncryptionKey:samlAttr('XML content-encryption key (local)','A fresh symmetric key for this encrypted assertion.','Generated temporarily by the encrypting IdP; recovered locally by the SP.','Encrypts assertion bytes. The plaintext key is never a browser-carried field.','Temporary AES-256 key; local only','XML Encryption 1.1',samlXmlEncUrl),
  samlEncryptedKey:samlAttr('xenc:EncryptedKey','The content-encryption key wrapped for the recipient’s public key.','The IdP wraps the key using the SP’s registered encryption certificate.','Travels inside the XML encryption structure; the SP unwraps it with its own private key.','RSA-OAEP wrapped key bytes; not the plaintext key','XML Encryption 1.1',samlXmlEncUrl),
  samlEncryptionAlgorithm:samlAttr('xenc:EncryptionMethod/@Algorithm (data)','The XML content-encryption algorithm URI.','Configured by the IdP and constrained by recipient policy.','This example uses AES-256-GCM; XML CipherValue encodes IV, ciphertext and tag together.','http://www.w3.org/2009/xmlenc11#aes256-gcm','XML Encryption 1.1',samlXmlEncUrl),
  samlKeyEncryptionAlgorithm:samlAttr('xenc:EncryptionMethod/@Algorithm (key)','The XML key-transport algorithm URI.','Configured by the IdP and recipient.','This example uses RSA-OAEP with explicitly configured SHA-256 digest/MGF; these are XML parameters, not JOSE alg/enc names.','http://www.w3.org/2009/xmlenc11#rsa-oaep; SHA-256 / MGF1-SHA256','XML Encryption 1.1',samlXmlEncUrl),
};

for(const [suffix,label]of [['App','application SP'],['Broker','Realm A acting as the broker SP']]){
  const app=suffix==='App',sp=app?'urn:example:app:sp':'urn:example:realm-a:broker:sp',acs=app?'https://app.example.test/saml/acs':'https://idp1.example.test/realms/realm-a/broker/saml-partner/endpoint';
  Object.assign(SAML_ATTRIBUTES,{
    ['samlSpEntity'+suffix]:samlAttr('entityID / AuthnRequest.Issuer ('+label+')','The registered SAML identity of the '+label+'.','Registered in SP metadata and IdP client configuration.','Selects the SP registration. In Keycloak this matches the SAML Client ID; no OAuth client_id parameter is sent.',sp),
    ['samlAcs'+suffix]:samlAttr('AssertionConsumerServiceURL ('+label+')','The registered HTTPS assertion-consumer endpoint.','Configured in SP metadata and approved by the IdP.','The SP requests/receives the browser SAML POST here; it is distinct from the SP entityID.',acs),
    ['samlRequestId'+suffix]:samlAttr('AuthnRequest/@ID ('+label+')','The unique identifier of this SP-initiated request.','Generated by the requesting SP and stored with its pending transaction.','The recipient later matches response and bearer confirmation InResponseTo to this value.',app?'_app_req_7f81':'_broker_req_94ac'),
    ['samlResponseId'+suffix]:samlAttr('Response/@ID ('+label+')','The unique ID of the IdP response.','Generated by the IdP.','Identifies the protocol response and its XML signature reference.',app?'_app_resp_1c52':'_broker_resp_2d63'),
    ['samlAssertionId'+suffix]:samlAttr('Assertion/@ID ('+label+')','The unique identifier of this assertion.','Generated by the issuing IdP.','Used by XML signature references and recipient replay protection.',app?'_app_assert_3e74':'_broker_assert_4f85'),
    ['samlRelayState'+suffix]:samlAttr('RelayState ('+label+')','An opaque binding value associated with SP application/transaction state.','In SP initiation, generated and stored by the requesting SP.','Returned unchanged and validated separately; keep it at most 80 bytes. POST XML signatures do not cover this separate form value.',app?'rs_app_7f81':'rs_broker_94ac','SAML 2.0 Bindings RelayState',samlBindingsUrl),
    ['samlInResponseTo'+suffix]:samlAttr('InResponseTo ('+label+')','Request correlation in Response and bearer SubjectConfirmationData.','Copied by the IdP from the SP’s AuthnRequest.ID.','The SP checks it against its pending request. It is absent in an unsolicited IdP-initiated app response.',app?'_app_req_7f81':'_broker_req_94ac'),
    ['samlNameId'+suffix]:samlAttr('NameID ('+label+')','The subject identifier presented to this SP.','The IdP derives it according to configured NameID format and mapping.','Identifies the trusted subject together with issuer/format. It is not automatically an OIDC sub.',app?'a-persistent-204':'b-persistent-913'),
    ['samlAudience'+suffix]:samlAttr('Audience ('+label+')','The permitted SP entityID in assertion AudienceRestriction.','Set by the IdP from the registered SP.','The receiver requires its own entityID; an audience is not the ACS URL.',sp),
    ['samlRecipient'+suffix]:samlAttr('Recipient ('+label+')','The ACS address in bearer SubjectConfirmationData.','Set by the IdP from the permitted response endpoint.','The recipient checks the value against its actual ACS URL.',acs),
    ['samlSessionIndex'+suffix]:samlAttr('SessionIndex ('+label+')','The IdP session identifier in AuthnStatement.','Generated/selected by the IdP for the authenticated session.','Can support SAML session management/logout; logout is outside this animation.',app?'saml_session_A_41':'saml_session_B_73'),
    ['samlAuthnContext'+suffix]:samlAttr('AuthnContextClassRef ('+label+')','The authentication-context class asserted under an agreed policy.','Emitted by the IdP only with configured mapping/enforcement semantics.','Describes the accepted authentication context; a URI alone is not an automatic MFA guarantee.','urn:example:authn-context:webauthn-user-verified'),
    ['samlEncryptionCertificate'+suffix]:samlAttr('SP encryption certificate ('+label+')','The SP’s public encryption key/certificate registered for encrypted assertions.','Published in trusted SP metadata or explicitly registered with the IdP.','The IdP uses this public key to wrap the temporary content-encryption key.','Public recipient X.509 certificate; not a private key','SAML metadata / XML Encryption',samlXmlEncUrl),
    ['samlDecryptKey'+suffix]:samlAttr('SP decryption key (private; '+label+')','The private key corresponding to the SP encryption certificate.','Provisioned and retained only by the receiving SP backend.','Unwraps the encrypted content key locally. It is never sent through the browser.','Recipient-only private decryption key; never transmitted','XML Encryption 1.1',samlXmlEncUrl),
  });
}
for(const [suffix,entity,actor]of [['App','urn:example:app:sp','application SP'],['A',EXAMPLE.issuerA,'Realm A'],['B',EXAMPLE.issuerB,'upstream IdP']]){
  Object.assign(SAML_ATTRIBUTES,{
    ['samlSigningKey'+suffix]:samlAttr('SAML signing key (private; '+actor+')','The sender’s configured private XML/query signing key.','Retained in the '+actor+' backend/key provider.','Signs protocol messages locally. Receivers verify with trusted public metadata keys.','Private signing key; never transmitted','SAML signing policy / XML Signature','https://www.w3.org/TR/xmldsig-core1/'),
    ['samlSigningCertificate'+suffix]:samlAttr('SAML signing certificate ('+actor+')','The trusted public key/certificate for this sender.','Obtained from authenticated configuration/metadata exchange.','Used to verify the expected signed element. An untrusted certificate inside ds:KeyInfo does not establish trust.','Trusted public X.509 signing certificate','SAML metadata / XML Signature','https://www.w3.org/TR/xmldsig-core1/'),
  });
  if(suffix!=='App')SAML_ATTRIBUTES['samlIdpEntity'+suffix]=samlAttr('Issuer / entityID ('+actor+')','The configured SAML identity of this IdP.','Published in trusted IdP metadata and configured at the SP.','The SP checks the exact expected issuer, independently of browser origin or OIDC issuer conventions.',entity);
}
SAML_ATTRIBUTES.samlSsoA=samlAttr('SingleSignOnService Location (Realm A)','Realm A’s SAML SSO endpoint from metadata.','Configured/published by Realm A.','An AuthnRequest Destination points here.',EXAMPLE.issuerA+'/protocol/saml','SAML 2.0 Metadata','https://docs.oasis-open.org/security/saml/v2.0/saml-metadata-2.0-os.pdf');
SAML_ATTRIBUTES.samlSsoB=samlAttr('SingleSignOnService Location (upstream IdP)','The upstream SAML SSO endpoint.','Published in trusted provider metadata.','Realm A sends its broker AuthnRequest here.',EXAMPLE.issuerB+'/protocol/saml','SAML 2.0 Metadata','https://docs.oasis-open.org/security/saml/v2.0/saml-metadata-2.0-os.pdf');

export const SAML_TOPIC_IDS=Object.freeze(Object.keys(SAML_ATTRIBUTES));
export const SAML_SOURCES=[{name:'SAML 2.0 Core',standard:'OASIS SAML 2.0',url:samlCoreUrl},{name:'SAML protocol bindings',standard:'HTTP-Redirect / HTTP-POST',url:samlBindingsUrl},{name:'SAML browser SSO profile',standard:'SP-initiated / IdP-initiated SSO',url:samlProfilesUrl},{name:'Approved SAML errata',standard:'Response/assertion signature policy',url:'https://docs.oasis-open.org/security/saml/v2.0/sstc-saml-approved-errata-2.0.html'},{name:'XML Encryption 1.1',standard:'EncryptedAssertion; distinct from JWE',url:samlXmlEncUrl},{name:'XML Signature 1.1',standard:'Enveloped XML signatures',url:'https://www.w3.org/TR/xmldsig-core1/'},{name:'Keycloak SAML clients and brokering',standard:'Product configuration',url:'https://www.keycloak.org/docs/latest/server_admin/index.html'}];

export function normalizeSamlConfig(input={}){
  const applicationProtocol=input.applicationProtocol==='oidc'?'oidc':'saml';
  const upstream=['single','keycloak','external'].includes(input.upstream)?input.upstream:'single';
  return {mode:JOURNEYS[input.mode]?input.mode:'passkey',architecture:applicationProtocol==='saml'?'web':input.architecture==='native'?'native':'web',upstream,authenticator:input.authenticator==='yubikey'?'yubikey':'hello',applicationProtocol,brokerProtocol:upstream==='single'?'none':input.brokerProtocol==='oidc'?'oidc':'saml',binding:input.binding==='post'?'post':'redirect',initiation:applicationProtocol==='saml'&&input.initiation==='idp'?'idp':'sp',encryptAssertions:!!input.encryptAssertions};
}
const samlConfigKey=c=>JSON.stringify(c);
const samlCanonical=s=>String(s.id).match(/(?:^|-)([a-z]\d{2})$/)?.[1];
const samlPayload=(name,value,description)=>({name,value,...(description?{description}:{})});
const samlOp=(ids,kind,actorId,detail,carriedAs)=>ids.map(attributeId=>({attributeId,kind,actorId,detail,...(carriedAs?{carriedAs}:{})}));
const samlWire=(ids,from,to,detail,carriedAs)=>[...samlOp(ids,'send',from,detail,carriedAs),...samlOp(ids,'receive',to,detail,carriedAs)];
const samlStage=(hop,key,title,from,to,phase,channel,summary,detail,fields,payload,attributeOperations,checks=[])=>({id:'saml-'+hop.kind+'-'+key,title,from,to,phase,channel,summary,detail,fields:[...new Set(fields)],payload,checks,attributeOperations,samlHop:hop.kind,samlStage:key,samlBinding:key.startsWith('response-')?'post':hop.config.binding,samlInitiation:hop.initiation,attributeValues:{...hop.values,samlRequestDestination:hop.values[hop.ssoId],samlResponseDestination:hop.values[hop.acsId]},encryptAssertions:hop.config.encryptAssertions,applicationProtocol:hop.config.applicationProtocol,brokerProtocol:hop.config.brokerProtocol,architecture:hop.config.architecture,topology:hop.config.upstream==='single'?'single':'brokered',upstream:hop.config.upstream,upstreamKind:hop.config.upstream==='single'?'single-realm':'saml-provider'});
const samlContextForMode=mode=>mode==='password'?'urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport':'urn:example:authn-context:'+({'password-totp':'password-totp','one-time-code':'totp-possession','passkey-totp':'webauthn-totp',passkey:'webauthn-user-verified'}[mode]||'verified-account');
function samlHop(config,kind){
  const app=kind==='app',suffix=app?'App':'Broker',issuer=app?'realmA':'realmB',sp=app?'app':'realmA',idpSuffix=app?'A':'B';
  const h={config,kind,suffix,issuer,sp,initiation:app?config.initiation:'sp',entityId:'samlSpEntity'+suffix,acsId:'samlAcs'+suffix,requestId:'samlRequestId'+suffix,responseId:'samlResponseId'+suffix,assertionId:'samlAssertionId'+suffix,relayId:'samlRelayState'+suffix,correlationId:'samlInResponseTo'+suffix,nameId:'samlNameId'+suffix,audienceId:'samlAudience'+suffix,recipientId:'samlRecipient'+suffix,sessionId:'samlSessionIndex'+suffix,contextId:'samlAuthnContext'+suffix,idpId:'samlIdpEntity'+idpSuffix,ssoId:'samlSso'+idpSuffix,spSigningKey:app?'samlSigningKeyApp':'samlSigningKeyA',spCertificate:app?'samlSigningCertificateApp':'samlSigningCertificateA',idpSigningKey:'samlSigningKey'+idpSuffix,idpCertificate:'samlSigningCertificate'+idpSuffix,encryptionCert:'samlEncryptionCertificate'+suffix,decryptionKey:'samlDecryptKey'+suffix};
  h.values=Object.fromEntries(Object.entries(SAML_ATTRIBUTES).map(([id,a])=>[id,a.example]));
  if(config.upstream==='external'){h.values.samlIdpEntityB='https://login.partner.example.test/saml/metadata';h.values.samlSsoB='https://login.partner.example.test/saml/sso';h.values.samlNameIdBroker='partner-persistent-913';}
  h.values[h.contextId]=samlContextForMode(config.mode);
  if(h.initiation==='idp')h.values[h.relayId]='rs_idp_landing_01';
  return h;
}

function samlRequestSteps(h){
  const v=id=>h.values[id],requestMembers=[h.requestId,h.entityId,'samlIssueInstant','samlRequestDestination',h.acsId,'samlProtocolBinding'];
  const xml='<samlp:AuthnRequest ID="'+v(h.requestId)+'" Version="2.0" IssueInstant="'+samlClock+'" Destination="'+v(h.ssoId)+'" AssertionConsumerServiceURL="'+v(h.acsId)+'" ProtocolBinding="'+samlPostBinding+'"><saml:Issuer>'+v(h.entityId)+'</saml:Issuer></samlp:AuthnRequest>';
  const create=samlStage(h,'request-create','Create a separate SAML AuthnRequest',h.sp,h.sp,'prepare','internal','The SP creates a fresh request ID and opaque RelayState.','The SP selects its own registered SAML entityID, IdP SSO endpoint and ACS. It stores the fresh request ID and RelayState with its browser transaction. '+(h.kind==='broker'?'Realm A is a separate SAML SP on this hop; application OAuth state/nonce/PKCE are not forwarded as SAML values.':'In Keycloak the configured SAML Client ID matches this SP entityID/Issuer; this request has no OAuth client_id, PKCE or nonce.'),['samlAuthnRequest',...requestMembers,h.relayId,h.ssoId],[samlPayload('AuthnRequest',xml),samlPayload('RelayState',v(h.relayId))],[...samlOp([h.entityId,h.acsId,h.ssoId,'samlProtocolBinding'],'use',h.sp,'Uses trusted SP registration and IdP metadata.'),...samlOp([h.requestId,h.relayId,'samlIssueInstant'],'create',h.sp,'Creates fresh SAML request correlation and opaque transaction routing state.'),...samlOp([h.requestId,h.relayId],'store',h.sp,'Associates request ID and RelayState with this pending browser transaction.'),...samlOp(['samlAuthnRequest'],'create',h.sp,'Constructs AuthnRequest XML with the registered SP Issuer and requested POST ACS.')]);
  const redirect=h.config.binding==='redirect';
  const bindingOps=[...samlOp([h.spSigningKey],'use',h.sp,'The configured SP private signing key stays on this server.')];
  if(redirect)bindingOps.push(...samlOp(['samlRequest'],'derive',h.sp,'Serializes XML, applies raw RFC 1951 DEFLATE, Base64 and URL encoding.'),...samlOp(['samlSigAlg','samlRedirectSignature'],'derive',h.sp,'Signs the exact original URL-encoded SAMLRequest&RelayState&SigAlg string, in that order.'));
  else bindingOps.push(...samlOp(['samlXmlSignature'],'derive',h.sp,'Adds an enveloped ds:Signature to the AuthnRequest XML; the separate RelayState form field is not signed by this XML signature.'),...samlOp(['samlRequest'],'derive',h.sp,'Base64-encodes the signed XML for the HTTP-POST form; no DEFLATE.'));
  const encoded=redirect?'URL_ENCODE(BASE64(RAW_DEFLATE(AuthnRequest XML)))':'BASE64(signed AuthnRequest XML)';
  const wireIds=['samlRequest',h.relayId,...(redirect?['samlSigAlg','samlRedirectSignature']:['samlXmlSignature'])],nestedIds=['samlAuthnRequest',...requestMembers],allWireIds=[...wireIds,...nestedIds];
  const bindingPayload=redirect?[samlPayload('HTTP','302 Found'),samlPayload('Location',v(h.ssoId)+'?SAMLRequest='+encoded+'&RelayState='+v(h.relayId)+'&SigAlg=URL_ENCODE('+samlRsaSha256+')&Signature=URL_ENCODE(BASE64(signature bytes))'),samlPayload('Signed query','SAMLRequest=<original encoded value>&RelayState=<original encoded value>&SigAlg=<original encoded URI>')]:[samlPayload('HTTP','200 HTML auto-submit form'),samlPayload('Form action',v(h.ssoId)),samlPayload('SAMLRequest',encoded),samlPayload('RelayState',v(h.relayId))];
  const bind=samlStage(h,'request-bind',redirect?'Sign and send an HTTP-Redirect request':'Sign and send an HTTP-POST request',h.sp,'browser','broker',redirect?'redirect':'https','The SP gives the browser an encoded and signed SAML request.',redirect?'The outgoing AuthnRequest has no enveloped XML signature. Redirect signs the exact encoded SAMLRequest, optional RelayState and SigAlg values in the prescribed order; Signature itself is excluded. The URI uses raw DEFLATE, Base64 and URL encoding.':'The browser receives an HTML form with Base64 signed AuthnRequest XML and a separate opaque RelayState. An enveloped XML signature protects the XML, not the RelayState control; the SP must retain transaction/browser correlation.',[...allWireIds,h.spSigningKey],bindingPayload,[...bindingOps,...samlWire(wireIds,h.sp,'browser','Encoded signed SAML request carried by the browser.',redirect?'HTTP Location query':'HTTP-POST form fields'),...samlWire(nestedIds,h.sp,'browser','Nested AuthnRequest members travel inside the encoded request, not as separate query/form parameters.','AuthnRequest XML inside encoded SAMLRequest')]);
  const browser=samlStage(h,'request-browser','Deliver the request to the IdP','browser',h.issuer,'broker','https','The browser carries the SAML request to the configured IdP SSO endpoint.','This is browser navigation, not a server-to-server OAuth token request. The IdP will validate the configured SP entityID, destination, allowed ACS and request signature before starting its login session.',allWireIds,[samlPayload('HTTP',redirect?'GET '+v(h.ssoId):'POST '+v(h.ssoId)),samlPayload('SAMLRequest',encoded),samlPayload('RelayState',v(h.relayId)),...(redirect?[samlPayload('SigAlg',samlRsaSha256),samlPayload('Signature','Redirect query signature bytes')]:[])],[...samlWire(wireIds,'browser',h.issuer,'Delivers the signed request using the chosen SAML binding.',redirect?'original URL-encoded query':'POST form controls'),...samlWire(nestedIds,'browser',h.issuer,'Delivers these members nested inside AuthnRequest XML.','AuthnRequest XML inside encoded SAMLRequest')]);
  const verify=samlStage(h,'request-verify','Validate the registered SAML SP',h.issuer,h.issuer,'broker','internal','The IdP verifies the request and selects the SP’s registered configuration.','The IdP checks the signed request against its trusted SP certificate and allowed algorithms, exact Destination, SP Issuer/entityID, approved ACS and requested POST binding. Redirect validation uses the original encoded query bytes; POST validation uses the signed XML element. The request ID is kept in the authentication context and RelayState is returned unchanged, not trusted as an arbitrary redirect URL.',[...requestMembers,h.relayId,h.spCertificate,...wireIds],[samlPayload('Registered SP Issuer',v(h.entityId)),samlPayload('Allowed ACS',v(h.acsId)),samlPayload('Requested response binding',samlPostBinding)],[...samlOp(['samlRequest'],'derive',h.issuer,'Decodes the selected SAML binding into AuthnRequest XML.'),...samlOp([h.spCertificate],'use',h.issuer,'Uses the configured trusted SP signing certificate, not an untrusted KeyInfo key.'),...samlOp(redirect?['samlRedirectSignature','samlSigAlg']:['samlXmlSignature'],'verify',h.issuer,'Validates the request signature and accepted algorithms.'),...samlOp([h.entityId,h.acsId,'samlRequestDestination','samlProtocolBinding'],'verify',h.issuer,'Checks the registered SP, actual destination, approved ACS and binding.'),...samlOp([h.requestId,h.relayId],'store',h.issuer,'Associates this SAML request with the IdP’s authentication context.')],['Trusted SP signature valid','Issuer selects registered SAML client','Destination and ACS allowed','POST response binding accepted']);
  return [create,bind,browser,verify];
}

function samlClaimIds(h){return [h.assertionId,h.idpId,h.nameId,'samlNameIdFormat',h.audienceId,h.recipientId,'samlNotBefore','samlNotOnOrAfter','samlSubjectExpiry','samlAuthnInstant',h.sessionId,h.contextId,...(h.initiation==='sp'?[h.correlationId]:[])];}
function samlResponseSteps(h){
  const v=id=>h.values[id],claims=samlClaimIds(h),headers=[h.responseId,h.idpId,'samlIssueInstant','samlResponseDestination','samlStatusCode',...(h.initiation==='sp'?[h.correlationId]:[])];
  const claimPayload=[samlPayload('Issuer',v(h.idpId)),samlPayload('NameID',v(h.nameId)),samlPayload('Audience',v(h.audienceId)),samlPayload('Recipient',v(h.recipientId)),samlPayload('Conditions.NotBefore',samlClock),samlPayload('Conditions.NotOnOrAfter',samlUntil),samlPayload('SubjectConfirmationData.NotOnOrAfter',samlUntil),samlPayload('AuthnContextClassRef',v(h.contextId)),...(h.initiation==='sp'?[samlPayload('InResponseTo',v(h.requestId))]:[])];
  const create=samlStage(h,'response-create','Build and sign the SAML identity result',h.issuer,h.issuer,'return','internal','The IdP creates its subject statement and signs the Assertion.','Configured authentication has succeeded. The IdP builds an assertion for this SP entityID and ACS, with bearer confirmation and short validity bounds. Conditions has NotBefore/NotOnOrAfter; bearer SubjectConfirmationData has NotOnOrAfter and no NotBefore. This model configures an assertion signature and later an outer Response signature; SAML policy may require one or both. AuthnContextClassRef is emitted only under agreed method/assurance mapping, not automatically inferred as MFA. '+(h.initiation==='sp'?'Response and bearer InResponseTo refer to the saved AuthnRequest.ID.':'This unsolicited application response has no AuthnRequest and omits InResponseTo in both Response and bearer confirmation.'),['samlAssertion',...claims,...headers,h.entityId,h.acsId,h.idpSigningKey,'samlXmlSignature'],[samlPayload('Assertion ID',v(h.assertionId)),...claimPayload,samlPayload('ds:Signature','Inner Assertion XML signature')],[...samlOp([h.idpSigningKey],'use',h.issuer,'Keeps the signing private key local to this IdP.'),...samlOp([h.idpId,h.entityId,h.acsId,'samlNameIdFormat'],'use',h.issuer,'Uses the configured IdP issuer, registered SP entityID/ACS and agreed subject identifier format.'),...samlOp(['samlAssertion',h.assertionId,h.responseId,h.nameId,'samlIssueInstant','samlAuthnInstant',h.sessionId,h.contextId],'create',h.issuer,'Constructs the signed identity assertion under configured subject/context policy.'),...samlOp([h.audienceId,h.recipientId,'samlNotBefore','samlNotOnOrAfter','samlSubjectExpiry','samlStatusCode'],'create',h.issuer,'Sets intended SP, bearer ACS recipient and bounded assertion/confirmation validity.'),...(h.initiation==='sp'?samlOp([h.correlationId],'derive',h.issuer,'Copies the original SP AuthnRequest.ID into Response and bearer confirmation.'):[]),...samlOp(['samlXmlSignature'],'derive',h.issuer,'Signs this Assertion XML with the configured IdP signing key.')]);
  const steps=[create];
  if(h.config.encryptAssertions)steps.push(samlStage(h,'assertion-encrypt','Encrypt the signed assertion for the SP',h.issuer,h.issuer,'return','internal','The IdP encrypts the signed Assertion with a temporary content key.','The registered SP public encryption certificate wraps a fresh AES-256 content key using XML RSA-OAEP with configured SHA-256 digest/MGF. AES-GCM encrypts the signed assertion; XML CipherValue contains IV, ciphertext and tag. The output is EncryptedAssertion plus EncryptedKey. No plaintext content key or recipient private key is sent. This is XML Encryption, not JWE.',[...claims,'samlAssertion','samlEncryptedAssertion','samlContentEncryptionKey','samlEncryptedKey','samlEncryptionAlgorithm','samlKeyEncryptionAlgorithm',h.encryptionCert],[samlPayload('EncryptedAssertion','EncryptedData + EncryptedKey (symbolic XML)'),samlPayload('EncryptionMethod','AES-256-GCM / XML RSA-OAEP')],[...samlOp([h.encryptionCert],'use',h.issuer,'Uses the recipient’s registered public encryption certificate.'),...samlOp(['samlEncryptionAlgorithm','samlKeyEncryptionAlgorithm'],'use',h.issuer,'Uses configured allowed XML content-encryption and key-transport algorithms with agreed digest/MGF parameters.'),...samlOp(['samlContentEncryptionKey'],'create',h.issuer,'Creates a temporary symmetric content key locally.'),...samlOp(['samlAssertion',...claims],'use',h.issuer,'Uses the signed plaintext assertion locally as encryption input.'),...samlOp(['samlEncryptedAssertion','samlEncryptedKey'],'derive',h.issuer,'Encrypts assertion data and wraps the content key for this recipient.') ]));
  const assertionWire=h.config.encryptAssertions?['samlEncryptedAssertion','samlEncryptedKey','samlEncryptionAlgorithm','samlKeyEncryptionAlgorithm']:['samlAssertion',...claims];
  const wireIds=['samlResponse','samlResponseXml',...headers,'samlXmlSignature',h.relayId,...assertionWire];
  const responseText=h.config.encryptAssertions?'BASE64(<Response>signed outer wrapper + EncryptedAssertion</Response>)':'BASE64(<Response>signed outer wrapper + signed Assertion</Response>)';
  const post=samlStage(h,'response-post','Send the signed SAML response by POST',h.issuer,'browser','return','https','The IdP gives the browser an auto-submit form for the registered ACS.','The IdP signs the outer Response containing the '+(h.config.encryptAssertions?'encrypted':'signed plaintext')+' assertion and returns an HTTP-POST form. RelayState is a separate form control; XML signatures do not cover it. The browser transports this result and never receives private signing/decryption keys. '+(h.config.encryptAssertions?'Identity claims are inside ciphertext on this browser hop.':'Plain assertion claims are nested in the signed Response XML and protected in transit by HTTPS.'),wireIds,[samlPayload('Form action',v(h.acsId)),samlPayload('SAMLResponse',responseText),samlPayload('RelayState',v(h.relayId))],[...samlOp(['samlResponseXml'],'create',h.issuer,'Builds Response XML around the assertion and protocol headers.'),...samlOp(['samlXmlSignature'],'derive',h.issuer,'Signs the enclosing Response XML with the IdP signing key.'),...samlOp(['samlResponse'],'derive',h.issuer,'Base64-encodes the response for the POST form; no DEFLATE.'),...samlWire(wireIds,h.issuer,'browser','SAML response carried in the auto-submit POST form.',h.config.encryptAssertions?'Response XML; identity claims remain inside EncryptedAssertion':'signed Response / Assertion XML')]);
  const receive=samlStage(h,'response-browser','Post the response to the SP ACS','browser',h.sp,'return','https','The browser posts SAMLResponse and RelayState to the service provider.','This browser POST reaches the registered HTTPS ACS. It is not an OAuth code callback or token redemption. '+(h.config.encryptAssertions?'The browser carries encrypted assertion XML; plaintext identity fields are not animated as browser-carried values.':'Assertion identity fields remain nested inside the signed XML response.'),wireIds,[samlPayload('HTTP','POST '+v(h.acsId)),samlPayload('SAMLResponse',responseText),samlPayload('RelayState',v(h.relayId))],samlWire(wireIds,'browser',h.sp,'Delivers the signed POST response to its registered ACS.',h.config.encryptAssertions?'EncryptedAssertion inside Response XML':'signed Assertion inside Response XML'));
  const verifyOps=[...samlOp([h.idpCertificate],'use',h.sp,'Uses the trusted configured IdP verification certificate; untrusted KeyInfo cannot establish issuer trust.'),...samlOp(['samlResponse','samlResponseXml'],'derive',h.sp,'Decodes the POST binding and processes the expected signed Response element.'),...samlOp(['samlXmlSignature'],'verify',h.sp,'Verifies the required outer Response signature over the expected XML element using trusted keys and allowed algorithms.')];
  if(h.config.encryptAssertions)verifyOps.push(...samlOp(['samlEncryptionAlgorithm','samlKeyEncryptionAlgorithm'],'verify',h.sp,'Rejects disallowed content/key EncryptionMethod algorithms and digest/MGF parameters before unwrapping or decrypting.'),...samlOp([h.decryptionKey],'use',h.sp,'Uses its own private decryption key locally; it never leaves this SP.'),...samlOp(['samlEncryptedKey','samlEncryptedAssertion'],'use',h.sp,'Processes the encrypted XML structures only under the accepted algorithm policy.'),...samlOp(['samlContentEncryptionKey'],'derive',h.sp,'Unwraps the content key locally using its recipient private key.'),...samlOp(['samlEncryptedAssertion'],'verify',h.sp,'Performs authenticated AES-GCM decryption and rejects any invalid authentication tag in CipherValue before releasing plaintext.'),...samlOp(['samlAssertion',...claims],'derive',h.sp,'Recovers the signed assertion only after authenticated decryption succeeds; these plaintext values are local to the receiver.'));
  verifyOps.push(...samlOp(['samlXmlSignature'],'verify',h.sp,'Verifies the inner Assertion signature after decryption when applicable, and consumes only the validated signed element.'),...samlOp([...headers,...claims],'verify',h.sp,'Checks expected issuer, successful status, ACS Destination/Recipient, SP Audience, conditions/confirmation expiry and accepted subject/context policy.'),...(h.initiation==='sp'?[...samlOp([h.requestId,h.correlationId,h.relayId],'verify',h.sp,'Matches Response and bearer InResponseTo plus opaque RelayState to the saved request/browser transaction.'),...samlOp([h.requestId],'use',h.sp,'Consumes the pending SAML request after successful validation.')]:[...samlOp(['samlUnsolicitedPolicy'],'verify',h.sp,'Requires explicitly enabled unsolicited acceptance; there is no request ID or request-correlated login-CSRF protection.'),...samlOp([h.relayId],'verify',h.sp,'Treats unsolicited RelayState only as approved routing data, not proof of a request/browser transaction.')]),...samlOp(['samlReplayState'],'verify',h.sp,'Rejects previously accepted Assertion IDs.'),...samlOp(['samlReplayState'],'store',h.sp,'Remembers the accepted assertion ID through its validity window.'));
  const verification=samlStage(h,'response-verify','Validate the SAML result at the SP',h.sp,h.sp,'tokens','internal','The SP validates trusted signatures and the assertion’s intended recipient and validity.','Verify the configured outer Response signature with trusted metadata keys. '+(h.config.encryptAssertions?'Then check the content/key EncryptionMethod allowlists, unwrap the content key and perform authenticated AES-GCM decryption. Reject any invalid CipherValue authentication tag before releasing plaintext and checking the inner Assertion signature. ':'Then verify the inner Assertion signature. ')+'Accept only the expected signed XML elements with allowed algorithms; validate issuer, StatusCode, actual Destination/ACS, Audience=SP entityID, bearer Recipient=ACS, Conditions time bounds, bearer expiry and assertion replay policy. '+(h.initiation==='sp'?'Match both InResponseTo values and opaque RelayState to the saved request and browser transaction.':'There is no InResponseTo. Explicitly permit unsolicited responses and evaluate login-CSRF/account-switching limitations; RelayState is only routing data.')+' Only then establish identity under the agreed NameID/authentication-context policy.',[...wireIds,...claims,h.idpCertificate,'samlReplayState',...(h.config.encryptAssertions?[h.decryptionKey,'samlContentEncryptionKey']:[]),...(h.initiation==='idp'?['samlUnsolicitedPolicy']:[h.requestId])],[samlPayload('Expected Audience',v(h.entityId)),samlPayload('Expected Recipient / Destination',v(h.acsId)),samlPayload('Validated NameID',v(h.nameId)),samlPayload('Accepted context',v(h.contextId))],verifyOps,['Trusted signatures and exact issuer valid','Audience matches SP entityID','Recipient and Destination match ACS','Conditions and bearer expiry valid','Assertion ID not replayed',h.initiation==='sp'?'Response and bearer InResponseTo match pending request':'Explicit unsolicited-response policy accepted']);
  steps.push(post,receive,verification);
  if(h.kind==='broker')steps.push(samlStage(h,'map-account','Map the trusted upstream SAML identity','realmA','realmA','tokens','internal','A resolves the trusted upstream NameID to its own local account.','Realm A applies its configured broker account-linking/import and authentication-context policy to the validated issuer/NameID/format, then establishes A’s own session. Extra first-broker-login actions can be required. This is not another password/passkey verification and it does not forward the upstream assertion as the app’s final result.',[h.idpId,h.nameId,'samlNameIdFormat',h.contextId,'subjectA','session'],[samlPayload('Trusted external identity',v(h.idpId)+' / '+v(h.nameId)),samlPayload('Local A account','user-in-A-204')],[...samlOp([h.idpId,h.nameId,'samlNameIdFormat',h.contextId],'use','realmA','Uses only the validated SAML identity and agreed authentication context.'),...samlOp(['subjectA'],'use','realmA','Resolves an existing or policy-authorized linked/imported local A account.'),...samlOp(['session'],'create','realmA','Establishes Realm A’s own authenticated session after broker policy succeeds.') ]));
  return steps;
}

const samlStepsCache=new Map();
export function getSamlSteps(input={}){
  const c=normalizeSamlConfig(input),key=samlConfigKey(c);if(samlStepsCache.has(key))return samlStepsCache.get(key);
  const base=applyFidoTransport(getJourneySteps(c.mode,c.architecture,c.upstream),c.authenticator);
  if(JOURNEYS[c.mode].enrollment||(c.applicationProtocol==='oidc'&&c.brokerProtocol!=='saml')){samlStepsCache.set(key,base);return base;}
  const appHop=samlHop(c,'app'),brokerHop=samlHop(c,'broker');
  const clone=item=>({...item,fields:[...item.fields],payload:item.payload.map(p=>({...p})),checks:[...item.checks]});
  const factors=base.filter(item=>['passkey','password','mfa','otp'].includes(item.phase)).map(item=>{
    const s=clone(item),samlFactor=c.upstream==='single'?c.applicationProtocol==='saml':c.brokerProtocol==='saml';
    if(samlFactor)s.detail=s.detail.replaceAll('broker authorization code','SAML response').replaceAll('application authorization code','SAML response').replaceAll('normal OIDC code response','signed SAML response').replaceAll('OIDC authorization response','SAML response');
    if((c.applicationProtocol==='saml'||samlFactor)&&samlCanonical(s)==='p01')s.detail='The IdP displays its own account username/password form and checks these account credentials locally, plus required TOTP if configured. '+(samlFactor&&c.upstream!=='single'?'The A-B broker hop carries a signed SAML identity result; ':'')+(c.applicationProtocol==='saml'?'The application receives its own signed SAML result rather than the typed password.':'The app-A hop remains OIDC Authorization Code with PKCE; the password is not delivered to the application.');
    if(c.applicationProtocol==='saml'&&samlCanonical(s)==='p02')s.detail='The person enters the IdP account username and password on its HTTPS page. These are the IdP account credentials; the SAML service-provider application does not receive them.';
    return s;
  });
  let result=[];
  if(c.applicationProtocol==='oidc')result.push(...base.filter(item=>['l01','l02','l03','l04','w00'].includes(samlCanonical(item))).map(clone));
  else if(c.initiation==='sp'){
    result.push(samlStage(appHop,'start','Choose SAML sign-in','user','browser','prepare','local','The person chooses Sign in on the web application.','The server-hosted application is a registered SAML service provider. It will create an AuthnRequest for Realm A; no OAuth client_id or PKCE fields appear on this app hop.',[],[samlPayload('Browser UI','Sign in at app.example.test')],[]));
    result.push(samlStage(appHop,'start-backend','Ask the SP backend to begin','browser','app','prepare','https','The browser asks its application backend to start SAML sign-in.','A normal HTTPS application request starts the SP transaction. The backend chooses the trusted IdP metadata and keeps request/browser correlation server-side.',[],[samlPayload('HTTP','GET https://app.example.test/saml/login')],[]));
    result.push(...samlRequestSteps(appHop));
  }else{
    result.push(samlStage(appHop,'idp-start','Choose the application in the IdP portal','user','browser','prepare','local','The person selects the registered application at the IdP.','This explicitly configured IdP-initiated path starts without an SP AuthnRequest. The SP must separately permit unsolicited responses and evaluate their missing request-correlation safeguards.',['samlIdpStartUrl'],[samlPayload('Browser UI','Open the IdP application link')],samlOp(['samlIdpStartUrl'],'use','user','Chooses the configured IdP application entry.')));
    result.push(samlStage(appHop,'idp-browser','Open the configured IdP SSO action','browser','realmA','prepare','https','The browser opens Realm A’s configured application entry.','A uses the configured IdP-initiated URL name to select the registered SAML SP, ACS and key policy. It starts authentication without a client AuthnRequest, request ID or InResponseTo. A broker request, if needed, is still independently SP-initiated.',['samlIdpStartUrl',appHop.entityId,appHop.acsId],[samlPayload('HTTP','GET '+SAML_ATTRIBUTES.samlIdpStartUrl.example)],[...samlOp(['samlIdpStartUrl'],'use','browser','Opens the configured IdP-side SSO action.'),...samlOp([appHop.entityId,appHop.acsId],'use','realmA','Selects the configured SP registration and allowed ACS from this IdP action.'),...samlOp([appHop.relayId],'create','realmA','Creates only approved unsolicited routing RelayState; no pending SP request exists.')]));
  }
  if(c.upstream!=='single'){
    if(c.brokerProtocol==='saml')result.push(...samlRequestSteps(brokerHop));
    else result.push(...base.filter(item=>['l05','l06','l07'].includes(samlCanonical(item))).map(item=>{const copy=clone(item);if(samlCanonical(copy)==='l05'&&c.applicationProtocol==='saml')copy.detail='Realm A starts a separate OIDC Authorization Code request as the confidential upstream broker client. It creates independent broker state/nonce and uses its HTTPS OIDC broker callback. Those values belong to this OIDC hop; the SAML application’s entityID, AuthnRequest ID and RelayState are separate.';return copy;}));
  }
  result.push(...factors);
  if(c.upstream!=='single'){
    if(c.brokerProtocol==='saml')result.push(...samlResponseSteps(brokerHop));
    else result.push(...base.filter(item=>['l15','l16','l17','l18','l19'].includes(samlCanonical(item))).map(clone));
  }
  if(c.applicationProtocol==='oidc')result.push(...base.filter(item=>['l20','l21','l22','l23','l24','l25','w01'].includes(samlCanonical(item))).map(item=>{const s=clone(item);if(c.brokerProtocol==='saml'&&samlCanonical(s)==='l24')s.detail='Realm A signs its own OIDC ID token for the application’s registered client_id and returns its access token and any permitted refresh token directly to the application. The upstream SAML assertion is validated by A and mapped to a local A account; it is not the app’s OIDC token.';return s;}));
  else{
    result.push(...samlResponseSteps(appHop));
    result.push(samlStage(appHop,'session','Establish the web application session','app','browser','complete','https','The SP creates its own session after accepting the validated SAML identity.','The SP maps the accepted issuer/NameID/format according to application policy, creates server-side session state and returns a protected opaque cookie. The signed SAML result is an authentication assertion, not an OAuth access token or PKCE code.',['sessionCookieApp',appHop.nameId,appHop.idpId],[samlPayload('Set-Cookie','__Host-app_session=<opaque>; Secure; HttpOnly; SameSite=Lax; Path=/'),samlPayload('HTTPS response','Signed-in application page')],[...samlOp([appHop.nameId,appHop.idpId],'use','app','Uses only the validated SAML subject identity under application mapping policy.'),...samlOp(['sessionCookieApp'],'create','app','Creates an opaque authenticated application session handle.'),...samlWire(['sessionCookieApp'],'app','browser','Returns the application session cookie.','Set-Cookie'),...samlOp(['sessionCookieApp'],'store','browser','Stores the cookie for permitted later requests to this application.')]));
    result.push(samlStage(appHop,'complete','Show the signed-in application','browser','user','complete','local','The person sees the signed-in web application.','The browser renders the SP response. This UI step does not deliver assertion keys or cookie values to the person.',[],[samlPayload('Browser UI','Signed in at app.example.test')],[]));
  }
  samlStepsCache.set(key,result);return result;
}

const samlDefinitionCache=new Map();
export function getSamlExampleOverrides(input={}){
  const c=normalizeSamlConfig(input),a=samlHop(c,'app'),b=samlHop(c,'broker');
  const result={...a.values,...b.values,samlAuthnContextApp:samlContextForMode(c.mode),samlAuthnContextBroker:samlContextForMode(c.mode),samlRequestDestination:c.applicationProtocol==='saml'?a.values.samlSsoA:b.values.samlSsoB,samlResponseDestination:c.applicationProtocol==='saml'?a.values.samlAcsApp:b.values.samlAcsBroker};
  if(c.initiation==='idp'){result.samlRequestIdApp='Absent: unsolicited IdP-initiated response';result.samlInResponseToApp='Absent from Response and bearer confirmation';result.samlRelayStateApp='rs_idp_landing_01';}
  return result;
}
export function getSamlAttributeOverrides(input={}){
  const c=normalizeSamlConfig(input),key=samlConfigKey(c);if(samlDefinitionCache.has(key))return samlDefinitionCache.get(key);
  const result={...getAttributeOverrides(c.architecture,c.upstream)},examples=getSamlExampleOverrides(c);
  for(const [id,a]of Object.entries(SAML_ATTRIBUTES))result[id]={...a,example:examples[id]||a.example};
  if(c.applicationProtocol==='saml')result.sessionCookieApp={...VARIANT_ATTRIBUTES.sessionCookieApp,origin:'Generated by the application SP backend after validating the signed SAML assertion.',generator:'Application SP backend',purpose:'Identifies the application’s own authenticated server-side session. The browser stores this protected opaque cookie; the SAML assertion is validated at the backend before the session is created.'};
  if(c.initiation==='idp')Object.assign(result.samlRelayStateApp,{origin:'Configured/generated by the IdP for approved unsolicited application routing.',generator:'Realm A’s IdP-initiated action',purpose:'The SP accepts only approved routing data. This value does not match a pending AuthnRequest and does not supply request-correlated login-CSRF protection.'});
  if(c.encryptAssertions)result.samlAssertion.purpose='Constructed and signed locally at the IdP, encrypted before browser transport, then recovered locally at the recipient SP. Plaintext assertion claims are not browser wire attributes in this configuration.';
  samlDefinitionCache.set(key,result);return result;
}

const samlActorCache=new Map();
const samlAppOidcFields=new Set(['clientIdApp','redirectApp','authorizationEndpoint','tokenEndpoint','jwksUri','scope','stateApp','nonceApp','codeVerifier','codeChallenge','codeChallengeMethod','codeA','idTokenA','accessTokenA','refreshToken','issuerA','audience','exp','iat']);
const samlBrokerOidcFields=new Set(['clientIdBroker','clientSecret','redirectBroker','stateBroker','nonceBroker','codeB','idTokenB','accessTokenB','issuerB','subjectB','authorizationHeader']);
export function getSamlActorOverrides(input={}){
  const c=normalizeSamlConfig(input),key=samlConfigKey(c);if(samlActorCache.has(key))return samlActorCache.get(key);
  const baseOverrides=getActorOverrides(c.architecture,c.upstream),actors=Object.fromEntries(Object.entries(ACTORS).map(([id,actor])=>[id,{...actor,...baseOverrides[id],attributes:(baseOverrides[id]?.attributes||actor.attributes).map(a=>({...a})),notes:[...(baseOverrides[id]?.notes||actor.notes)]}]));
  const add=(actorId,id,kind)=>{const actor=actors[actorId];if(!actor.attributes.some(a=>a.id===id))actor.attributes.push({id,kind});};
  if(JOURNEYS[c.mode].enrollment||(c.applicationProtocol==='oidc'&&c.brokerProtocol!=='saml')){samlActorCache.set(key,actors);return actors;}
  const factorRealm=c.upstream==='single'?'Realm A':c.upstream==='external'?'the independent upstream provider':'Realm B';
  actors.realmA.notes=[c.upstream==='single'?'A verifies the configured factor method against its own existing local account.':'A validates the upstream identity result and applies its account-linking/mapping policy; it does not receive the upstream account password or private credential key.',c.applicationProtocol==='saml'?'A is the application’s SAML IdP: the app entityID identifies its registration and assertion Audience, while its HTTPS ACS is the response Destination and bearer Recipient.':'A is the application’s OIDC provider: application client_id selects registration, binds the authorization code and is validated against ID-token aud.',...(c.upstream==='single'?['There is one application-Realm A identity hop.']:[c.brokerProtocol==='saml'?'A is separately a SAML SP to the upstream provider, with its own entityID, AuthnRequest ID, ACS and RelayState.':'A is separately a confidential OIDC client to the upstream provider, with independently generated state and nonce and its own broker callback.'])];
  if(c.applicationProtocol==='saml')actors.realmA.attributes=actors.realmA.attributes.filter(a=>a.id!=='realmSigningKey');
  if(c.upstream!=='single'&&c.brokerProtocol==='saml')actors.realmB.notes=['The configured upstream provider authenticates its own account using the selected supported factor method.','It returns a signed SAML identity result to Realm A’s registered broker ACS; this hop has no OIDC code, state, nonce or token.',c.upstream==='external'?'This independent provider has its own issuer/entityID, certificates, accounts and sessions.':'Realm B has its own certificates, accounts and authentication policy.'];
  actors.browser.notes=['Displays the application and the configured IdP HTTPS pages.','WebAuthn executes on '+factorRealm+'’s HTTPS origin; credential private keys and local PIN/biometric secrets remain protected locally.',c.applicationProtocol==='saml'?'Posts the SAML response to the application ACS and stores the application’s later opaque session cookie.':c.architecture==='web'?'Carries the OIDC HTTPS callback to the backend; the backend retains its verifier, secret and tokens.':'Carries the OIDC callback to the native application’s loopback listener.'];
  for(const kind of ['app','broker']){
    if(kind==='app'&&c.applicationProtocol!=='saml'||kind==='broker'&&(c.upstream==='single'||c.brokerProtocol!=='saml'))continue;
    const h=samlHop(c,kind),sp=actors[h.sp],idp=actors[h.issuer];
    if(kind==='app'){
      sp.name='Web application';sp.role='SAML service provider (SP)';sp.plainRole='Validates the SAML result at its HTTPS ACS and creates your application session.';sp.attributes=sp.attributes.filter(a=>!samlAppOidcFields.has(a.id)&&!['clientSecretApp','authorizationHeaderApp'].includes(a.id));
      idp.attributes=idp.attributes.filter(a=>!samlAppOidcFields.has(a.id));
      sp.notes=['SP entityID urn:example:app:sp is registered as the Keycloak SAML Client ID and appears in AuthnRequest.Issuer / assertion Audience.','HTTPS ACS app.example.test/saml/acs receives the browser POST.','No OAuth client_id, callback code, PKCE or OIDC token appears on this SAML app hop.',c.initiation==='idp'?'Explicitly permits unsolicited responses; request correlation is absent and login-CSRF risks need a deliberate policy.':'Stores its AuthnRequest ID and opaque RelayState with the pending browser transaction.'];
    }else{
      sp.attributes=sp.attributes.filter(a=>!samlBrokerOidcFields.has(a.id));idp.attributes=idp.attributes.filter(a=>!samlBrokerOidcFields.has(a.id)&&!['realmSigningKey','idTokenA','accessTokenA','codeA'].includes(a.id));
    }
    for(const id of [h.entityId,h.acsId,h.idpId,h.ssoId,h.idpCertificate])add(h.sp,id,'static');
    if(h.initiation==='sp')for(const id of [h.requestId,h.relayId,'samlAuthnRequest','samlRequest',c.binding==='redirect'?'samlRedirectSignature':'samlXmlSignature'])add(h.sp,id,'generated');
    else{add(h.sp,'samlUnsolicitedPolicy','static');add(h.sp,h.relayId,'received');}
    if(h.initiation==='sp'){add(h.sp,h.spSigningKey,'static');add(h.issuer,h.spCertificate,'static');add(h.issuer,h.requestId,'received');}
    for(const id of [h.entityId,h.acsId,h.idpId,h.ssoId,h.idpSigningKey])add(h.issuer,id,'static');
    for(const id of [h.responseId,h.assertionId,h.nameId,h.audienceId,h.recipientId,h.contextId,h.sessionId,'samlAssertion','samlResponseXml','samlResponse','samlXmlSignature'])add(h.issuer,id,'generated');
    for(const id of [h.responseId,h.assertionId,h.nameId,h.audienceId,h.recipientId,h.contextId,h.sessionId,'samlResponse','samlReplayState'])add(h.sp,id,id==='samlReplayState'?'generated':'received');
    if(c.encryptAssertions){add(h.issuer,h.encryptionCert,'static');add(h.issuer,'samlContentEncryptionKey','generated');add(h.issuer,'samlEncryptedAssertion','generated');add(h.issuer,'samlEncryptedKey','generated');add(h.sp,h.decryptionKey,'static');add(h.sp,'samlEncryptedAssertion','received');add(h.sp,'samlContentEncryptionKey','generated');add('browser','samlEncryptedAssertion','received');}
    else add('browser','samlAssertion','received');
    for(const id of [...(h.initiation==='sp'?['samlRequest']:[]),'samlResponse',h.relayId])add('browser',id,'received');
    idp.notes.push('SAML SP entityID identifies registration; Audience is that entityID while Recipient is the ACS URL.','This example configures signed Assertion and signed Response; encryption optionally wraps the signed Assertion using XML Encryption, not JWE.');
  }
  actors.realmA.role=(c.applicationProtocol==='saml'?'SAML IdP':'OIDC provider')+(c.upstream==='single'?' + authentication verifier':' + identity broker');
  actors.realmA.plainRole=c.upstream==='single'?'Authenticates the person and issues the application’s selected-protocol result.':'Validates the upstream identity, maps its local account and issues the application’s selected-protocol result.';
  if(c.upstream!=='single'&&c.brokerProtocol==='saml'){actors.realmB.name=c.upstream==='external'?'External SAML IdP':'IdP 2 · Realm B';actors.realmB.role='SAML IdP + selected factor verifier';actors.realmB.plainRole='Authenticates the person and returns a signed SAML result to A.';}
  actors.browser.notes.push('SAML requests use the selected Redirect/POST binding; responses are always browser POSTs to the registered ACS.','POST XML signatures do not sign the separate RelayState control. Private signing/decryption keys stay on servers.');
  samlActorCache.set(key,actors);return actors;
}
