import { labAttribute, labP, labOp, labWire, labStep, labScenario } from './lab-common.js';

// All values and verification results are synthetic. The application/API parts
// are teaching patterns; this file does not implement an OAuth client or server.
const webLabOAuth = 'https://www.rfc-editor.org/rfc/rfc6749';
const webLabPkce = 'https://www.rfc-editor.org/rfc/rfc7636';
const webLabBearer = 'https://www.rfc-editor.org/rfc/rfc6750';
const webLabIntrospection = 'https://www.rfc-editor.org/rfc/rfc7662';
const webLabJwt = 'https://www.rfc-editor.org/rfc/rfc7519';
const webLabJws = 'https://www.rfc-editor.org/rfc/rfc7515';
const webLabJwk = 'https://www.rfc-editor.org/rfc/rfc7517';
const webLabJwtBcp = 'https://www.rfc-editor.org/rfc/rfc8725';
const webLabOidc = 'https://openid.net/specs/openid-connect-core-1_0.html';
const webLabAdapter = 'https://www.keycloak.org/securing-apps/javascript-adapter';
const webLabLayers = 'https://www.keycloak.org/securing-apps/oidc-layers';
const webLabAdmin = 'https://www.keycloak.org/docs/latest/server_admin/index.html';
const webLabFetch = 'https://fetch.spec.whatwg.org/#http-cors-protocol';
const webLabIssuer = 'https://idp1.example.test/realms/realm-a';
const webLabAuth = webLabIssuer + '/protocol/openid-connect/auth';
const webLabToken = webLabIssuer + '/protocol/openid-connect/token';
const webLabJwks = webLabIssuer + '/protocol/openid-connect/certs';
const webLabIntrospect = webLabToken + '/introspect';
const webLabSpaOrigin = 'https://spa.example.test';
const webLabSpaCallback = webLabSpaOrigin + '/callback';
const webLabBffOrigin = 'https://app.example.test';
const webLabBffCallback = webLabBffOrigin + '/oidc/callback';
const webLabApiUrl = 'https://api.example.test/orders';
const webLabVerifier = 'dBjftJeZ4CVP-mB92K27uhbUJU1p1r_wW1gFWFOEjXk';
const webLabChallenge = 'E9Melhoa2OwvFrEMTJguCHaoeK1t8URWbuGJSstw-cM';
const webLabA = (name, meaning, origin, purpose, example, standard, source) => labAttribute(name, meaning, origin, purpose, example, standard, source);

export const WEBLAB_ATTRIBUTES = {
  webClientId: webLabA('client_id', 'The application’s public client-registration identifier.', 'Assigned during client registration in Realm A and configured in SPA code or the BFF backend.', 'Selects the client registration; binds the code and ID-token audience. A SPA is public and cannot protect a client_secret; the BFF can authenticate with its own server credential.', 'spa-public', 'RFC 6749 §2.2 / OIDC Core §2', webLabOAuth),
  webClientSecret: webLabA('client_secret', 'The BFF’s protected confidential-client credential.', 'Provisioned for bff-web in A and retained on the backend.', 'Authenticates BFF code redemption. It never enters SPA JavaScript, browser redirects, cookies or API bearer requests.', 'Backend-only secret; not a real credential', 'RFC 6749 §2.3.1', webLabOAuth),
  webClientAuth: webLabA('Authorization (client authentication)', 'The BFF’s HTTP Basic client-authentication header.', 'Created locally from the registered client identifier and server-only secret.', 'Authenticates the confidential client at A’s token endpoint; distinct from Authorization: Bearer used for APIs.', 'Basic base64(encoded-bff-web:encoded-secret)', 'RFC 6749 §2.3.1', webLabOAuth),
  webRedirectUri: webLabA('redirect_uri', 'The exact registered callback URI of the OIDC client.', 'Configured in the client and registered in A.', 'For a pure SPA this loads the SPA route, where browser JavaScript handles code/state. For a BFF the browser calls a backend callback, where the server handles them.', webLabSpaCallback, 'RFC 6749 §3.1.2 / §4.1.3', webLabOAuth),
  webResponseType: webLabA('response_type', 'Requests an authorization code.', 'Set by the requesting client.', 'Keeps the token response on the separate token-endpoint exchange.', 'code', 'OIDC Core §3.1.2.1', webLabOidc),
  webRequestScope: webLabA('scope (authorization request)', 'The requested identity and API permission scopes.', 'Chosen by the client and constrained by realm policy and client-scope configuration.', 'openid requests an ID token; the configured orders:read scope and audience mapping determine access to the illustrated API.', 'openid profile orders:read', 'RFC 6749 §3.3 / OIDC Core §3.1.2.1', webLabOAuth),
  webState: webLabA('state', 'A fresh random correlation value for this browser authorization attempt.', 'Generated and retained by SPA JavaScript in the browser, or by the BFF on its backend.', 'The actual client checks the returned value before accepting its callback; it is not a client password or API permission.', 'st_web_demo_1', 'RFC 6749 §4.1.1 / §10.12', webLabOAuth),
  webNonce: webLabA('nonce', 'A fresh request value expected in this client’s ID token.', 'Generated and retained by the SPA or BFF before its OIDC request.', 'The client compares the ID-token nonce with the original value. It is not forwarded as an API permission or separate access-token parameter.', 'n_web_demo_1', 'OIDC Core §3.1.2.1 / §3.1.3.7', webLabOidc),
  webVerifier: webLabA('code_verifier', 'The high-entropy per-attempt PKCE secret.', 'Created and retained by the actual OAuth client: browser JavaScript for SPA; backend for BFF.', 'Sent only by that client to A’s token endpoint. It is absent from authorization redirects, API requests and the BFF’s browser session cookie.', webLabVerifier, 'RFC 7636 §4.1 / §4.5', webLabPkce),
  webChallenge: webLabA('code_challenge', 'The public S256 commitment to code_verifier.', 'Derived by the actual client as BASE64URL(SHA256(ASCII(code_verifier))) without padding.', 'A binds it to the code and recomputes it locally from the submitted verifier during redemption.', webLabChallenge, 'RFC 7636 §4.2 / §4.6', webLabPkce),
  webChallengeMethod: webLabA('code_challenge_method', 'Names the PKCE commitment method.', 'Selected by the client.', 'S256 requires the server to compare the SHA-256 commitment rather than receiving the original verifier through the browser authorization URL.', 'S256', 'RFC 7636 §4.2', webLabPkce),
  webCode: webLabA('code', 'The short-lived, single-use authorization code issued to this registered client.', 'Created by A after its required account authentication and authorization.', 'The SPA or BFF redeems it with the same redirect_uri and the original PKCE verifier; the code alone is not accepted as identity.', 'c_web_demo_1', 'RFC 6749 §4.1', webLabOAuth),
  webGrantType: webLabA('grant_type', 'Selects code redemption at the token endpoint.', 'Set by the client.', 'authorization_code selects exchange of the callback code with its required client/PKCE binding.', 'authorization_code', 'RFC 6749 §4.1.3', webLabOAuth),
  webLocation: webLabA('Location', 'The HTTP redirect target followed by the browser.', 'Constructed by the BFF or Realm A.', 'Contains the next authorization URL or callback code/state. The sender issues a redirect; the browser then performs navigation.', '302 → registered callback?code=…&state=…', 'RFC 9110 §10.2.2', 'https://www.rfc-editor.org/rfc/rfc9110'),
  webAuthContext: webLabA('Verified account context (local state)', 'The realm’s protected record that its configured account checks and authorization requirements succeeded.', 'Established by A’s configured browser authentication flow.', 'A issues a code only after the required password/passkey/MFA method and authorization policy complete. Detailed credential ceremonies are covered by the main diagram; this lab treats their successful completion as one stage.', 'Verified Realm A account user-204', 'Keycloak browser authentication; implementation-specific state', webLabAdmin),
  webIdToken: webLabA('id_token', 'A signed OIDC identity statement intended for the SPA or BFF client.', 'Signed by Realm A after the protected code exchange.', 'The client checks signature/issuer/client audience/time/nonce before accepting account identity. The illustrated Orders API accepts an access_token rather than this ID token.', 'ID-token JWS: aud=spa-public, nonce=n_web_demo_1', 'OIDC Core §2 / §3.1.3.7', webLabOidc),
  webAccessToken: webLabA('access_token', 'The authorization credential for the illustrated resource API.', 'Issued by A according to approved scopes and configured API audience mapping.', 'Carried as Authorization: Bearer on API requests. A JWT API validates signature, issuer, API audience, expiry and permissions; a lightweight/opaque-token API can use authenticated introspection.', 'Access-token JWS: aud=orders-api, scope=orders:read', 'RFC 6749 §1.4 / RFC 6750', webLabBearer),
  webRefreshToken: webLabA('refresh_token', 'An optional credential for obtaining new tokens from A.', 'Issued if the client/realm policy permits.', 'For SPA it remains in browser memory; for BFF it remains on the backend. This lab shows issuance/storage, with refresh redemption in the separate refresh lifecycle lab.', 'Optional, according to policy', 'RFC 6749 §1.5', webLabOAuth),
  webTokenType: webLabA('token_type', 'The access-token usage scheme.', 'Included by A in the token response.', 'Bearer means that possession of the access token authorizes its presentation; TLS and appropriate storage protect it.', 'Bearer', 'RFC 6749 §5.1 / RFC 6750', webLabOAuth),
  webExpiresIn: webLabA('expires_in', 'The access-token lifetime in seconds from issuance.', 'Set by the issuing realm.', 'Helps the client decide whether it must obtain fresh authorization before a request; the API still enforces token validity independently.', '300', 'RFC 6749 §5.1', webLabOAuth),
  webIssuer: webLabA('iss', 'The exact trusted issuer inside the token or introspection result.', 'Set by Realm A.', 'The recipient verifies the expected realm; the same user name from a different issuer does not identify the same trusted account.', webLabIssuer, 'RFC 7519 §4.1.1 / OIDC Core §2', webLabJwt),
  webIdAudience: webLabA('aud (ID token)', 'The intended OIDC client recipient of the ID token.', 'Set by A to include the requesting client identifier.', 'The SPA/BFF compares it with its own client_id. It is separate from the access token’s intended API audience.', 'spa-public', 'OIDC Core §2 / §3.1.3.7', webLabOidc),
  webApiAudience: webLabA('aud (access token / introspection)', 'The intended recipient of the API authorization credential.', 'Set by configured audience mappers or the issuer’s authorization policy.', 'The Orders API requires aud to include orders-api. An ID token whose aud names the SPA does not satisfy this API policy.', 'orders-api', 'RFC 7519 §4.1.3 / RFC 7662 §2.2', webLabJwt),
  webExpectedApiAudience: webLabA('Expected audience (local API policy)', 'The recipient identifier this API requires in an access token’s aud claim.', 'Configured locally in Orders API as orders-api; it is not supplied by the requesting client.', 'The API compares the received aud against its own identity. A signed and unexpired token for other-api is rejected before permission checks, even when its scope names orders:read. This local value is not a JWT claim or request parameter.', 'orders-api', 'RFC 7519 §4.1.3; application-specific recipient policy', webLabJwt),
  webSubject: webLabA('sub', 'The trusted token subject within the issuer.', 'Assigned by A and included in the token or introspection result.', 'After validation the application/API can identify the authorized account as an issuer/subject pair; knowing sub alone grants no access.', 'user-204', 'RFC 7519 §4.1.2 / RFC 7662 §2.2', webLabJwt),
  webExpiry: webLabA('exp', 'The instant after which the token must no longer be accepted.', 'Set by the issuer as NumericDate.', 'The recipient rejects an expired token. An introspection response can supply exp, but active=true alone is not the API’s complete permission decision.', 'iat + 300', 'RFC 7519 §4.1.4 / RFC 7662 §2.2', webLabJwt),
  webIssuedAt: webLabA('iat', 'The token issuance time as NumericDate.', 'Set by A.', 'Used with the configured validity and claim policy; it is not an expiry replacement.', 'Unix-epoch seconds', 'RFC 7519 §4.1.6', webLabJwt),
  webApiScope: webLabA('scope (access token / introspection)', 'The permissions actually granted to this access token.', 'Chosen by the issuer from approved scopes and configured policies.', 'The API checks required permissions against granted values. Token validity and permissions are separate checks.', 'orders:read', 'RFC 6749 §3.3 / RFC 7662 §2.2', webLabOAuth),
  webPermissions: webLabA('Required API permissions (local policy)', 'The API’s application-specific authorization requirement for an operation.', 'Configured in the protected Orders API.', 'A valid token still receives 403 if its granted scope/roles do not satisfy this requirement. This local policy is not transmitted as a claim.', 'GET /orders requires orders:read', 'RFC 6750 §3.1; application-specific authorization policy', webLabBearer),
  webBearerHeader: webLabA('Authorization (API bearer token)', 'The HTTP header carrying the client’s access token to the resource API.', 'Created by browser JavaScript, the BFF or an authorized API client.', 'Bearer <access_token> authorizes the API call. It is distinct from Basic client authentication and from an opaque BFF session cookie.', 'Bearer <access-token-JWS>', 'RFC 6750 §2.1', webLabBearer),
  webSignature: webLabA('JWS Signature', 'The signature segment of a compact signed JWT.', 'Computed by A using its retained signing private key.', 'The recipient verifies it with a trusted public key and an allowed algorithm before trusting the decoded claims.', 'Third JWS compact segment', 'RFC 7515 §3.1 / §5.2', webLabJws),
  webAlgorithm: webLabA('alg', 'The signature algorithm named by the JOSE header.', 'Set by the signer; initially untrusted until token verification.', 'The recipient enforces a configured algorithm allowlist and appropriate key type. It must not accept a token merely because its own header requests an algorithm.', 'RS256 (illustrative allowed algorithm)', 'RFC 7515 §4.1.1 / RFC 8725 §3.1', webLabJwtBcp),
  webKid: webLabA('kid', 'The key identifier in a JOSE header or public JWK.', 'Assigned by the issuer to its signing keys and copied into signed-token headers.', 'Selects a candidate from trusted issuer keys. An unfamiliar kid can trigger one bounded refresh of the trusted JWKS; kid itself is not proof of trust.', 'realm-sign-2', 'RFC 7515 §4.1.4 / RFC 7517 §4.5 / OIDC Core §10.1.1', webLabJwk),
  webJwksUri: webLabA('jwks_uri', 'The trusted issuer URL for its public signing keys.', 'Configured or obtained from issuer-validated OIDC discovery.', 'The recipient loads public keys only from its configured trusted issuer. It does not turn an arbitrary token jku into a fetch destination.', webLabJwks, 'OIDC Discovery §3 / OIDC Core §10.1.1', 'https://openid.net/specs/openid-connect-discovery-1_0.html'),
  webKeys: webLabA('keys', 'The array of public keys inside a JSON Web Key Set.', 'Published by A’s trusted key endpoint.', 'Supplies public verification material. Signing private-key members are excluded from the published JWKS.', '{"keys":[{"kty":"RSA","kid":"realm-sign-1","use":"sig","n":"…","e":"AQAB"},{"kty":"RSA","kid":"realm-sign-2","use":"sig","n":"…","e":"AQAB"}]}', 'RFC 7517 §5 / §9.2', webLabJwk),
  webSigningPrivateKey: webLabA('Issuer signing private key (local)', 'The protected private key with which A signs tokens.', 'Generated/provisioned and retained by A’s key provider.', 'Used locally to produce JWS signatures. Public verification keys are published; this private key never travels in tokens or JWKS.', 'Realm A private key for realm-sign-2; local only', 'RFC 7515 / RFC 7517 §9.2', webLabJwk),
  webKeyCache: webLabA('Trusted JWKS cache (local state)', 'The verifier’s retained public issuer key set and cache metadata.', 'Loaded from the trusted jwks_uri according to the verifier’s caching policy.', 'Avoids fetching keys for every request. A new kid can trigger bounded refresh, then full verification; cached keys do not waive expiry or authorization checks.', 'Before rotation: realm-sign-1; after refresh: realm-sign-1 + realm-sign-2', 'OIDC Core §10.1.1; application-specific caching', webLabOidc),
  webRefreshBudget: webLabA('JWKS retry budget (local policy)', 'The verifier’s bound on key-refresh attempts for one unverified token.', 'Configured by the API’s token verifier.', 'This teaching policy permits one trusted-JWKS refresh for unknown kid, with rate limiting/cache control. If no trusted matching key appears, reject the token rather than looping or fetching arbitrary URLs.', 'One refresh for this request', 'RFC 8725 §3.10; application-specific resource limits', webLabJwtBcp),
  webJku: webLabA('jku', 'An optional JOSE header URL suggesting a JWK Set.', 'Provided by a token’s creator; untrusted before token validation.', 'An API with issuer-pinned JWKS policy ignores arbitrary jku/embedded-key hints and never uses them to replace the trusted verification source. No jku is required by this rotation example.', 'An arbitrary token-provided URL must not be followed', 'RFC 7515 §4.1.2 / RFC 8725 §3.10', webLabJwtBcp),
  webSession: webLabA('BFF session (local state)', 'The backend’s mapping from an opaque session handle to the verified account and server-held tokens.', 'Created by the BFF after validating the OIDC result.', 'The browser uses a cookie while access/refresh tokens and PKCE material remain on the backend. Server-side session expiry and CSRF controls remain application responsibilities.', 'Opaque handle → validated account + protected server token store', 'Application-specific session architecture', webLabOAuth),
  webCookie: webLabA('Set-Cookie / Cookie (BFF session)', 'The HTTP cookie containing an opaque application session handle.', 'Issued by the BFF after account validation and retained by the browser.', 'References the server-held session without carrying OAuth tokens. Secure, HttpOnly and a suitable SameSite policy reduce exposure; state-changing cookie requests also need appropriate CSRF protection.', '__Host-bff_session=<opaque>; Secure; HttpOnly; SameSite=Lax; Path=/', 'RFC 6265; modern cookie attributes; application policy', 'https://www.rfc-editor.org/rfc/rfc6265'),
  webOrigin: webLabA('Origin', 'The browser’s originating web-site identifier on a cross-origin request.', 'Set by the browser.', 'The API/token endpoint matches its allowed origins for CORS. An allowed origin is not authentication or API authorization.', webLabSpaOrigin, 'Fetch Standard §3.2 / §3.3', webLabFetch),
  webAllowOrigin: webLabA('Access-Control-Allow-Origin', 'The response header allowing a particular browser origin to read a cross-origin response.', 'Configured and emitted by the API or token endpoint.', 'Makes the authorized browser interaction readable to SPA JavaScript. This lab uses an exact origin; CORS does not replace token validation.', webLabSpaOrigin, 'Fetch Standard §3.3', webLabFetch),
  webRequestedHeaders: webLabA('Access-Control-Request-Headers', 'The browser preflight header listing non-safelisted request header names.', 'Created by the browser before a cross-origin fetch with Authorization.', 'Requests permission to send authorization; the preflight contains no bearer token.', 'authorization', 'Fetch Standard §3.3 / §4.8', webLabFetch),
  webRequestedMethod: webLabA('Access-Control-Request-Method', 'The browser preflight header naming the intended HTTP method.', 'Created by the browser.', 'The API’s CORS policy decides whether to permit the cross-origin method. This preflight is independent of API token authentication.', 'GET', 'Fetch Standard §3.3 / §4.8', webLabFetch),
  webAllowedHeaders: webLabA('Access-Control-Allow-Headers', 'The preflight response list of allowed request header names.', 'Set by the API’s configured CORS policy.', 'Permits the browser to send authorization on its actual API request; no token is sent in this header.', 'authorization', 'Fetch Standard §3.3', webLabFetch),
  webAllowedMethods: webLabA('Access-Control-Allow-Methods', 'The preflight response list of permitted cross-origin methods.', 'Set by the API’s CORS policy.', 'Allows the corresponding browser fetch while the API still independently checks token and permissions.', 'GET', 'Fetch Standard §3.3', webLabFetch),
  webIntrospectionEndpoint: webLabA('introspection_endpoint', 'The trusted HTTPS endpoint used by an authorized API to inspect a token.', 'Configured from the trusted realm metadata or endpoint documentation.', 'Allows an API to obtain active status and configured authorization claims. Keycloak permits confidential clients to call this endpoint.', webLabIntrospect, 'RFC 7662 §2', webLabIntrospection),
  webIntrospectionClientId: webLabA('client_id (introspection client)', 'The resource API’s own confidential-client registration identifier.', 'Registered for the protected API in A.', 'Identifies the API’s authenticated introspection request; it is not the original SPA client or end-user identity.', 'orders-api-introspection', 'RFC 7662 §2.1 / RFC 6749 §2.2', webLabIntrospection),
  webIntrospectionSecret: webLabA('client_secret (introspection client)', 'The protected resource API credential for authenticated introspection.', 'Provisioned for the API’s confidential registration and retained by the API.', 'Authenticates the API at the introspection endpoint. It never enters the SPA, BFF user cookie or access-token claims.', 'API-only secret; not a real credential', 'RFC 7662 §2.1', webLabIntrospection),
  webIntrospectionAuth: webLabA('Authorization (introspection client)', 'The API’s HTTP Basic authentication header for its introspection call.', 'Created from the API’s own client identifier and secret.', 'Authorizes this confidential API to query token status. It is distinct from the incoming user bearer token carried in the request body.', 'Basic base64(encoded-orders-api-introspection:encoded-secret)', 'RFC 7662 §2.1', webLabIntrospection),
  webIntrospectionToken: webLabA('token', 'The token under inspection in the introspection form body.', 'Copied from the access_token the API received.', 'Queries the exact presented credential without substituting an ID token or an API client-authentication credential.', '<presented access_token>', 'RFC 7662 §2.1', webLabIntrospection),
  webTokenTypeHint: webLabA('token_type_hint', 'The optional hint indicating the kind of token being introspected.', 'Set by the querying API.', 'access_token helps the issuer locate the credential; it does not make an inactive or invalid token acceptable.', 'access_token', 'RFC 7662 §2.1', webLabIntrospection),
  webActive: webLabA('active', 'The required Boolean token status in an introspection result.', 'Determined by A after checking its token state and query authorization.', 'The API requires active=true and still checks audience, lifetime and permissions. active=false is a successful HTTP 200 introspection answer about an unusable token, not an introspection-client authentication error.', 'true; inactive branch: false', 'RFC 7662 §2.2 / §2.3', webLabIntrospection),
  webChallengeHeader: webLabA('WWW-Authenticate', 'The resource API’s HTTP bearer challenge header.', 'Constructed by the API when access cannot be accepted.', '401 invalid_token identifies an invalid credential; 403 insufficient_scope identifies a valid token lacking required permission. The error members in this lab are header auth-params, not invented JSON token-endpoint errors.', 'Bearer error="invalid_token"', 'RFC 6750 §3 / §3.1', webLabBearer),
  webBearerError: webLabA('error (WWW-Authenticate auth-param)', 'The RFC bearer challenge error value.', 'Chosen by the API after authentication or permission checks fail.', 'invalid_token accompanies the illustrated 401; insufficient_scope accompanies the illustrated 403. These are alternative request outcomes, not successive automatic stages of one token.', 'invalid_token / insufficient_scope', 'RFC 6750 §3.1', webLabBearer),
  webRequiredScope: webLabA('scope (WWW-Authenticate auth-param)', 'The required scope advertised in an insufficient-scope bearer challenge.', 'Set by the API according to its protected-operation policy.', 'Explains the missing permission in the illustrated 403 without granting it. A client must obtain authorized additional scope through the issuer’s policy.', 'orders:write', 'RFC 6750 §3 / §3.1', webLabBearer),
  webHttpStatus: webLabA('HTTP status', 'The outcome status of the API response.', 'Selected by the API after authentication and authorization.', '200 returns the resource, 401 rejects an invalid token, and 403 rejects insufficient permission. The challenge error is carried in WWW-Authenticate.', '200 / 401 / 403', 'RFC 9110 / RFC 6750 §3.1', webLabBearer),
  webResource: webLabA('Protected resource representation', 'The application data returned after API authorization succeeds.', 'Produced by the resource API.', 'The authorized client can display/use the requested orders. Its structure is application-specific and is not an OAuth token or identity claim.', '{"orders":[{"id":"order-101"}]}', 'Application-specific HTTPS response body', 'https://www.rfc-editor.org/rfc/rfc9110'),
};

export const WEBLAB_SOURCES = [
  { label: 'Keycloak JavaScript adapter · public SPA, Code + PKCE, memory storage', url: webLabAdapter },
  { label: 'Keycloak OIDC layers · confidential introspection and public keys', url: webLabLayers },
  { label: 'Keycloak · lightweight access tokens and audience configuration', url: webLabAdmin },
  { label: 'RFC 6750 · bearer requests and 401 / 403 challenges', url: webLabBearer },
  { label: 'RFC 7662 · authenticated introspection', url: webLabIntrospection },
  { label: 'OIDC Core · ID-token validation and signing-key rotation', url: webLabOidc },
  { label: 'RFC 8725 · JWT algorithm and key-source trust', url: webLabJwtBcp },
  { label: 'Fetch Standard · browser CORS and preflight', url: webLabFetch },
];

const webLabP = (id, value, description) => labP(WEBLAB_ATTRIBUTES[id].name, value === undefined ? WEBLAB_ATTRIBUTES[id].example : value, description, id);
const webLabS = (id, title, from, to, operations, payload, summary, detail, checks = [], phase = 'tokens') => labStep(id, title, from, to, phase, from === to ? 'internal' : ['user'].includes(from) ? 'local' : 'https', summary, detail, [...new Set(operations.map(action => action.attributeId))], payload, checks, operations);
const webLabOp = (ids, kind, actor, detail) => labOp(ids, kind, actor, detail);
const webLabWire = (ids, from, to, detail, carriedAs) => labWire(ids, from, to, detail, carriedAs);
const webLabRequestIds = ['webClientId', 'webRedirectUri', 'webResponseType', 'webRequestScope', 'webState', 'webNonce', 'webChallenge', 'webChallengeMethod'];
const webLabIdClaims = ['webIssuer', 'webIdAudience', 'webSubject', 'webNonce', 'webExpiry', 'webIssuedAt'];
const webLabAccessClaims = ['webIssuer', 'webApiAudience', 'webSubject', 'webExpiry', 'webIssuedAt', 'webApiScope'];
const webLabJose = ['webSignature', 'webAlgorithm', 'webKid'];
const webLabTokenFields = ['webIdToken', 'webAccessToken', 'webTokenType', 'webExpiresIn'];
const webLabAttrsFor = (client = 'spa-public', callback = webLabSpaCallback) => ({ ...WEBLAB_ATTRIBUTES, webClientId: { ...WEBLAB_ATTRIBUTES.webClientId, example: client }, webRedirectUri: { ...WEBLAB_ATTRIBUTES.webRedirectUri, example: callback }, webIdAudience: { ...WEBLAB_ATTRIBUTES.webIdAudience, example: client }, webIdToken: { ...WEBLAB_ATTRIBUTES.webIdToken, example: 'ID-token JWS: aud=' + client + ', nonce=n_web_demo_1' } });
const webLabIssuerActor = { name: 'Keycloak · Realm A', role: 'Authorization server / OIDC provider', plainRole: 'Verifies your account and issues identity and API authorization tokens.', notes: ['The configured client scopes and audience mappers must make the access token valid for the intended API.', 'Its token signing private key stays in this realm.'], art: 'realmA' };
const webLabApiActor = { name: 'Orders API', role: 'OAuth resource server', plainRole: 'Checks the access token and permissions before returning orders.', notes: ['Accepts the configured access-token type and API audience.', 'A valid signature alone does not grant the required permission.', 'The ID token and BFF session cookie do not replace this API access token.'], art: 'webapp' };
const webLabBrowserActor = { name: 'Browser · SPA JavaScript', role: 'Public browser OAuth client', plainRole: 'Runs the web app, handles its callback and calls the API.', notes: ['A pure SPA cannot safely retain a client secret.', 'PKCE verifier, state and nonce belong to this browser client.', 'Tokens remain in memory in this teaching pattern; code exchange occurs in browser JavaScript.'], art: 'browser' };
const webLabClientActor = { name: 'Authorized API client', role: 'Application holding an access token', plainRole: 'Calls the protected API using the appropriate access token.', notes: ['The token’s original grant completed before this focused API walkthrough.', 'This client does not supply API introspection credentials.'], art: 'webapp' };

function webLabPrepare(id, clientActor, client, callback) {
  return webLabS(id, 'Create local OIDC and PKCE protections', clientActor, clientActor, [...webLabOp(['webClientId', 'webRedirectUri', 'webRequestScope', 'webChallengeMethod'], 'use', clientActor, 'Reads registered client and request policy.'), ...webLabOp(['webState', 'webNonce', 'webVerifier'], 'create', clientActor, 'Creates fresh independent state, nonce and PKCE verifier locally.'), ...webLabOp(['webChallenge'], 'derive', clientActor, 'Computes BASE64URL(SHA256(ASCII(code_verifier))) without padding.'), ...webLabOp(['webState', 'webNonce', 'webVerifier'], 'store', clientActor, 'Retains one-time protections at the actual client until its callback and token validation.')], [webLabP('webClientId', client), webLabP('webRedirectUri', callback), webLabP('webState'), webLabP('webNonce'), webLabP('webVerifier', undefined, 'Local secret; not sent in the authorization URL.'), webLabP('webChallenge'), webLabP('webChallengeMethod')], 'The actual client creates the protections that only it will later verify.', clientActor === 'browser' ? 'SPA JavaScript generates and retains these values in its browser context. The registered HTTPS callback returns to the SPA route, where JavaScript processes the result. This public client uses no client_secret. Its static hosting server is not the OAuth callback handler or token exchanger.' : 'The BFF backend generates and retains the PKCE verifier, state and nonce and associates them with the requesting browser’s protected login transaction. The registered HTTPS callback is handled by this backend. Its client_secret also stays server-side.', [], 'prepare');
}
function webLabTokenResult(id, recipient, client) {
  return webLabS(id, 'Return separate identity and API tokens', 'realmA', recipient, [...webLabOp(['webSigningPrivateKey'], 'use', 'realmA', 'Signs the tokens using the issuer private key retained locally.'), ...webLabOp([...webLabTokenFields, 'webRefreshToken', 'webIdAudience', 'webApiAudience', 'webApiScope', 'webExpiry', 'webIssuedAt', 'webSignature', 'webAlgorithm', 'webKid'], 'create', 'realmA', 'Issues the approved tokens and recipient-specific audiences; refresh token is optional by policy.'), ...webLabOp(['webIssuer', 'webSubject', 'webNonce'], 'use', 'realmA', 'Places the trusted issuer, verified subject and original OIDC nonce into the ID token.'), ...webLabWire(webLabTokenFields, 'realmA', recipient, 'Top-level members of the HTTPS token response.', 'token response body'), ...webLabWire(['webRefreshToken'], 'realmA', recipient, 'Optional refresh_token if policy permits issuance.', 'optional token response member'), ...webLabWire(webLabIdClaims, 'realmA', recipient, 'Claims inside id_token; its audience is the OIDC client.', 'id_token claims'), ...webLabWire(webLabAccessClaims, 'realmA', recipient, 'Claims inside access_token; its audience and granted permissions target the API.', 'access_token claims'), ...webLabWire(webLabJose, 'realmA', recipient, 'Public JOSE header and signature members nested in the issued JWTs.', 'token JWT header / signature'), ...(recipient === 'browser' ? webLabWire(['webAllowOrigin'], 'realmA', recipient, 'Allows the configured SPA origin to read this token response; does not authenticate the user.', 'HTTP CORS response header') : [])], [labP('HTTP', '200 OK'), webLabP('webIdToken', 'ID-token JWS: aud=' + client + ', nonce=n_web_demo_1'), webLabP('webAccessToken'), webLabP('webTokenType'), webLabP('webExpiresIn'), webLabP('webRefreshToken', undefined, 'Optional; only if policy permits'), webLabP('webIdAudience', client, 'Inside id_token'), webLabP('webApiAudience', undefined, 'Inside access_token'), webLabP('webApiScope', undefined, 'Inside access_token'), ...(recipient === 'browser' ? [webLabP('webAllowOrigin')] : [])], 'A sends an ID token for the client and an access token for the API.', 'The ID token targets ' + client + '; the separately issued access token targets orders-api through explicit audience configuration. The original request nonce is an ID-token check, not an API permission. A permitted refresh token is optional. This synthetic walkthrough uses signed JWT access tokens; no issuer signing private key is transmitted.', ['Code, client, redirect and PKCE binding verified']);
}
function webLabApiRequest(id, sender, detail = 'The client sends its access token to the resource API over HTTPS.') {
  return webLabS(id, 'Present the access token to Orders API', sender, 'realmB', [...webLabOp(['webAccessToken', 'webTokenType'], 'use', sender, 'Uses the access token intended for this API, not an ID token.'), ...webLabOp(['webBearerHeader'], 'derive', sender, 'Constructs Authorization: Bearer <access_token>.'), ...webLabWire(['webBearerHeader', 'webAccessToken'], sender, 'realmB', 'Presents the API access credential in the Authorization bearer header.', 'Authorization: Bearer header'), ...webLabWire([...webLabAccessClaims, ...webLabJose], sender, 'realmB', 'Nested JWT claims/header/signature bytes carried inside the bearer access token.', 'Authorization → access_token JWT'), ...(sender === 'browser' ? webLabWire(['webOrigin'], sender, 'realmB', 'Browser supplies its actual request Origin for the API CORS check.', 'HTTP Origin request header') : [])], [labP('HTTP', 'GET ' + webLabApiUrl), webLabP('webBearerHeader'), webLabP('webApiAudience', undefined, 'Inside the access token'), webLabP('webApiScope', undefined, 'Inside the access token')], 'The API receives the authorization token it is configured to accept.', detail + ' The client does not present id_token, nonce, PKCE verifier, refresh_token, client_secret or application session cookie to this API. The decoded access-token claims remain untrusted until the API completes verification.');
}
function webLabApiVerify(id, title = 'Verify the access token and API permissions') {
  return webLabS(id, title, 'realmB', 'realmB', [...webLabOp(['webJwksUri', 'webKeys', 'webPermissions'], 'use', 'realmB', 'Uses trusted issuer public keys and local operation-permission policy.'), ...webLabOp(['webAlgorithm', 'webSignature', 'webIssuer', 'webApiAudience', 'webExpiry', 'webIssuedAt', 'webApiScope'], 'verify', 'realmB', 'Checks allowed algorithm and valid signature, exact trusted issuer, API audience, token validity and required granted permissions.'), ...webLabOp(['webSubject'], 'use', 'realmB', 'Uses the validated issuer/subject account identity for this authorized API request.')], [webLabP('webApiAudience'), webLabP('webApiScope'), webLabP('webPermissions')], 'The API checks both token trust and the operation’s permission.', 'Using its trusted issuer public-key cache, the API verifies the JWT signature and an allowed algorithm, exact iss, aud including orders-api, expiry and applicable time policy. It then checks orders:read against its own required permission policy. An ID token intended for the SPA cannot satisfy this illustrated API audience/type policy. Decoding a JWT or allowing CORS by itself grants no access.', ['Allowed algorithm + valid signature', 'Exact issuer + intended API audience', 'Token within accepted time window', 'Required API permission granted']);
}
function webLabResourceResponse(id, recipient, cors = false) {
  const step=webLabS(id, 'Return the protected orders', 'realmB', recipient, [...webLabOp(['webResource', 'webHttpStatus'], 'create', 'realmB', 'Creates a successful resource response only after validation and authorization.'), ...webLabWire(['webResource', 'webHttpStatus', ...(cors ? ['webAllowOrigin'] : [])], 'realmB', recipient, 'Returns the authorized resource representation and HTTP status.', 'HTTPS resource response')], [labP('HTTP', '200 OK', undefined, 'webHttpStatus'), webLabP('webResource'), ...(cors ? [webLabP('webAllowOrigin')] : [])], 'The authorized client receives its orders.', 'The response contains application data, not another authorization grant. ' + (cors ? 'The exact configured Access-Control-Allow-Origin also allows this SPA browser to read the response.' : 'The receiving client can use the resource after the API’s separate checks.'), [], 'complete');
  step.attributeValues={webHttpStatus:'200 OK'};
  return step;
}

const webLabSpaSteps = [
  webLabS('web-spa-start', 'Choose Sign in in the browser app', 'user', 'browser', [], [labP('Local action', 'Sign in')], 'The person starts sign-in in a Single Page Application.', 'SPA means a browser-run JavaScript application. Its static assets may be served over the network, while OAuth state and token exchange happen in the browser; it is not the confidential backend pattern.', [], 'prepare'),
  webLabPrepare('web-spa-prepare', 'browser', 'spa-public', webLabSpaCallback),
  webLabS('web-spa-authorize', 'Navigate to A with the public PKCE request', 'browser', 'realmA', [...webLabWire(webLabRequestIds, 'browser', 'realmA', 'Browser navigation carries the public authorization request, without code_verifier or client_secret.', 'authorization URL query'), ...webLabOp(['webClientId', 'webRedirectUri', 'webChallenge', 'webChallengeMethod'], 'verify', 'realmA', 'Checks the registered public client, exact permitted callback and S256 PKCE request.'), ...webLabOp(['webState', 'webNonce', 'webChallenge'], 'store', 'realmA', 'Retains the authorization request context while required account checks run.')], [labP('HTTP', 'GET ' + webLabAuth), ...webLabRequestIds.map(id => webLabP(id))], 'The browser asks A to authenticate and authorize its public SPA client.', 'The request includes client_id=spa-public, response_type=code, exact redirect_uri, requested scopes, state, nonce and the S256 public commitment. The browser-held verifier stays local. The realm uses its configured required account method; this is Authorization Code, not a password grant.', ['Registered public client', 'Exact HTTPS SPA callback', 'S256 request valid'], 'prepare'),
  webLabS('web-spa-login-page', 'Show the configured authentication method', 'realmA', 'browser', [], [labP('HTTPS page', 'Realm A account verification')], 'A presents its account authentication page.', 'Password, passkey and any required TOTP checks happen on A’s trusted page. The corresponding credential ceremonies are expanded in the main diagram; this focused SPA/API lab does not pretend a page display already authenticated the account.', [], 'password'),
  webLabS('web-spa-human-auth', 'Complete the required account checks', 'user', 'browser', [], [labP('Local action', 'Perform the configured password / passkey / MFA method')], 'The person completes the method required by the realm.', 'This stage abbreviates the selected credential ceremony; it does not transmit a generic authenticate parameter or expose password/passkey/TOTP secrets to the API.', [], 'password'),
  webLabS('web-spa-auth-complete', 'Verify account authentication and authorization', 'browser', 'realmA', [...webLabOp(['webAuthContext'], 'create', 'realmA', 'Records that the configured account checks and required authorization succeeded.'), ...webLabOp(['webAuthContext'], 'verify', 'realmA', 'Requires the completed account/authorization context before issuing a client-bound code.')], [labP('Provider-specific authentication actions', 'Required method verified; permissions approved according to policy')], 'A confirms the account and authorization requirements before returning a code.', 'The configured realm factor verifiers and authorization policy have completed. This summary step covers their provider-specific messages; webAuthContext is local realm state and is never a browser-supplied assertion of success.', ['Required account checks verified', 'Requested permissions allowed'], 'password'),
  webLabS('web-spa-code-return', 'Redirect to the actual SPA callback', 'realmA', 'browser', [...webLabOp(['webCode'], 'create', 'realmA', 'Creates a short-lived one-use code bound to client, redirect and PKCE commitment.'), ...webLabOp(['webLocation'], 'derive', 'realmA', 'Constructs the registered SPA callback URL with code and original state.'), ...webLabWire(['webLocation', 'webCode', 'webState'], 'realmA', 'browser', '302 redirect carries code and original state to the SPA callback URL.', 'Location callback URL')], [labP('HTTP', '302 Found'), webLabP('webLocation', webLabSpaCallback + '?code=c_web_demo_1&state=st_web_demo_1'), webLabP('webCode'), webLabP('webState')], 'The browser loads the SPA callback route with code and state.', 'This teaching request uses query response mode. The returned callback is an HTTPS SPA route, not localhost and not a backend token exchanger. The static page loads and its browser JavaScript reads the code/state; tokens have not been returned yet.', [], 'return'),
  webLabS('web-spa-callback', 'Handle the callback in SPA JavaScript', 'browser', 'browser', [...webLabOp(['webState', 'webRedirectUri'], 'verify', 'browser', 'Checks original state and the expected callback context before accepting the code.'), ...webLabOp(['webCode'], 'store', 'browser', 'Retains the callback code temporarily for redemption.'), ...webLabOp(['webVerifier'], 'use', 'browser', 'Retrieves the original browser-held PKCE verifier.')], [webLabP('webState'), webLabP('webCode')], 'The JavaScript client checks that this callback belongs to its own attempt.', 'The callback handler executes in browser JavaScript. It matches the returned state, restores its original verifier and clears one-time callback material after use. A hosting server that merely serves static assets does not receive the confidential client role.', ['Callback state matches original'], 'return'),
  webLabS('web-spa-token-request', 'Redeem the code directly from the browser', 'browser', 'realmA', [...webLabWire(['webClientId', 'webGrantType', 'webCode', 'webRedirectUri', 'webVerifier', 'webOrigin'], 'browser', 'realmA', 'SPA browser sends the public-client token request and browser Origin over HTTPS.', 'token endpoint form body + Origin header'), ...webLabOp(['webCode', 'webClientId', 'webRedirectUri'], 'verify', 'realmA', 'Checks the unexpired single-use code and original client/callback binding.'), ...webLabOp(['webChallenge'], 'derive', 'realmA', 'Recomputes S256 from received code_verifier locally.'), ...webLabOp(['webVerifier', 'webChallenge'], 'verify', 'realmA', 'Compares with the original PKCE commitment before issuing tokens.')], [labP('HTTP', 'POST ' + webLabToken), webLabP('webClientId'), webLabP('webGrantType'), webLabP('webCode'), webLabP('webRedirectUri'), webLabP('webVerifier'), webLabP('webOrigin')], 'The public SPA exchanges its code and original verifier with A.', 'The form includes client_id=spa-public, grant_type=authorization_code, code, identical redirect_uri and code_verifier. No client_secret is embedded in JavaScript. A’s configured Web Origins allow the exact SPA origin to read the token response; CORS does not replace the code/PKCE checks.', ['Single-use client-bound code', 'Exact callback', 'S256 verifier matches commitment']),
  webLabTokenResult('web-spa-tokens', 'browser', 'spa-public'),
  webLabS('web-spa-identity', 'Validate the OIDC result and retain tokens in memory', 'browser', 'browser', [...webLabOp(['webClientId', 'webJwksUri', 'webKeys'], 'use', 'browser', 'Uses its configured client identity and trusted issuer verification material.'), ...webLabOp(['webIdToken', 'webSignature', 'webAlgorithm', 'webIssuer', 'webIdAudience', 'webExpiry', 'webIssuedAt', 'webNonce'], 'verify', 'browser', 'Validates the OIDC ID-token result and original request nonce before accepting identity.'), ...webLabOp(['webIdToken', 'webAccessToken', 'webRefreshToken'], 'store', 'browser', 'Retains only issued tokens in browser memory, without localStorage persistence.')], [webLabP('webIdAudience'), webLabP('webNonce')], 'The SPA accepts the validated identity result and keeps its API access token.', 'This teaching OIDC client enforces trusted token-source/signature policy, exact issuer, its client audience, validity and original nonce. The current Keycloak JavaScript adapter stores tokens in memory; this lab does not claim that merely decoding a token cryptographically verifies it. API authorization remains the API’s independent responsibility.'),
  webLabS('web-spa-preflight', 'Ask permission for the cross-origin API header', 'browser', 'realmB', webLabWire(['webOrigin', 'webRequestedHeaders', 'webRequestedMethod'], 'browser', 'realmB', 'CORS preflight asks whether this SPA may send an Authorization header.', 'OPTIONS CORS preflight headers'), [labP('HTTP', 'OPTIONS ' + webLabApiUrl), webLabP('webOrigin'), webLabP('webRequestedHeaders'), webLabP('webRequestedMethod')], 'The browser sends a preflight without an access token.', 'A cross-origin fetch using the non-safelisted Authorization header requires CORS preflight unless a suitable preflight cache entry already exists. OPTIONS advertises the method and header names; it contains no bearer token and must not be treated as proof of account identity.'),
  webLabS('web-spa-preflight-allow', 'Allow this origin, method and header', 'realmB', 'browser', webLabWire(['webAllowOrigin', 'webAllowedMethods', 'webAllowedHeaders'], 'realmB', 'browser', 'Returns the API’s configured CORS permissions for this exact browser origin.', 'preflight response headers'), [labP('HTTP', '204 No Content'), webLabP('webAllowOrigin'), webLabP('webAllowedMethods'), webLabP('webAllowedHeaders')], 'The API permits the browser to make the intended request.', 'These headers permit browser access; they do not validate a bearer token or grant the required API scope. The API still authenticates and authorizes the actual GET separately.'),
  webLabApiRequest('web-spa-api-request', 'browser'),
  webLabApiVerify('web-spa-api-verify'),
  webLabResourceResponse('web-spa-api-response', 'browser', true),
];

const webLabBffSteps = [
  webLabS('web-bff-start', 'Ask the BFF to sign in', 'browser', 'app', [], [labP('HTTP', 'GET ' + webLabBffOrigin + '/login')], 'The web frontend asks its backend to start account sign-in.', 'BFF means Backend for Frontend. The browser runs the interface, while its same-origin backend is the confidential OAuth client. The person initiates this browser request; the browser will never hold the BFF’s token-store contents.', [], 'prepare'),
  webLabPrepare('web-bff-prepare', 'app', 'bff-web', webLabBffCallback),
  webLabS('web-bff-redirect', 'Redirect the browser with public request fields', 'app', 'browser', [...webLabOp(['webLocation'], 'derive', 'app', 'Builds A’s authorization URL containing only public OIDC request fields.'), ...webLabWire(['webLocation', ...webLabRequestIds], 'app', 'browser', 'HTTP redirect points to A with the backend’s public request values.', 'Location authorization URL')], [labP('HTTP', '302 Found'), webLabP('webLocation', webLabAuth), webLabP('webClientId', 'bff-web'), webLabP('webRedirectUri', webLabBffCallback), webLabP('webChallenge'), webLabP('webState'), webLabP('webNonce')], 'The browser receives an authorization URL, while the backend keeps its secrets.', 'The redirect includes the public PKCE challenge, state, nonce and registered BFF callback. The verifier and confidential client_secret remain on the backend.', [], 'prepare'),
  webLabS('web-bff-authorize', 'Navigate to the realm authorization page', 'browser', 'realmA', [...webLabWire(webLabRequestIds, 'browser', 'realmA', 'Browser delivers the BFF authorization request to A.', 'authorization URL query'), ...webLabOp(['webClientId', 'webRedirectUri', 'webChallenge', 'webChallengeMethod'], 'verify', 'realmA', 'Checks the registered BFF client, exact allowed callback and S256 request.'), ...webLabOp(['webState', 'webNonce', 'webChallenge'], 'store', 'realmA', 'Retains the BFF’s request context until authentication/authorization finish.')], [labP('HTTP', 'GET ' + webLabAuth), webLabP('webClientId', 'bff-web'), webLabP('webRedirectUri', webLabBffCallback), webLabP('webChallenge'), webLabP('webState'), webLabP('webNonce')], 'A uses its required account verification method.', 'A’s trusted browser page performs the configured password/passkey/MFA method. These credential ceremonies are expanded elsewhere in the main diagram; the BFF does not receive the account password, passkey private key or TOTP seed.', [], 'prepare'),
  webLabS('web-bff-account-check', 'Complete the realm’s required account checks', 'realmA', 'realmA', [...webLabOp(['webAuthContext'], 'create', 'realmA', 'Records successful configured account factor checks and required authorization.'), ...webLabOp(['webAuthContext'], 'verify', 'realmA', 'Requires the verified account and allowed permissions before issuing the code.')], [labP('Local result', 'Configured account authentication and authorization verified')], 'A verifies the person before returning the BFF’s code.', 'This summary stage represents successful realm-hosted browser authentication and authorization. A does not accept an unverified browser assertion that the person signed in. The main diagram explains password/passkey/TOTP message details.', ['Required account and authorization checks succeeded'], 'password'),
  webLabS('web-bff-code-return', 'Send the BFF callback through the browser', 'realmA', 'browser', [...webLabOp(['webCode'], 'create', 'realmA', 'Creates a short-lived one-use BFF code bound to callback and PKCE.'), ...webLabOp(['webLocation'], 'derive', 'realmA', 'Creates the BFF backend callback URL with original state.'), ...webLabWire(['webLocation', 'webCode', 'webState'], 'realmA', 'browser', 'The redirect carries code/state to the registered BFF callback.', 'Location backend callback URL')], [labP('HTTP', '302 Found'), webLabP('webLocation', webLabBffCallback + '?code=c_web_demo_1&state=st_web_demo_1'), webLabP('webCode'), webLabP('webState')], 'The browser follows A’s redirect to the backend callback.', 'No OAuth tokens are returned in this browser redirect. The backend callback will receive code/state, with its own original verifier still retained server-side.', [], 'return'),
  webLabS('web-bff-callback', 'Deliver and validate the backend callback', 'browser', 'app', [...webLabWire(['webCode', 'webState'], 'browser', 'app', 'Browser calls the registered BFF HTTPS callback.', 'callback request query'), ...webLabOp(['webState', 'webRedirectUri'], 'verify', 'app', 'Checks original backend-held state and the protected requesting-browser login context.'), ...webLabOp(['webCode'], 'store', 'app', 'Accepts the callback code only for redemption after state validation.')], [labP('HTTP', 'GET ' + webLabBffCallback), webLabP('webCode'), webLabP('webState')], 'The backend checks that this callback belongs to its pending login.', 'The BFF, rather than browser JavaScript, validates its original state and callback context and redeems the code. The browser-held frontend does not receive the server’s PKCE verifier or client_secret.', ['Original backend login context + state match'], 'return'),
  webLabS('web-bff-token-request', 'Redeem with backend-only client authentication', 'app', 'realmA', [...webLabOp(['webClientId', 'webClientSecret'], 'use', 'app', 'Uses the confidential registration identity and retained credential.'), ...webLabOp(['webClientAuth'], 'derive', 'app', 'Constructs Basic client authentication locally.'), ...webLabWire(['webClientAuth', 'webGrantType', 'webCode', 'webRedirectUri', 'webVerifier'], 'app', 'realmA', 'Backend HTTPS token request carries Basic client authentication and the original PKCE verifier.', 'Authorization Basic + token form body'), ...webLabOp(['webClientAuth', 'webClientId', 'webCode', 'webRedirectUri'], 'verify', 'realmA', 'Authenticates the client and checks code/client/callback binding.'), ...webLabOp(['webChallenge'], 'derive', 'realmA', 'Recomputes S256 from the received verifier.'), ...webLabOp(['webVerifier', 'webChallenge'], 'verify', 'realmA', 'Checks the original PKCE commitment before token issuance.')], [labP('HTTP', 'POST ' + webLabToken), webLabP('webClientAuth'), webLabP('webGrantType'), webLabP('webCode'), webLabP('webRedirectUri', webLabBffCallback), webLabP('webVerifier')], 'The backend authenticates itself and proves its original PKCE request.', 'HTTP Basic identifies bff-web as the username and carries its protected client_secret as the password. The body contains grant_type, code, identical redirect_uri and code_verifier; this teaching Basic variant does not duplicate client_id in the body. Neither secret passes through the browser.', ['Confidential client authenticated', 'Client/callback/code binding valid', 'S256 verifier commitment matches']),
  webLabTokenResult('web-bff-tokens', 'app', 'bff-web'),
  webLabS('web-bff-session-create', 'Validate identity and create a server-held session', 'app', 'app', [...webLabOp(['webClientId', 'webJwksUri', 'webKeys'], 'use', 'app', 'Uses the BFF client ID and trusted issuer key material.'), ...webLabOp(['webIdToken', 'webSignature', 'webAlgorithm', 'webIssuer', 'webIdAudience', 'webExpiry', 'webIssuedAt', 'webNonce'], 'verify', 'app', 'Checks signature, exact issuer, BFF client audience, time and original nonce.'), ...webLabOp(['webIdToken', 'webAccessToken', 'webRefreshToken'], 'store', 'app', 'Retains only issued OAuth tokens on the backend.'), ...webLabOp(['webSession', 'webCookie'], 'create', 'app', 'Creates an opaque browser session handle mapped to the validated account and server-held token store.')], [webLabP('webIdAudience', 'bff-web'), webLabP('webSession'), webLabP('webCookie')], 'The BFF stores the tokens and creates an opaque application session.', 'The backend verifies the OIDC result and keeps access/refresh tokens, nonce and verifier away from browser JavaScript. It creates a distinct application session cookie after validation. Cookie security and appropriate CSRF checks remain backend responsibilities.'),
  webLabS('web-bff-cookie', 'Give the browser only the session cookie', 'app', 'browser', webLabWire(['webCookie'], 'app', 'browser', 'Sends an opaque session handle with Secure/HttpOnly/SameSite policy; no OAuth tokens.', 'Set-Cookie response header'), [labP('HTTP', '302 → signed-in frontend'), webLabP('webCookie')], 'The browser receives a protected opaque handle for its BFF session.', 'HttpOnly prevents frontend JavaScript from reading this cookie. The cookie value does not contain an access_token, refresh_token, ID token, verifier or client_secret. Browser requests are bound to the backend’s session and application policy.'),
  webLabS('web-bff-data-request', 'Ask the BFF for application data', 'browser', 'app', [...webLabWire(['webCookie'], 'browser', 'app', 'Browser automatically sends its same-origin session cookie to the BFF.', 'Cookie request header'), ...webLabOp(['webSession', 'webCookie'], 'verify', 'app', 'Resolves and validates the opaque application session, expiry and request policy.')], [labP('HTTP', 'GET ' + webLabBffOrigin + '/api/orders'), webLabP('webCookie', '__Host-bff_session=<opaque>')], 'The frontend uses its cookie to ask the BFF for orders.', 'The browser makes a same-origin read request to its BFF. It sends no API OAuth bearer token. For state-changing cookie-authenticated operations, the BFF additionally enforces suitable CSRF protection; SameSite alone is not presented as a universal replacement.'),
  webLabApiRequest('web-bff-api-request', 'app', 'The BFF retrieves the authorized server-held access token for this validated application session and calls the separate API.'),
  webLabApiVerify('web-bff-api-verify'),
  webLabResourceResponse('web-bff-api-response', 'app'),
  webLabS('web-bff-ui-response', 'Return application data to the frontend', 'app', 'browser', webLabWire(['webResource', 'webHttpStatus'], 'app', 'browser', 'Returns application data to the authenticated browser session, without forwarding OAuth tokens.', 'BFF application response'), [labP('HTTP', '200 OK', undefined, 'webHttpStatus'), webLabP('webResource')], 'The web frontend displays the orders while the tokens remain on the BFF.', 'The BFF returns only the authorized resource representation to the browser. The frontend cookie and API bearer token are separate credentials for separate recipients.', [], 'complete'),
];

const webLabIntrospectionIds = ['webActive', 'webIssuer', 'webSubject', 'webApiAudience', 'webApiScope', 'webExpiry'];
const webLabIntrospectionSteps = [
  webLabS('web-intro-client-request', 'Send the presented access token to the API', 'app', 'realmB', [...webLabOp(['webBearerHeader'], 'derive', 'app', 'Constructs the bearer header from the access token obtained by a prior approved grant.'), ...webLabWire(['webBearerHeader', 'webAccessToken'], 'app', 'realmB', 'Presents the access token to its intended API.', 'Authorization Bearer request header')], [labP('HTTP', 'GET ' + webLabApiUrl), webLabP('webBearerHeader', 'Bearer <lightweight-access-token>')], 'The client calls the API with an access token whose full claims need introspection.', 'This Keycloak example uses a lightweight JWT access token with selected claims omitted by configured mappers. It is still a JWT, not Keycloak’s default opaque-token format. An API treating a generic OAuth token as opaque can use the same RFC 7662 pattern. The API does not replace the access token with id_token.'),
  webLabS('web-intro-prepare', 'Prepare the API’s authenticated introspection call', 'realmB', 'realmB', [...webLabOp(['webIntrospectionEndpoint', 'webIntrospectionClientId', 'webIntrospectionSecret'], 'use', 'realmB', 'Uses the API’s own trusted introspection endpoint and protected confidential-client credentials.'), ...webLabOp(['webIntrospectionAuth'], 'derive', 'realmB', 'Constructs HTTP Basic client authentication locally.'), ...webLabOp(['webAccessToken'], 'use', 'realmB', 'Uses the exact bearer access credential received on this request.'), ...webLabOp(['webIntrospectionToken'], 'derive', 'realmB', 'Copies the presented access_token into the token form parameter.'), ...webLabOp(['webTokenTypeHint'], 'use', 'realmB', 'Selects the optional access_token token-type hint.')], [webLabP('webIntrospectionEndpoint'), webLabP('webIntrospectionClientId'), webLabP('webIntrospectionToken'), webLabP('webTokenTypeHint')], 'The resource API authenticates using its own protected registration.', 'Keycloak permits confidential clients to invoke token introspection. The API’s client_secret is separate from the user’s bearer token and from a BFF credential. It stays local and is protected inside the Basic header on the TLS request.'),
  webLabS('web-intro-query', 'Query the exact access token', 'realmB', 'realmA', [...webLabWire(['webIntrospectionAuth', 'webIntrospectionToken', 'webTokenTypeHint'], 'realmB', 'realmA', 'Authenticated RFC 7662 request sends the token under inspection in the form body.', 'Authorization Basic + introspection form body'), ...webLabWire(['webAccessToken'], 'realmB', 'realmA', 'The exact received access-token object is the value of the token form parameter; access_token is not an additional body member.', 'introspection form token value'), ...webLabOp(['webIntrospectionAuth', 'webIntrospectionClientId'], 'verify', 'realmA', 'Authenticates and authorizes this confidential API to query the presented token.')], [labP('HTTP', 'POST ' + webLabIntrospect), webLabP('webIntrospectionAuth'), webLabP('webIntrospectionToken'), webLabP('webTokenTypeHint')], 'A receives an authorized token-status query from the API.', 'The token form value is the user’s presented access token; the Authorization Basic header authenticates the querying API. An invalid API credential would produce an introspection authentication error, which is separate from an inactive token result.'),
  webLabS('web-intro-evaluate', 'Determine active status and authorized claims', 'realmA', 'realmA', [...webLabOp(['webIntrospectionToken'], 'verify', 'realmA', 'Checks the exact token, issuer state, expiry and the API’s permission to inspect it.'), ...webLabOp(webLabIntrospectionIds, 'create', 'realmA', 'Builds active status and the configured claims allowed in this API’s introspection result.')], [webLabP('webActive', 'true'), webLabP('webApiAudience'), webLabP('webApiScope')], 'A checks whether the presented token is active for this introspection request.', 'The configured Keycloak Add to token introspection mapper settings supply the needed subject/audience/scope claims. Only active is mandatory in RFC 7662; other fields are returned as configured and authorized. An inactive or unknown token returns HTTP 200 with active=false and normally no sensitive additional claims.'),
  webLabS('web-intro-result', 'Return the authenticated introspection result', 'realmA', 'realmB', webLabWire(webLabIntrospectionIds, 'realmA', 'realmB', 'Returns active status and configured claims in the JSON introspection result.', 'introspection response JSON members'), [labP('HTTP', '200 OK'), webLabP('webActive', 'true'), webLabP('webIssuer'), webLabP('webSubject'), webLabP('webApiAudience'), webLabP('webApiScope'), webLabP('webExpiry')], 'The API receives token status and the claims needed for its policy.', 'This example uses the JSON introspection result. The deprecated Keycloak Accept: application/jwt introspection extension is not used. The response is authenticated by the trusted endpoint/TLS and confidential client context; the caller must still evaluate active status and its own authorization policy.'),
  webLabS('web-intro-api-check', 'Check active status, audience and permissions', 'realmB', 'realmB', [...webLabOp(['webPermissions'], 'use', 'realmB', 'Reads its own expected API audience and operation-permission policy.'), ...webLabOp(['webActive', 'webIssuer', 'webApiAudience', 'webExpiry', 'webApiScope'], 'verify', 'realmB', 'Requires active=true and trusted issuer, intended API audience, valid time and needed granted scope.'), ...webLabOp(['webSubject'], 'use', 'realmB', 'Uses the trusted introspected subject after the policy checks.')], [webLabP('webActive', 'true'), webLabP('webApiAudience'), webLabP('webApiScope'), webLabP('webPermissions')], 'An active token still has to meet the API’s authorization policy.', 'The API rejects inactive or unusable credentials. For active=true it still verifies the expected audience, required configured claims, lifetime and permissions. If a required claim is absent it fails closed rather than interpreting active=true as unrestricted access. Any introspection cache is bounded by token expiry and the chosen revocation-freshness policy.', ['active=true', 'Trusted issuer + intended API audience', 'Required claims and time validity', 'Required permission present']),
  webLabResourceResponse('web-intro-resource', 'app'),
  webLabS('web-intro-expired-request', 'Separate case · present an expired access token', 'app', 'realmB', webLabWire(['webBearerHeader', 'webAccessToken'], 'app', 'realmB', 'A different API request presents an expired bearer token.', 'Authorization Bearer header'), [labP('HTTP', 'GET ' + webLabApiUrl), webLabP('webBearerHeader', 'Bearer <expired-access-token>')], 'A separate client request now presents an unusable token.', 'This is an independent example after the successful path, not a token revoked by that response. The API will query this exact expired credential before deciding its own bearer response.'),
  webLabS('web-intro-inactive-query', 'Introspect this separate expired credential', 'realmB', 'realmA', [...webLabOp(['webAccessToken'], 'use', 'realmB', 'Uses the expired credential received in this separate API request.'), ...webLabOp(['webIntrospectionToken'], 'derive', 'realmB', 'Copies that exact credential into the token parameter.'), ...webLabWire(['webIntrospectionAuth', 'webIntrospectionToken', 'webTokenTypeHint'], 'realmB', 'realmA', 'Makes an authorized introspection query for the separate expired credential.', 'Authorization Basic + introspection form body'), ...webLabWire(['webAccessToken'], 'realmB', 'realmA', 'The exact expired access-token object is the token form value.', 'introspection form token value'), ...webLabOp(['webIntrospectionAuth', 'webIntrospectionToken'], 'verify', 'realmA', 'Checks the API query is authorized and determines that this separate credential is expired.')], [labP('HTTP', 'POST ' + webLabIntrospect), webLabP('webIntrospectionAuth'), webLabP('webIntrospectionToken', '<expired-access-token>'), webLabP('webTokenTypeHint')], 'The API authenticates its query while the inspected credential is inactive.', 'The API client credential is valid, so the introspection call itself is authorized. The user access token being inspected has expired; these are separate authentication objects.'),
  webLabS('web-intro-inactive-note', 'Compare the separate inactive-token outcome', 'realmA', 'realmB', [...webLabOp(['webActive'], 'create', 'realmA', 'For a different expired/revoked/unknown token, creates active=false.'), ...webLabWire(['webActive'], 'realmA', 'realmB', 'An inactive-token query succeeds as HTTP 200 with active=false.', 'separate inactive introspection response')], [labP('HTTP', '200 OK'), webLabP('webActive', 'false')], 'A separate inactive-token query returns status information, without granting API access.', 'This is an alternative example for a different token, after the successful path above. active=false prevents API access; it is not HTTP 401 from the introspection endpoint. The API can map this unusable bearer credential to its own 401 invalid_token response.', [], 'complete'),
  webLabS('web-intro-reject-inactive', 'Reject the inactive bearer credential at the API', 'realmB', 'app', [...webLabOp(['webActive'], 'verify', 'realmB', 'Rejects active=false before returning any protected resource.'), ...webLabOp(['webHttpStatus', 'webChallengeHeader', 'webBearerError'], 'create', 'realmB', 'Creates the API bearer challenge for this unusable access token.'), ...webLabWire(['webHttpStatus', 'webChallengeHeader', 'webBearerError'], 'realmB', 'app', 'Returns the API 401 invalid_token challenge; the introspection endpoint itself returned HTTP 200.', 'HTTP status + WWW-Authenticate auth-params')], [labP('HTTP', '401 Unauthorized', undefined, 'webHttpStatus'), webLabP('webChallengeHeader', 'Bearer error="invalid_token"'), webLabP('webBearerError', 'invalid_token', 'Inside WWW-Authenticate')], 'The API refuses protected data for the inactive credential.', 'The client sees the API’s 401 invalid_token result. This is distinct from the issuer’s successful HTTP 200 token-status query, which returned active=false. The error never grants a replacement token or additional permission.', [], 'complete'),
];

const webLabErrorSteps = [
  webLabS('web-error-invalid-request', 'Case 1 · present an expired access token', 'app', 'realmB', webLabWire(['webBearerHeader', 'webAccessToken', 'webExpiry'], 'app', 'realmB', 'First independent request carries an expired bearer access token.', 'Authorization Bearer header; exp nested in JWT'), [labP('HTTP', 'GET ' + webLabApiUrl), webLabP('webBearerHeader', 'Bearer <expired-access-token>'), webLabP('webExpiry', 'An instant before the API’s current time', 'Inside the presented JWT')], 'An invalid or expired credential cannot authenticate the API request.', 'This first request example has an expired access token. It does not receive protected resource data, even if its former scopes would have been sufficient.'),
  webLabS('web-error-invalid-check', 'Reject the invalid credential', 'realmB', 'realmB', [...webLabOp(['webExpiry', 'webAccessToken'], 'verify', 'realmB', 'Rejects the expired or otherwise invalid bearer credential before authorizing the resource.'), ...webLabOp(['webHttpStatus', 'webChallengeHeader', 'webBearerError'], 'create', 'realmB', 'Constructs the 401 invalid_token bearer challenge.')], [webLabP('webHttpStatus', '401'), webLabP('webBearerError', 'invalid_token')], 'The API rejects token validity before returning data.', 'Expiry, bad signature, wrong issuer/audience or another invalid-token condition rejects this credential. Here the demonstrated cause is expiry. The authentication challenge is an HTTP header, not a successful token response.'),
  webLabS('web-error-401', 'Return 401 · invalid_token', 'realmB', 'app', webLabWire(['webHttpStatus', 'webChallengeHeader', 'webBearerError'], 'realmB', 'app', 'Returns a bearer authentication challenge for an invalid token.', 'HTTP status + WWW-Authenticate auth-params'), [labP('HTTP', '401 Unauthorized'), webLabP('webChallengeHeader', 'Bearer error="invalid_token"'), webLabP('webBearerError', 'invalid_token', 'Inside WWW-Authenticate')], 'The client must obtain a usable credential before retrying.', 'RFC 6750’s invalid_token outcome uses the illustrated 401. A permitted token refresh or a new authorization can obtain a valid token; this response itself does not issue one or reveal an issuer private key.'),
  webLabS('web-error-audience-request', 'Case 2 · present a token for another API', 'app', 'realmB', webLabWire(['webBearerHeader', 'webAccessToken', ...webLabAccessClaims, ...webLabJose], 'app', 'realmB', 'A separate request carries a signed and unexpired token whose aud names other-api.', 'Authorization → access_token JWT'), [labP('HTTP', 'GET ' + webLabApiUrl), webLabP('webBearerHeader', 'Bearer <signed-other-api-access-token>'), webLabP('webAccessToken', 'Access-token JWS: aud=other-api, scope=orders:read; signed and unexpired'), webLabP('webApiAudience', 'other-api', 'Received claim inside the presented access token'), webLabP('webApiScope', 'orders:read', 'Inside the access token'), webLabP('webExpiry', 'An instant after the API’s current time', 'Inside the presented JWT')], 'This token has a valid signature and sufficient-looking scope, but was issued to a different recipient.', 'This is another independent API request, not a retry repaired by the preceding 401. Realm A issued the token for other-api. Orders API receives aud=other-api inside the signed access token; it must compare that received claim with its own locally configured orders-api identity.'),
  webLabS('web-error-audience-trust', 'Accept this token’s signature, issuer and time', 'realmB', 'realmB', [...webLabOp(['webKeys', 'webJwksUri'], 'use', 'realmB', 'Uses trusted Realm A verification keys.'), ...webLabOp(['webAlgorithm', 'webSignature', 'webIssuer', 'webExpiry', 'webIssuedAt'], 'verify', 'realmB', 'The allowed algorithm, signature, exact issuer and token time checks pass for this independent token.')], [labP('Local result', 'Signature, issuer and lifetime valid; audience still unchecked'), webLabP('webApiAudience', 'other-api', 'Received token claim; no recipient decision yet'), webLabP('webExpiry', 'An instant after the API’s current time')], 'Cryptographic authenticity and current validity pass; the intended-recipient check remains.', 'A signature proves which trusted issuer created this token. It does not make the token acceptable at every API. This access token is unexpired and authentic, but its aud still names other-api. Required-scope checks and protected data access have not run.', ['Allowed algorithm + valid issuer signature', 'Exact Realm A issuer', 'Token unexpired']),
  webLabS('web-error-audience-check', 'Reject the wrong audience before checking scope', 'realmB', 'realmB', [...webLabOp(['webExpectedApiAudience'], 'use', 'realmB', 'Reads Orders API’s own configured recipient identifier orders-api; the client cannot choose this expected value.'), ...webLabOp(['webApiAudience'], 'verify', 'realmB', 'Compares received aud=other-api with expected orders-api. No audience member matches, so reject this token before scope checks.'), ...webLabOp(['webHttpStatus', 'webChallengeHeader', 'webBearerError'], 'create', 'realmB', 'Creates 401 invalid_token because the authentic token is not intended for this API.')], [webLabP('webApiAudience', 'other-api', 'Received claim inside the token'), webLabP('webExpectedApiAudience', 'orders-api', 'Local API policy; never transmitted'), labP('Local comparison', 'other-api does not contain orders-api → reject'), webLabP('webHttpStatus', '401'), webLabP('webBearerError', 'invalid_token')], 'Orders API rejects a token addressed to other-api, even though it grants orders:read.', 'The recipient must identify itself in aud. Here received aud=other-api does not include expected orders-api, so this API rejects the credential. Granting orders:read cannot repair the recipient mismatch; scope checking is not reached and no protected resource is returned. A recipient can be one string or a member of an audience array; this example uses one string.', ['Received aud: other-api', 'Expected API recipient: orders-api', 'Audience membership fails', 'Stop before scope checks and resource access']),
  webLabS('web-error-audience-401', 'Return 401 · token is for another API', 'realmB', 'app', webLabWire(['webHttpStatus', 'webChallengeHeader', 'webBearerError'], 'realmB', 'app', 'Returns the API bearer challenge for an access token with the wrong intended recipient.', 'HTTP status + WWW-Authenticate auth-params'), [labP('HTTP', '401 Unauthorized'), webLabP('webChallengeHeader', 'Bearer error="invalid_token"'), webLabP('webBearerError', 'invalid_token', 'Inside WWW-Authenticate')], 'The client receives invalid_token rather than insufficient_scope.', 'This response does not modify the token’s signed audience, issue a replacement token or grant additional permission. The client needs an issuer-authorized access token intended for orders-api. The next case is a different request with a different token.', [], 'complete'),
  webLabS('web-error-scope-request', 'Case 3 · present a valid token missing write permission', 'app', 'realmB', webLabWire(['webBearerHeader', 'webAccessToken', ...webLabAccessClaims, ...webLabJose], 'app', 'realmB', 'A separate request presents a valid access token granting only orders:read.', 'Authorization → access_token JWT'), [labP('HTTP', 'POST ' + webLabApiUrl), webLabP('webBearerHeader', 'Bearer <valid-read-only-access-token>'), webLabP('webApiScope', 'orders:read', 'Inside the access token')], 'This independent token is valid but cannot authorize an order write.', 'This is a separate request case with a usable token; it is not a token magically repaired by the preceding 401. The requested POST operation requires orders:write, but this token only grants orders:read.'),
  webLabS('web-error-validity', 'Verify the token before checking permissions', 'realmB', 'realmB', [...webLabOp(['webKeys', 'webJwksUri'], 'use', 'realmB', 'Uses trusted issuer verification keys.'), ...webLabOp(['webAlgorithm', 'webSignature', 'webIssuer', 'webApiAudience', 'webExpiry'], 'verify', 'realmB', 'Validates algorithm/signature, issuer, intended API audience and token time.')], [labP('Local result', 'Token authenticity and validity checks succeeded')], 'The API accepts token trust and validity for this third case.', 'Successful authentication does not authorize every operation. The API proceeds to its own write-permission check only after this token passes trust and validity checks.'),
  webLabS('web-error-permission', 'Fail the required write-permission check', 'realmB', 'realmB', [...webLabOp(['webPermissions'], 'use', 'realmB', 'Reads the protected POST operation’s local orders:write requirement.'), ...webLabOp(['webApiScope'], 'verify', 'realmB', 'Finds the required write permission absent from the granted read-only scope.'), ...webLabOp(['webHttpStatus', 'webChallengeHeader', 'webBearerError', 'webRequiredScope'], 'create', 'realmB', 'Constructs 403 insufficient_scope and advertises the required scope in the challenge.')], [webLabP('webPermissions', 'POST /orders requires orders:write'), webLabP('webApiScope', 'orders:read'), webLabP('webRequiredScope', 'orders:write')], 'A valid token is refused because the requested operation needs a different permission.', 'The API cannot grant a missing scope itself. It returns no protected write result. The requesting client needs issuer-authorized additional permission; blindly retrying with the same token does not satisfy the policy.'),
  webLabS('web-error-403', 'Return 403 · insufficient_scope', 'realmB', 'app', webLabWire(['webHttpStatus', 'webChallengeHeader', 'webBearerError', 'webRequiredScope'], 'realmB', 'app', 'Returns the bearer challenge showing the required permission.', 'HTTP status + WWW-Authenticate auth-params'), [labP('HTTP', '403 Forbidden'), webLabP('webChallengeHeader', 'Bearer error="insufficient_scope", scope="orders:write"'), webLabP('webBearerError', 'insufficient_scope', 'Inside WWW-Authenticate'), webLabP('webRequiredScope', 'orders:write', 'Inside WWW-Authenticate')], 'The client receives a permission failure rather than an invalid-token failure.', 'The token was valid; the requested write lacked scope. This 403 challenge does not revoke or replace the token. Authentication and authorization are separate checks.', [], 'complete'),
  webLabApiRequest('web-error-success-request', 'app', 'Case 4 is another independent GET request with a valid orders:read access token.'),
  webLabApiVerify('web-error-success-check', 'Case 4 · accept valid token and read permission'),
  webLabResourceResponse('web-error-success-response', 'app'),
];

// Each authored result binds its own status and bearer challenge. The generic
// glossary lists alternative outcomes; it is not the value of one response.
const webLabErrorResponseValues = {
  'web-error-invalid-check': {webHttpStatus:'401 Unauthorized',webChallengeHeader:'Bearer error="invalid_token"',webBearerError:'invalid_token'},
  'web-error-401': {webHttpStatus:'401 Unauthorized',webChallengeHeader:'Bearer error="invalid_token"',webBearerError:'invalid_token'},
  'web-error-audience-check': {webHttpStatus:'401 Unauthorized',webChallengeHeader:'Bearer error="invalid_token"',webBearerError:'invalid_token'},
  'web-error-audience-401': {webHttpStatus:'401 Unauthorized',webChallengeHeader:'Bearer error="invalid_token"',webBearerError:'invalid_token'},
  'web-error-permission': {webHttpStatus:'403 Forbidden',webChallengeHeader:'Bearer error="insufficient_scope", scope="orders:write"',webBearerError:'insufficient_scope',webRequiredScope:'orders:write'},
  'web-error-403': {webHttpStatus:'403 Forbidden',webChallengeHeader:'Bearer error="insufficient_scope", scope="orders:write"',webBearerError:'insufficient_scope',webRequiredScope:'orders:write'},
  'web-error-success-response': {webHttpStatus:'200 OK'},
};

// Every independent API case snapshots its own received credential and result.
// Focused local checks and response construction must retain the same value as
// their wire transmission, without falling back to another branch's example.
for (const item of webLabErrorSteps) {
  const wrongAudience=item.id.startsWith('web-error-audience-');
  item.attributeValues={
    webApiAudience:wrongAudience?'other-api':'orders-api',
    webExpectedApiAudience:'orders-api',
    webApiScope:'orders:read',
    webAccessToken:wrongAudience?'Access-token JWS: aud=other-api, scope=orders:read; signed and unexpired':item.id.startsWith('web-error-invalid-')?'Expired access-token JWS: aud=orders-api, scope=orders:read':'Access-token JWS: aud=orders-api, scope=orders:read; signed and unexpired',
    webBearerHeader:wrongAudience?'Bearer <signed-other-api-access-token>':item.id.startsWith('web-error-invalid-')?'Bearer <expired-access-token>':'Bearer <valid-read-only-access-token>',
    webExpiry:item.id.startsWith('web-error-invalid-')?'An instant before the API’s current time':'An instant after the API’s current time',
    ...(webLabErrorResponseValues[item.id]||{}),
  };
  const response=webLabErrorResponseValues[item.id];
  if(response)item.payload=item.payload.map(member=>{
    const id=member.attributeId||(member.name==='HTTP'?'webHttpStatus':undefined);
    return id&&Object.hasOwn(response,id)?{...member,attributeId:id,value:response[id]}:member;
  });
}

const webLabRotationSteps = [
  webLabS('web-rotation-cache', 'Start with cached trusted public keys', 'realmB', 'realmB', [...webLabOp(['webJwksUri', 'webKeys', 'webRefreshBudget'], 'use', 'realmB', 'Uses the already trusted issuer JWKS URL, initial public keys and bounded refresh policy.'), ...webLabOp(['webKeyCache'], 'store', 'realmB', 'Caches the initial trusted public key realm-sign-1 locally.')], [webLabP('webJwksUri'), webLabP('webKeyCache', 'Cached public key: realm-sign-1'), webLabP('webRefreshBudget')], 'The API already trusts A and has its earlier public signing key.', 'The trusted jwks_uri comes from validated issuer configuration, not from a token header. This scenario applies one bounded key refresh for an unknown kid; cache and request rate limits prevent untrusted tokens from causing unlimited fetches.'),
  webLabS('web-rotation-new-key', 'Provision the realm’s next signing key', 'realmA', 'realmA', [...webLabOp(['webSigningPrivateKey', 'webKid'], 'create', 'realmA', 'Creates/provisions a new protected issuer signing key and key identifier.'), ...webLabOp(['webKeys'], 'derive', 'realmA', 'Publishes only the new public verification material alongside the retained previous public key.')], [webLabP('webKid', 'realm-sign-2'), webLabP('webKeys')], 'A prepares its new signing key while retaining public verification overlap.', 'The new issuer private key stays inside Realm A. The public JWKS contains realm-sign-1 and realm-sign-2 for an appropriate transition period; the API’s old cached copy has not yet seen the second key. This is signing-key rotation, not WebAuthn credential rotation or JWE recipient-key rotation.'),
  webLabS('web-rotation-sign', 'Sign an authorized token with the new kid', 'realmA', 'realmA', [...webLabOp(['webSigningPrivateKey'], 'use', 'realmA', 'Signs the approved access-token claims with the protected new private key.'), ...webLabOp(['webAccessToken', 'webSignature', 'webKid', 'webAlgorithm', ...webLabAccessClaims], 'create', 'realmA', 'Creates a signed access token with kid=realm-sign-2 for the configured API audience.')], [webLabP('webKid', 'realm-sign-2'), webLabP('webAlgorithm', 'RS256'), webLabP('webApiAudience')], 'The new access-token header names realm-sign-2.', 'The original OAuth grant and permission approval already succeeded before this focused rotation stage. A signs the authorized access token with its new key and includes kid as a key selector. Decoded header metadata alone is not proof that the token is trusted.'),
  webLabS('web-rotation-issue', 'Deliver the newly signed access token', 'realmA', 'app', webLabWire(['webAccessToken', ...webLabJose, ...webLabAccessClaims], 'realmA', 'app', 'Returns the new signed access token to its authorized client.', 'token response access_token → JWT'), [webLabP('webAccessToken', 'JWT signed with realm-sign-2'), webLabP('webKid', 'realm-sign-2', 'Inside the JOSE header')], 'The client receives an access token signed with the new key.', 'The token response carries the signed credential, its public header and claims. The issuer’s private signing key is absent from the response.'),
  webLabApiRequest('web-rotation-api-request', 'app'),
  webLabS('web-rotation-unknown-kid', 'Notice that the header kid is unfamiliar', 'realmB', 'realmB', [...webLabOp(['webKid', 'webAlgorithm', 'webKeyCache', 'webRefreshBudget'], 'use', 'realmB', 'Reads untrusted header metadata and searches its trusted cached keys under the bounded refresh policy.'), ...webLabOp(['webKeyCache', 'webRefreshBudget'], 'verify', 'realmB', 'Finds no cached realm-sign-2 key and checks that a single trusted-source refresh remains allowed.'), ...labOp(['webJku'], 'inspect', 'realmB', 'Arbitrary token jku or embedded-key hints are not trusted key sources and are not followed.')], [webLabP('webKid', 'realm-sign-2'), webLabP('webKeyCache', 'Contains realm-sign-1 only'), webLabP('webRefreshBudget', 'One refresh permitted')], 'The API cannot yet verify this signature with its cached key set.', 'Unknown kid is a cache lookup result, not a signature success. The API selects its already trusted jwks_uri and enforces its allowed algorithm/key policy. It does not fetch arbitrary jku URLs, embedded JWKs or other attacker-selected key locations. This example contains no required jku field.'),
  webLabS('web-rotation-jwks-request', 'Refresh keys once from the trusted issuer', 'realmB', 'realmA', [...webLabOp(['webJwksUri', 'webRefreshBudget'], 'use', 'realmB', 'Uses the issuer-pinned HTTPS key endpoint and one allowed refresh attempt.'), ...webLabOp(['webRefreshBudget'], 'store', 'realmB', 'Consumes this request’s permitted refresh attempt so another miss cannot create a loop.'), ...webLabOp(['webJwksUri'], 'use', 'realmA', 'Serves the realm’s configured public verification key endpoint.')], [labP('HTTP', 'GET ' + webLabJwks), webLabP('webJwksUri')], 'The API fetches public keys from A’s configured JWKS endpoint.', 'The fetch destination is fixed by trusted issuer metadata/configuration. kid only selected the need for refresh; it did not supply a URL. This educational policy allows one refresh with rate limiting/caching, then verifies or rejects.'),
  webLabS('web-rotation-jwks-response', 'Return old and new public verification keys', 'realmA', 'realmB', [...webLabWire(['webKeys'], 'realmA', 'realmB', 'Publishes the JSON Web Key Set containing public verification keys only.', 'JWKS JSON keys array'), ...webLabOp(['webKeys', 'webKeyCache'], 'store', 'realmB', 'Updates the trusted local key cache with the fetched public issuer keys.')], [labP('HTTP', '200 OK'), webLabP('webKeys')], 'The refreshed trusted cache now contains realm-sign-2.', 'The public JWKS includes appropriate kty/use/alg/kid and public RSA parameters, with no private signing-key material. Recently retired public keys may remain during the rollover overlap. Trust comes from the pinned issuer endpoint and validated transport, not a matching kid alone.'),
  webLabApiVerify('web-rotation-verify', 'Verify the token using the refreshed trusted public key'),
  webLabResourceResponse('web-rotation-success', 'app'),
];

export const WEBLAB_SCENARIOS = [
  labScenario({ id: 'lab-spa-api', title: 'SPA → API · public Code + PKCE', summary: 'Browser JavaScript handles its HTTPS callback, redeems the code and presents a separate access token to a resource API.', category: 'SPA / API', status: 'supported', supportNote: 'Keycloak public OIDC client + application/resource-server checks. Detailed realm factor ceremonies are available in the main diagram. This SPA lab illustrates an OIDC validation policy and does not claim keycloak-js alone performs every signature check.', source: webLabAdapter, architecture: 'web', executionEnvironment: 'browser', clientActor: 'browser', protocol: 'oidc', hasPerson: true }, webLabAttrsFor(), webLabSpaSteps, { user: { name: 'Person', role: 'Starts and verifies account sign-in', plainRole: 'Chooses Sign in and completes the realm’s required method.', notes: ['The trusted realm checks the account credentials; the separate API checks access-token permissions.'], art: 'user' }, browser: webLabBrowserActor, realmA: webLabIssuerActor, realmB: webLabApiActor }),
  labScenario({ id: 'lab-bff-api', title: 'SPA + BFF → API · cookie / token boundary', summary: 'The browser uses an opaque application cookie; the confidential BFF performs Code + PKCE and keeps OAuth tokens on the backend.', category: 'SPA / API', status: 'supported', supportNote: 'Keycloak confidential OIDC client. BFF session, cookie attributes, CSRF and server-side API proxy behavior are application architecture choices.', source: webLabOAuth, architecture: 'web', executionEnvironment: 'server', clientActor: 'app', protocol: 'oidc', hasPerson: true }, webLabAttrsFor('bff-web', webLabBffCallback), webLabBffSteps, { browser: { name: 'Browser · web frontend', role: 'Cookie-authenticated frontend', plainRole: 'Uses its opaque BFF session cookie and displays the application data.', notes: ['The backend handles the OAuth callback and token exchange.', 'No OAuth tokens, client secret or PKCE verifier enter browser JavaScript.'], art: 'browser' }, app: { name: 'Backend for Frontend', role: 'Confidential OIDC client + API caller', plainRole: 'Keeps tokens securely and calls the API for your browser session.', notes: ['The actual OAuth client is the server-hosted BFF.', 'The browser cookie only references the BFF’s local session; the API receives a separate access token.'], art: 'webapp' }, realmA: webLabIssuerActor, realmB: webLabApiActor }),
  labScenario({ id: 'lab-api-introspection', title: 'API introspection · lightweight / opaque-token pattern', summary: 'A confidential resource API queries the exact presented access token, then checks active status, audience, time and permissions.', category: 'SPA / API', status: 'supported', supportNote: 'Keycloak lightweight access tokens remain JWTs and require configured claim mappers. RFC 7662 also supports generic opaque-token APIs. Keycloak introspection callers must be confidential; deprecated Accept: application/jwt is not used.', source: webLabIntrospection, architecture: 'web', protocol: 'oauth', hasPerson: false }, WEBLAB_ATTRIBUTES, webLabIntrospectionSteps, { app: webLabClientActor, realmA: webLabIssuerActor, realmB: { ...webLabApiActor, role: 'Resource API + confidential introspection client', notes: ['Keeps its own introspection client credential locally.', 'active=true does not waive audience, expiry or permission checks.', 'Required missing claims fail closed.'] } }),
  labScenario({ id: 'lab-api-errors', title: 'API outcomes · 401 vs 403 vs 200', summary: 'Compare independent requests: expired token, signed token for the wrong audience, valid token lacking required scope, and permitted read access.', category: 'SPA / API', status: 'supported', supportNote: 'RFC 6750 bearer challenges and RFC 7519 intended-recipient checks. Each case is an independent illustrative request; the error response never grants or repairs authorization.', source: webLabBearer, architecture: 'web', protocol: 'oauth', hasPerson: false }, WEBLAB_ATTRIBUTES, webLabErrorSteps, { app: webLabClientActor, realmB: webLabApiActor }),
  labScenario({ id: 'lab-jwks-rotation', title: 'API signing-key rotation · unknown kid', summary: 'A new kid triggers one bounded refresh from the trusted issuer JWKS, followed by full signature and permission checks.', category: 'SPA / API', status: 'supported', supportNote: 'Keycloak publishes realm public keys. OIDC signing-key rotation and JWT BCP apply; the single retry/rate-limiting behavior is an explicit application policy. Arbitrary token jku/key hints are not followed.', source: webLabOidc, architecture: 'web', protocol: 'oauth', hasPerson: false }, WEBLAB_ATTRIBUTES, webLabRotationSteps, { app: webLabClientActor, realmA: webLabIssuerActor, realmB: webLabApiActor }),
];
